CREATE TABLE next_destinations(
   city              VARCHAR(34) NOT NULL PRIMARY KEY
  ,lat               NUMERIC(9,6) NOT NULL
  ,lng               NUMERIC(9,6) NOT NULL
  ,country           VARCHAR(11) NOT NULL
  ,iso2              VARCHAR(2) NOT NULL
  ,admin             VARCHAR(10) NOT NULL
  ,capital           VARCHAR(7)
  ,population        INTEGER 
  ,population_proper INTEGER 
);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kabul',34.516667,69.183333,'Afghanistan','AF','Kābul','primary',3277000,3043532);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kandahār',31.613323,65.710126,'Afghanistan','AF','Kandahār','admin',715542,512200);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Jalālābād',34.426468,70.45153,'Afghanistan','AF','Nangarhār','admin',597971,205423);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Herāt',34.348167,62.199673,'Afghanistan','AF','Herāt','admin',481009,397456);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mazār-e Sharīf',36.709041,67.110866,'Afghanistan','AF','Balkh','admin',458151,272714);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kunduz',36.728955,68.857001,'Afghanistan','AF','Kunduz','admin',259809,161902);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ṯaghar',36.152481,68.737086,'Afghanistan','AF','Baghlān',NULL,218748,108449);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Lashkar Gāh',31.593817,64.371614,'Afghanistan','AF','Helmand','admin',201546,201546);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Maīmanah',35.921337,64.784058,'Afghanistan','AF','Fāryāb','admin',199795,199795);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Balkh',36.756352,66.897196,'Afghanistan','AF','Balkh','minor',179969,114883);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ghaznī',33.550833,68.4225,'Afghanistan','AF','Ghaznī','admin',141000,118785);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Gardēz',33.597439,69.225922,'Afghanistan','AF','Paktiyā','admin',103601,61760);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Shibirghān',36.667567,65.752904,'Afghanistan','AF','Jowzjān','admin',93241,55641);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Farāh',32.374508,62.116383,'Afghanistan','AF','Farāh','admin',73647,43561);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Andkhōy',36.952926,65.123761,'Afghanistan','AF','Fāryāb','minor',71730,29208);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Faīẕābād',37.116638,70.580022,'Afghanistan','AF','Badakhshān','admin',64704,40276);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Tāluqān',36.734133,69.533559,'Afghanistan','AF','Takhār','admin',64256,64256);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Pul-e Khumrī',35.944583,68.715122,'Afghanistan','AF','Baghlān','admin',56369,25689);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chārīkār',35.016585,69.174011,'Afghanistan','AF','Parwān','admin',53676,53676);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Asadābād',34.873113,71.14697,'Afghanistan','AF','Kunaṟ','admin',48400,48400);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Aībak',36.26468,68.015512,'Afghanistan','AF','Samangān','admin',24000,24000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Barakī Barak',33.967443,68.949199,'Afghanistan','AF','Lōgar','minor',22305,22305);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Karukh',34.481083,62.5863,'Afghanistan','AF','Herāt','minor',17484,11293);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mehtar Lām',34.671389,70.209444,'Afghanistan','AF','Laghmān','admin',17345,17345);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zarghūn Shahr',32.847343,68.445732,'Afghanistan','AF','Paktīkā',NULL,13737,13737);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qalāt',32.10575,66.908332,'Afghanistan','AF','Zābul','admin',12191,12191);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Tarīn Kōṯ',32.62675,65.873313,'Afghanistan','AF','Uruzgān','admin',10000,10000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Maḩmūd-e Rāqī',35.016406,69.344504,'Afghanistan','AF','Kāpīsā','admin',7407,7407);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qal‘ah-ye Now',34.987351,63.128911,'Afghanistan','AF','Bādghīs','admin',2997,2997);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dowlat Shāh',34.950397,70.071017,'Afghanistan','AF','Laghmān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dowlatyār',34.551319,65.793022,'Afghanistan','AF','Ghōr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Karbōṟī',34.965974,71.274601,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ḩāfiz̧ān',34.286652,70.372467,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mīr Bachah Kōṯ',34.749991,69.118987,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Nīlī',33.721777,66.130229,'Afghanistan','AF','Dāykundī','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kalān Deh',33.836765,68.402328,'Afghanistan','AF','Wardak','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kā’ī',34.128189,70.718277,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Āsmār',35.033328,71.358087,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dū Qal‘ah',32.142372,61.446899,'Afghanistan','AF','Farāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chimtāl',36.678179,66.803254,'Afghanistan','AF','Balkh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bāzārak',35.31292,69.51519,'Afghanistan','AF','Panjshir','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Nūrgal',34.613406,70.764975,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Salām Khēl',33.670666,69.329826,'Afghanistan','AF','Paktiyā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khulm',36.697362,67.698255,'Afghanistan','AF','Balkh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qarqīn',37.41853,66.043581,'Afghanistan','AF','Jowzjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qal‘ah-ye Kuhnah',32.615909,63.666807,'Afghanistan','AF','Farāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qal‘ah-ye Kūf',38.041189,70.472982,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Jalrēz',34.470796,68.654378,'Afghanistan','AF','Wardak','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Nādir Shāh Kōṯ',34.243477,70.728546,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alī Khēl',33.942528,69.719078,'Afghanistan','AF','Paktiyā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Fayrōz Kōh',34.519516,65.250935,'Afghanistan','AF','Ghōr','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khwājah Ghār',37.065883,69.421257,'Afghanistan','AF','Takhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Shērwānī-ye Bālā',35.014683,69.599342,'Afghanistan','AF','Kāpīsā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Now Dahānak',35.623977,70.005106,'Afghanistan','AF','Panjshir','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zindah Jān',34.342641,61.746747,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kanḏay',34.953598,70.778974,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bāzār-e Tālah',35.39205,68.223168,'Afghanistan','AF','Baghlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Āfāqī',36.661724,69.350952,'Afghanistan','AF','Takhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Nahrīn',36.064904,69.13343,'Afghanistan','AF','Baghlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qāshqāl',35.039747,69.006854,'Afghanistan','AF','Parwān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Māymay',38.40856,71.038385,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('March',37.528451,70.448201,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ōmnah',32.900288,68.796265,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qaranghū Tōghaī',37.215278,67.639722,'Afghanistan','AF','Balkh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khōst',33.339512,69.92041,'Afghanistan','AF','Khōst','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Markaz-e Sayyidābād',34.000367,68.713458,'Afghanistan','AF','Wardak','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mashhad',36.81665,70.102108,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chowṉêy',33.38278,66.272331,'Afghanistan','AF','Dāykundī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sarfirāz Kalā',32.983334,67.965167,'Afghanistan','AF','Ghaznī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bāsawul',34.247494,70.872177,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kuhsān',34.653889,61.197778,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Wulêswālī Bihsūd',34.343602,67.905671,'Afghanistan','AF','Wardak','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Anār Darah',32.758698,61.653969,'Afghanistan','AF','Farāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Spērah',33.202038,69.515203,'Afghanistan','AF','Khōst','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Nayak',34.734141,66.952921,'Afghanistan','AF','Bāmyān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ghulām ‘Alī',34.950758,69.228703,'Afghanistan','AF','Parwān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Gōshtah',34.358223,70.762642,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mardīān',36.992524,66.296541,'Afghanistan','AF','Jowzjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alāqahdārī Shāh Jōy',32.521541,67.413151,'Afghanistan','AF','Zābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ghōriyān',34.344798,61.493212,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ḩukūmatī Dahanah-ye Ghōrī',35.906168,68.488694,'Afghanistan','AF','Baghlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zamtō Kêlay',32.372604,66.177083,'Afghanistan','AF','Kandahār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Āq Tapah',36.976593,68.572239,'Afghanistan','AF','Kunduz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bābā Şāḩib',31.661439,65.660984,'Afghanistan','AF','Kandahār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ghurayd Gharamē',36.522204,70.790635,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chākarān',36.911119,71.0688,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Guz̄arah',34.212228,62.212353,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qal‘ah-ye Fārsī',33.785293,63.247354,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Pul-e ‘Alam',33.995289,69.02274,'Afghanistan','AF','Lōgar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dūāb',35.562772,67.821912,'Afghanistan','AF','Samangān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ţāqchah Khānah',36.619217,69.628052,'Afghanistan','AF','Takhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Deh-e Şalāḩ',35.690306,69.315105,'Afghanistan','AF','Baghlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Now Zād',32.403145,64.469588,'Afghanistan','AF','Helmand','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ḩājī Khēl',35.109218,69.433412,'Afghanistan','AF','Kāpīsā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khōshāmand',32.685667,68.238013,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chahār Qal‘ah',33.552672,68.29828,'Afghanistan','AF','Ghaznī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Pul-e Sangī',34.599721,69.259927,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dū Laīnah',34.155987,64.785665,'Afghanistan','AF','Ghōr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mīray',33.324624,68.440682,'Afghanistan','AF','Ghaznī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('S̲h̲ēwah',34.571693,70.588593,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bāzār-e Tashkān',36.881678,70.276738,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kajrān',33.203568,65.473112,'Afghanistan','AF','Dāykundī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Maīdān Shahr',34.395614,68.866179,'Afghanistan','AF','Wardak','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zīṟūk ‘Alāqahdārī',33.158056,69.312778,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Taywarah',33.521176,64.421156,'Afghanistan','AF','Ghōr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Darqad',37.384145,69.452941,'Afghanistan','AF','Takhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Shaykh Amīr Kêlay',33.287443,69.912834,'Afghanistan','AF','Khōst','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qaīşār',35.687469,64.293182,'Afghanistan','AF','Fāryāb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qal‘ah-ye Na‘īm',34.39951,69.167051,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Charkh',33.797122,68.937494,'Afghanistan','AF','Lōgar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Nūsay',38.443501,70.804133,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alāqahdārī Gēlān',32.726923,67.636964,'Afghanistan','AF','Ghaznī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Wuluswālī ‘Alīngār',34.835294,70.359302,'Afghanistan','AF','Laghmān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Lāsh-e Juwayn',31.713823,61.622723,'Afghanistan','AF','Farāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Fayẕābād',36.291111,64.862222,'Afghanistan','AF','Fāryāb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Faīẕābād',36.82091,66.459213,'Afghanistan','AF','Jowzjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alāqahdārī Dīshū',30.432057,63.298024,'Afghanistan','AF','Helmand','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Pachīr wa Āgām',34.200108,70.278061,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alāqahdārī Aṯghar',31.73506,67.357401,'Afghanistan','AF','Zābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mīrān',34.220375,68.312589,'Afghanistan','AF','Wardak','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zīārat-e Shāh Maqşūd',31.984801,65.473604,'Afghanistan','AF','Kandahār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dasht-e Qal‘ah',33.029783,63.839497,'Afghanistan','AF','Farāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dasht-e Qal‘ah',37.153904,69.443503,'Afghanistan','AF','Takhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ḩukūmat-e Shīnkaī',31.983034,67.335581,'Afghanistan','AF','Zābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khayr Kōṯ',32.853546,68.449715,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Tūlak',33.975086,63.72868,'Afghanistan','AF','Ghōr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Tsowkêy',34.692459,70.92688,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khānābād',36.683037,69.112793,'Afghanistan','AF','Kunduz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sarōbī',34.589615,69.760047,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chakaray',34.340986,69.437695,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khadīr',33.922324,65.93398,'Afghanistan','AF','Dāykundī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Baghlān',36.130684,68.708286,'Afghanistan','AF','Baghlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Urgūn',32.941111,69.18,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ibrāhīm Khān',35.05352,69.256539,'Afghanistan','AF','Parwān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Jurm',36.864768,70.834207,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bālā Murghāb',35.584191,63.329563,'Afghanistan','AF','Bādghīs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Narang',34.760091,71.047376,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Rabāţ-e Sangī-ye Pā’īn',34.799514,62.139172,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alīābād',36.521149,68.899849,'Afghanistan','AF','Kunduz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dehdādī',36.663187,66.993392,'Afghanistan','AF','Balkh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sulţānpūr-e ‘Ulyā',34.412045,70.296341,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Būrkah',36.222424,69.150375,'Afghanistan','AF','Baghlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chisht-e Sharīf',34.347308,63.739659,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alāqahdārī Kirān wa Munjān',36.028663,70.772575,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dōshī',35.609182,68.684729,'Afghanistan','AF','Baghlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sangar Sarāy',34.407438,70.639374,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Rū-ye Sang',35.319992,67.633871,'Afghanistan','AF','Bāmyān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Āqchah',36.905001,66.183407,'Afghanistan','AF','Jowzjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Shīnḏanḏ',33.302944,62.1474,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Barg-e Matāl',35.672831,71.343387,'Afghanistan','AF','Nūristān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Banū',35.633484,69.260195,'Afghanistan','AF','Baghlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kōṯowāl',34.103193,70.460734,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sar Chakān',35.701775,65.230553,'Afghanistan','AF','Fāryāb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zurmat',33.437782,69.02774,'Afghanistan','AF','Paktiyā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dāngām',34.992492,71.419355,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Pas Pul',37.47355,70.616173,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khulbisāt',33.494795,70.006054,'Afghanistan','AF','Khōst','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chandal Bā’ī',34.584694,68.955235,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bāgh-e Maīdān',35.221562,69.213967,'Afghanistan','AF','Parwān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kalakān',34.783706,69.150012,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Lāsh',35.378197,64.774567,'Afghanistan','AF','Fāryāb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Surkh Bilandī',34.684739,69.028632,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Nāyak',32.572298,66.774032,'Afghanistan','AF','Zābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Alah Sāy',34.8965,69.72049,'Afghanistan','AF','Kāpīsā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Siyāhgird',35.005529,68.855778,'Afghanistan','AF','Parwān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sar-e Pul',36.215443,65.932487,'Afghanistan','AF','Sar-e Pul','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alī Shēr ‘Alāqahdārī',33.436204,70.067109,'Afghanistan','AF','Khōst','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Māṉōgay',34.990152,70.913015,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khwājah Dū Kōh',36.828808,65.624321,'Afghanistan','AF','Jowzjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kaz̲h̲ah',34.240875,70.182738,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Shwāk',33.423862,69.376839,'Afghanistan','AF','Paktiyā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khinjān',35.589081,68.900928,'Afghanistan','AF','Baghlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Jānī Khēl',32.763148,68.397224,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sāyagaz',32.565214,67.033239,'Afghanistan','AF','Zābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Panjāb',34.387949,67.023273,'Afghanistan','AF','Bāmyān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khamyāb',37.5275,65.758333,'Afghanistan','AF','Jowzjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khākirān',32.838503,67.073771,'Afghanistan','AF','Zābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Yaḩyá Khēl',32.937423,68.64622,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Tsapêraī',33.830029,69.919197,'Afghanistan','AF','Paktiyā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mingajik',37.027901,66.128171,'Afghanistan','AF','Jowzjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Rāmak',33.522339,68.626396,'Afghanistan','AF','Ghaznī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Markaz-e Ḩukūmat-e Sulţān-e Bakwāh',32.241391,62.949361,'Afghanistan','AF','Farāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Injīl',34.301566,62.2465,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Langar',35.994741,68.050808,'Afghanistan','AF','Samangān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dê Nārkhēl Kêlay',32.432052,65.634838,'Afghanistan','AF','Kandahār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chāh Āb',37.397734,69.814644,'Afghanistan','AF','Takhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Stêr Giyān',32.977043,69.373077,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khandūd',36.951272,72.317998,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Wulêswālī Sayyid Karam',33.690563,69.368813,'Afghanistan','AF','Paktiyā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Māmā Khēl',34.244938,69.996803,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mīzān ‘Alāqahdārī',32.176351,66.512706,'Afghanistan','AF','Zābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Quchanghī',34.061826,66.278014,'Afghanistan','AF','Dāykundī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zaybāk',36.529474,71.344096,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Tsamkanī',33.802979,69.816708,'Afghanistan','AF','Paktiyā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bal Chirāgh',35.840263,65.230896,'Afghanistan','AF','Fāryāb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ḩāfiz̧ Moghul',37.056434,70.400606,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dehī',35.958063,67.279983,'Afghanistan','AF','Samangān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Pāshmūl',31.557203,65.434295,'Afghanistan','AF','Kandahār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kushkak',32.289906,61.521942,'Afghanistan','AF','Farāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Jabal us Sarāj',35.121491,69.23725,'Afghanistan','AF','Parwān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kishk-e Nakhūd',31.62519,65.055108,'Afghanistan','AF','Kandahār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Nāṟay',35.219953,71.522838,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Āq Kupruk',36.083517,66.840293,'Afghanistan','AF','Balkh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mutā Khān',33.240008,68.866296,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Tōrmay',33.688469,68.402045,'Afghanistan','AF','Ghaznī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Deh-e Now',34.747667,69.047844,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alāqahdārī Saṟōbī',32.793308,69.086601,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sangīn',32.072752,64.835903,'Afghanistan','AF','Helmand','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Wāshēr',32.251225,63.85553,'Afghanistan','AF','Helmand','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dowr-e Rabāţ',36.691324,68.790927,'Afghanistan','AF','Kunduz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kushk-e Kuhnah',34.871096,62.547621,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zīrakī',37.592334,70.558138,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sar-e Tayghān',33.50998,65.676323,'Afghanistan','AF','Dāykundī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Āb-e Kamarī',35.087955,63.067796,'Afghanistan','AF','Bādghīs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Darzāb',35.97744,65.378281,'Afghanistan','AF','Jowzjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Pārūn',35.420644,70.922612,'Afghanistan','AF','Nūristān','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khānaqāh',36.62587,69.536948,'Afghanistan','AF','Takhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Deh Khwāhān',37.889653,70.218753,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Adraskan',33.645728,62.269587,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('La‘l',34.501408,66.279965,'Afghanistan','AF','Ghōr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Muḩammad Āghah Wuluswālī',34.214216,69.100265,'Afghanistan','AF','Lōgar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khōshī',33.999159,69.215824,'Afghanistan','AF','Lōgar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bulōlah',34.877061,68.087903,'Afghanistan','AF','Bāmyān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alāqahdārī Yōsuf Khēl',33.051945,68.65,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kalafgān',36.772259,69.944894,'Afghanistan','AF','Takhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qarah Bāgh',34.940233,61.775888,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qarah Bāgh',33.198014,68.107977,'Afghanistan','AF','Ghaznī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Şayād',36.135292,65.829697,'Afghanistan','AF','Sar-e Pul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dowlatābād',36.432589,64.920713,'Afghanistan','AF','Fāryāb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dowlatābād',36.988211,66.82069,'Afghanistan','AF','Balkh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('‘Alāqahdārī-ye Almār',35.846163,64.530735,'Afghanistan','AF','Fāryāb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bāmyān',34.821558,67.827338,'Afghanistan','AF','Bāmyān','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qarah Bāgh Bāzār',34.852898,69.170619,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sharan',33.175678,68.730449,'Afghanistan','AF','Paktīkā','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Shahrak',34.107375,64.305199,'Afghanistan','AF','Ghōr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Shahrān',36.979844,70.739284,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qurghān',36.919393,65.064904,'Afghanistan','AF','Fāryāb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('’Unābah',35.232514,69.377187,'Afghanistan','AF','Panjshir','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Pasāband',33.68956,64.853103,'Afghanistan','AF','Ghōr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sōzmah Qal‘ah',36.099165,66.208226,'Afghanistan','AF','Sar-e Pul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Tītān',33.690323,63.863606,'Afghanistan','AF','Ghōr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Spīn Bōldak',31.00575,66.400013,'Afghanistan','AF','Kandahār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chahār Bāgh',37.001082,65.223922,'Afghanistan','AF','Fāryāb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Kirāmān',35.297298,69.681252,'Afghanistan','AF','Panjshir','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Istālif',34.832676,69.077557,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Jowand',35.063611,64.149167,'Afghanistan','AF','Bādghīs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dahan-e Jarf',34.928907,68.462727,'Afghanistan','AF','Parwān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Amānzī',30.211442,66.047647,'Afghanistan','AF','Kandahār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ḩukūmatī Azrah',34.173553,69.645728,'Afghanistan','AF','Lōgar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Nādir Shāh Kōṯ',33.306572,69.693806,'Afghanistan','AF','Khōst','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Imām Şāḩib',37.188974,68.936438,'Afghanistan','AF','Kunduz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zargarān',34.787639,69.05878,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ḏanḏar',34.790947,69.475037,'Afghanistan','AF','Parwān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ōbêh',34.369722,63.176389,'Afghanistan','AF','Herāt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Chinār',32.015826,65.107207,'Afghanistan','AF','Kandahār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sar Kāṉī',34.790227,71.10962,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khinj',35.428982,69.734823,'Afghanistan','AF','Panjshir','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Muqêr',32.820087,67.769341,'Afghanistan','AF','Ghaznī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zōr Kōṯ',33.541486,69.734456,'Afghanistan','AF','Khōst','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qaram Qōl',36.830063,65.042992,'Afghanistan','AF','Fāryāb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mūsá Qal‘ah',32.445653,64.744862,'Afghanistan','AF','Helmand','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Sang-e Māshah',33.139601,67.440455,'Afghanistan','AF','Ghaznī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khānaqāh',36.862785,66.166557,'Afghanistan','AF','Jowzjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ōkak',33.897935,67.956519,'Afghanistan','AF','Ghaznī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Darāyim',36.866667,70.383333,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Nīkêh',33.189341,69.271786,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Gereshk',31.820894,64.570048,'Afghanistan','AF','Helmand','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Farkhār',36.572884,69.857834,'Afghanistan','AF','Takhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Shahr-e Şafā',31.803466,66.323756,'Afghanistan','AF','Zābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qal‘ah-ye Shāhī',34.649212,70.5914,'Afghanistan','AF','Nangarhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Rustāq',37.126035,69.83045,'Afghanistan','AF','Takhār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Tukzār',35.948308,66.42132,'Afghanistan','AF','Sar-e Pul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khudāydād Khēl',35.178346,67.687582,'Afghanistan','AF','Bāmyān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Qarghah’ī',34.554024,70.24292,'Afghanistan','AF','Laghmān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Ḩukūmat-e Nād ‘Alī',31.642864,64.23982,'Afghanistan','AF','Helmand','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Dwah Manḏay',33.281588,69.585312,'Afghanistan','AF','Khōst','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khān Neshīn',30.548803,63.788801,'Afghanistan','AF','Helmand','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Wuṯahpūr',34.919136,71.098633,'Afghanistan','AF','Kunaṟ','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Maīdān Khūlah',33.649155,69.781204,'Afghanistan','AF','Paktiyā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bagrāmī',34.493761,69.274274,'Afghanistan','AF','Kābul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Pul-e Ḩişār',35.617945,69.47134,'Afghanistan','AF','Baghlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Gōmal Kêlay',32.509888,68.855982,'Afghanistan','AF','Paktīkā','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Mandōl',35.284031,70.170174,'Afghanistan','AF','Nūristān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Zaranj',30.966667,61.883333,'Afghanistan','AF','Nīmrōz','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Pasnay',35.766644,65.764862,'Afghanistan','AF','Sar-e Pul','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Khūgyāṉī',31.562667,66.581397,'Afghanistan','AF','Kandahār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,admin,capital,population,population_proper) VALUES ('Bahārak',37.002538,70.906643,'Afghanistan','AF','Badakhshān','minor',NULL,NULL);
