CREATE TABLE IF NOT EXISTS next_destinations(
   city              VARCHAR(10) NOT NULL
  ,lat               NUMERIC(9,6) NOT NULL
  ,lng               NUMERIC(9,6) NOT NULL
  ,country           VARCHAR(10) NOT NULL
  ,iso2              VARCHAR(2) NOT NULL
  ,auser             VARCHAR(10) NOT NULL
  ,capital           VARCHAR(7)
  ,population        INTEGER 
  ,population_proper INTEGER 
);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Minsk',53.9,27.566667,'Belarus','BY',NULL,'primary',1805000,1577138);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Homyel’',52.441667,30.983333,'Belarus','BY','Homyel’skaya Voblasts’','admin',480951,463724);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Mahilyow',53.913889,30.336389,'Belarus','BY','Mahilyowskaya Voblasts’','admin',369200,317854);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Vitsyebsk',55.1925,30.194444,'Belarus','BY','Vitsyebskaya Voblasts’','admin',342700,323937);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hrodna',53.7559,23.832,'Belarus','BY','Hrodzyenskaya Voblasts’',NULL,317365,254369);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brest',52.097548,23.687751,'Belarus','BY','Brestskaya Voblasts’','admin',300715,232835);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Babruysk',53.1384,29.2214,'Belarus','BY','Mahilyowskaya Voblasts’','minor',220517,205126);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Baranavichy',53.1327,26.0139,'Belarus','BY','Brestskaya Voblasts’','minor',168772,144257);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Barysaw',54.2279,28.505,'Belarus','BY','Minskaya Voblasts’','minor',155389,100000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Orsha',54.5081,30.4172,'Belarus','BY','Vitsyebskaya Voblasts’','minor',135206,125347);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pinsk',52.1229,26.0951,'Belarus','BY','Brestskaya Voblasts’','minor',130777,110900);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mazyr',52.0495,29.2456,'Belarus','BY','Homyel’skaya Voblasts’','minor',112137,89735);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maladzyechna',54.3167,26.854,'Belarus','BY','Minskaya Voblasts’','minor',101300,90810);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lida',53.883333,25.299722,'Belarus','BY','Hrodzyenskaya Voblasts’',NULL,100216,98036);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Polatsk',55.4879,28.7856,'Belarus','BY','Vitsyebskaya Voblasts’','minor',82258,76174);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vyetka',52.5591,31.1794,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Kobryn',52.216111,24.366389,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Pinsk',52.121389,26.072778,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Luninyets',52.250278,26.799444,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Byaroza',52.5314,24.9786,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dobrush',52.4089,31.3237,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brahin',51.787,30.2677,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Asipovichy',53.3011,28.6386,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Slawharad',53.4429,31.0014,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Klyetsk',53.0635,26.6321,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Smalyavichy',54.0249,28.0894,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chachersk',52.9164,30.9179,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chavusy',53.8098,30.9717,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pastavy',55.1136,26.8509,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kapyl’',53.1516,27.0913,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kastsyukovichy',53.3525,32.0514,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krychaw',53.7125,31.717,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shklow',54.2131,30.2877,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Salihorsk',52.7876,27.5415,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Orsha',54.515278,30.405278,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Braslaw',55.6413,27.0418,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krupki',54.3178,29.1374,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mahilyow',53.9168,30.3449,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Svyetlahorsk',52.6329,29.7389,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zhlobin',52.8926,30.024,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Astravyets',54.6145,25.9571,'Belarus','BY','Hrodzyenskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lyel’chytsy',51.7862,28.3288,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Drybin',54.1192,31.0939,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chashniki',54.8584,29.1608,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cherykaw',53.5689,31.3831,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Masty',53.4122,24.5387,'Belarus','BY','Hrodzyenskaya Voblasts’','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hlybokaye',55.1384,27.6905,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Homyel’',52.4345,30.9754,'Belarus','BY','Homyel’skaya Voblasts’','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hantsavichy',52.758,26.43,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Myadzyel',54.8789,26.9371,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bykhaw',53.521,30.2454,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Loyew',51.9458,30.7953,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khoyniki',51.8911,29.9552,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Staryya Darohi',53.0402,28.267,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ashmyany',54.421,25.936,'Belarus','BY','Hrodzyenskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rasony',55.9058,28.8135,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lyakhavichy',53.0388,26.2656,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalinkavichy',52.1323,29.3257,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krasnapollye',53.3353,31.3999,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lyozna',55.0247,30.797,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Slonim',53.0869,25.3163,'Belarus','BY','Hrodzyenskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Smarhon’',54.4798,26.3957,'Belarus','BY','Hrodzyenskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Haradok',55.4624,29.9845,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vilyeyka',54.4914,26.9111,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shchuchin',53.6014,24.7465,'Belarus','BY','Hrodzyenskaya Voblasts’','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Rechytsa',52.363889,30.394722,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mstsislaw',54.0185,31.7217,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vyerkhnyadzvinsk',55.7777,27.9389,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aktsyabrski',52.644,28.8801,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Narowlya',51.7961,29.5004,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zhytkavichy',52.2168,27.8561,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karma',53.1301,30.8016,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khotsimsk',53.4086,32.578,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lyuban’',52.7985,28.0048,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Yel’sk',51.8141,29.1522,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kobryn',52.2138,24.3564,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dokshytsy',54.8918,27.7667,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zhabinka',52.1984,24.0115,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hrodna',53.6884,23.8258,'Belarus','BY','Hrodzyenskaya Voblasts’','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horki',54.2862,30.9863,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hlusk',52.903,28.6845,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Slutsk',53.0274,27.5597,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sharkawshchyna',55.3689,27.4686,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Buda-Kashalyova',52.7179,30.5701,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malaryta',51.7905,24.074,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Byalynichy',53.9994,29.7141,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nyasvizh',53.2189,26.6779,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pyetrykaw',52.1289,28.4921,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Zhodzina',54.0985,28.3331,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Myory',55.6222,27.6281,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pruzhany',52.556,24.4573,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Talachyn',54.4087,29.6955,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Voranava',54.1492,25.3112,'Belarus','BY','Hrodzyenskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valozhyn',54.0892,26.5266,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rahachow',53.0934,30.0495,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kirawsk',53.2693,29.4752,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Luninyets',52.2472,26.8047,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ivatsevichy',52.709,25.3401,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horad Krychaw',53.698889,31.714167,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Klimavichy',53.6079,31.9586,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Klichaw',53.4923,29.3356,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dubrowna',54.5716,30.691,'Belarus','BY','Vitsyebskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kruhlaye',54.2497,29.7968,'Belarus','BY','Mahilyowskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rechytsa',52.3617,30.3916,'Belarus','BY','Homyel’skaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ivanava',52.1451,25.5365,'Belarus','BY','Brestskaya Voblasts’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lahoysk',54.2064,27.8512,'Belarus','BY','Minskaya Voblasts’','minor',NULL,NULL);
