CREATE TABLE IF NOT EXISTS next_destinations(
   city              VARCHAR(10) NOT NULL
  ,lat               NUMERIC(9,6) NOT NULL
  ,lng               NUMERIC(9,6) NOT NULL
  ,country           VARCHAR(10) NOT NULL
  ,iso2              VARCHAR(2) NOT NULL
  ,auser             VARCHAR(10) NOT NULL
  ,capital           VARCHAR(7)
  ,population        INTEGER 
  ,population_proper INTEGER 
);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Adjamé',5.350527,-4.024637,'Côte D’Ivoire','CI','Abidjan',NULL,3802000,3190395);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bouaké',7.693846,-5.030307,'Côte D’Ivoire','CI','Vallée du Bandama','admin',567481,454821);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Déraouan',6.890867,-6.423196,'Côte D’Ivoire','CI','Sassandra-Marahoué',NULL,255168,215652);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San-Pédro',4.748508,-6.636301,'Côte D’Ivoire','CI','Bas-Sassandra','admin',210273,196751);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Yamoussoukro',6.820548,-5.276741,'Côte D’Ivoire','CI','Yamoussoukro','primary',206499,194530);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Korhogo',9.458031,-5.629608,'Côte D’Ivoire','CI','Savanes','admin',177711,167359);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Man',7.412513,-7.55383,'Côte D’Ivoire','CI','Montagnes','admin',146974,139341);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Divo',5.83739,-5.357229,'Côte D’Ivoire','CI','Gôh-Djiboua','minor',127867,127867);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gagnoa',6.131934,-5.950601,'Côte D’Ivoire','CI','Gôh-Djiboua','admin',123184,99192);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Soubré',5.785556,-6.608333,'Côte D’Ivoire','CI','Bas-Sassandra',NULL,108933,58492);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Abengourou',6.729722,-3.496389,'Côte D’Ivoire','CI','Comoé','admin',104020,71598);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agboville',5.92801,-4.213186,'Côte D’Ivoire','CI','Lagunes','minor',81770,64285);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grand-Bassam',5.211796,-3.738839,'Côte D’Ivoire','CI','Comoé','minor',73772,48681);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dabou',5.325556,-4.376853,'Côte D’Ivoire','CI','Lagunes','admin',72913,69661);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dimbokro',6.64678,-4.70519,'Côte D’Ivoire','CI','Lacs','admin',67349,25586);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ferkessédougou',9.5928,-5.194487,'Côte D’Ivoire','CI','Savanes','minor',62008,52812);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bouaflé',6.990406,-5.744204,'Côte D’Ivoire','CI','Sassandra-Marahoué','minor',60962,60962);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bondoukou',8.040201,-2.800034,'Côte D’Ivoire','CI','Zanzan','admin',58297,18706);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Séguéla',7.961111,-6.673056,'Côte D’Ivoire','CI','Woroba','admin',51157,12603);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Odienné',9.505114,-7.564332,'Côte D’Ivoire','CI','Denguélé','admin',49857,19119);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Guiglo',6.543682,-7.493495,'Côte D’Ivoire','CI','Montagnes','minor',39134,35846);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Toumodi',6.557986,-5.017688,'Côte D’Ivoire','CI','Lacs','minor',39005,39005);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sassandra',4.95,-6.083333,'Côte D’Ivoire','CI','Bas-Sassandra','minor',38411,23274);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aboisso',5.467794,-3.207111,'Côte D’Ivoire','CI','Comoé','minor',37654,37654);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Touba',8.283333,-7.683333,'Côte D’Ivoire','CI','Woroba','minor',27504,27504);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Toulépleu',6.579742,-8.410906,'Côte D’Ivoire','CI','Montagnes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sakassou',7.454624,-5.292628,'Côte D’Ivoire','CI','Vallée du Bandama','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ayamé',5.605204,-3.157086,'Côte D’Ivoire','CI','Comoé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Béoumi',7.673951,-5.580855,'Côte D’Ivoire','CI','Vallée du Bandama','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Katiola',8.137278,-5.10095,'Côte D’Ivoire','CI','Vallée du Bandama','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alépé',5.500397,-3.663083,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dianra',8.943333,-6.254897,'Côte D’Ivoire','CI','Woroba','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tanda',7.803355,-3.168325,'Côte D’Ivoire','CI','Zanzan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Yakassé-Attobrou',6.181743,-3.651111,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Séguélon',9.356944,-7.120833,'Côte D’Ivoire','CI','Denguélé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sikensi',5.668294,-4.573709,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kounahiri',7.790886,-5.834766,'Côte D’Ivoire','CI','Woroba','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Koun-Fao',7.487638,-3.252493,'Côte D’Ivoire','CI','Zanzan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jacqueville',5.205148,-4.414604,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Guitry',5.519518,-5.240379,'Côte D’Ivoire','CI','Gôh-Djiboua','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Daloa',6.877355,-6.450221,'Côte D’Ivoire','CI','Sassandra-Marahoué','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kaniasso',9.814709,-7.512505,'Côte D’Ivoire','CI','Denguélé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Songon',5.319597,-4.254152,'Côte D’Ivoire','CI','Abidjan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tiapoum',5.136221,-3.023077,'Côte D’Ivoire','CI','Comoé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Abidjan',5.309657,-4.012656,'Côte D’Ivoire','CI','Abidjan','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mankono',8.058611,-6.189722,'Côte D’Ivoire','CI','Woroba','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Minignan',9.997442,-7.83593,'Côte D’Ivoire','CI','Denguélé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Azaguié',5.629841,-4.082041,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tabou',4.42295,-7.3528,'Côte D’Ivoire','CI','Bas-Sassandra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bongouanou',6.651749,-4.204061,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kouto',9.890289,-6.409215,'Côte D’Ivoire','CI','Savanes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grand-Lahou',5.250683,-5.003332,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Biankouma',7.739093,-7.613774,'Côte D’Ivoire','CI','Montagnes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Soubré',5.783766,-6.59388,'Côte D’Ivoire','CI','Bas-Sassandra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bonoua',5.27247,-3.596248,'Côte D’Ivoire','CI','Comoé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Danané',7.259572,-8.154981,'Côte D’Ivoire','CI','Montagnes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tiébissou',7.157722,-5.2248,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Téhini',9.60542,-3.658043,'Côte D’Ivoire','CI','Zanzan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oumé',6.383086,-5.417591,'Côte D’Ivoire','CI','Gôh-Djiboua','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Botro',7.852488,-5.310628,'Côte D’Ivoire','CI','Vallée du Bandama','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Niakaramandougou',8.657589,-5.291087,'Côte D’Ivoire','CI','Vallée du Bandama','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kani',8.478074,-6.605092,'Côte D’Ivoire','CI','Woroba','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kong',9.149434,-4.609823,'Côte D’Ivoire','CI','Savanes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bangolo',7.01232,-7.486395,'Côte D’Ivoire','CI','Montagnes','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bouna',9.269265,-2.995098,'Côte D’Ivoire','CI','Zanzan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zoukougbeu',6.76229,-6.8638,'Côte D’Ivoire','CI','Sassandra-Marahoué','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Méagui',5.404821,-6.558359,'Côte D’Ivoire','CI','Bas-Sassandra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Transua',7.550045,-3.014313,'Côte D’Ivoire','CI','Zanzan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ouaninou',8.237897,-7.866379,'Côte D’Ivoire','CI','Woroba','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Daoukro',7.058552,-3.964625,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gbéléban',9.584607,-8.131833,'Côte D’Ivoire','CI','Denguélé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bocanda',7.062635,-4.499484,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Doropo',9.810273,-3.344975,'Côte D’Ivoire','CI','Zanzan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Adzopé',6.106944,-3.861944,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kouassi-Kouassikro',7.341414,-4.67709,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zouan-Hounien',6.919371,-8.206503,'Côte D’Ivoire','CI','Montagnes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sipilou',7.8645,-8.101433,'Côte D’Ivoire','CI','Montagnes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Buyo',6.275344,-6.997038,'Côte D’Ivoire','CI','Bas-Sassandra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arrah',6.673419,-3.969383,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Guéyo',5.688203,-6.071199,'Côte D’Ivoire','CI','Bas-Sassandra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Facobly',7.388301,-7.376439,'Côte D’Ivoire','CI','Montagnes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lakota',5.847523,-5.681997,'Côte D’Ivoire','CI','Gôh-Djiboua','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tiassalé',5.898394,-4.822926,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sinématiali',9.584103,-5.384757,'Côte D’Ivoire','CI','Savanes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sinfra',6.621026,-5.911442,'Côte D’Ivoire','CI','Sassandra-Marahoué','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Anyama',5.494622,-4.051831,'Côte D’Ivoire','CI','Abidjan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Duekoué',6.74202,-7.349183,'Côte D’Ivoire','CI','Montagnes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ouangolodougou',9.96837,-5.148818,'Côte D’Ivoire','CI','Savanes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bingerville',5.355809,-3.885371,'Côte D’Ivoire','CI','Abidjan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prikro',7.647048,-3.996256,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agnibilékrou',7.131132,-3.204147,'Côte D’Ivoire','CI','Comoé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vavoua',7.381944,-6.477778,'Côte D’Ivoire','CI','Sassandra-Marahoué','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Béttié',6.075676,-3.408456,'Côte D’Ivoire','CI','Comoé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fresco',5.082265,-5.569379,'Côte D’Ivoire','CI','Bas-Sassandra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Samatiguila',9.819521,-7.560846,'Côte D’Ivoire','CI','Denguélé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Koro',8.555049,-7.463478,'Côte D’Ivoire','CI','Woroba','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Adiaké',5.286337,-3.304025,'Côte D’Ivoire','CI','Comoé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dikodougou',9.067573,-5.772225,'Côte D’Ivoire','CI','Savanes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Didiévi',7.12866,-4.898041,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Madinani',9.610832,-6.942153,'Côte D’Ivoire','CI','Denguélé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Taabo',6.199799,-5.108841,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sandégué',7.953756,-3.580124,'Côte D’Ivoire','CI','Zanzan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Djékanou',6.483892,-5.115527,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zuénoula',7.430272,-6.050541,'Côte D’Ivoire','CI','Sassandra-Marahoué','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('M’Bahiakro',7.457277,-4.339934,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Taï',5.873663,-7.455185,'Côte D’Ivoire','CI','Montagnes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Issia',6.492241,-6.585576,'Côte D’Ivoire','CI','Sassandra-Marahoué','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bloléquin',6.569129,-8.002533,'Côte D’Ivoire','CI','Montagnes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kouibly',7.255974,-7.235084,'Côte D’Ivoire','CI','Montagnes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agou',5.982888,-3.943933,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('M’Batto',6.471971,-4.357809,'Côte D’Ivoire','CI','Lacs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nassian',8.452746,-3.471522,'Côte D’Ivoire','CI','Zanzan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tengréla',10.48115,-6.406939,'Côte D’Ivoire','CI','Savanes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Boundiali',9.521667,-6.486944,'Côte D’Ivoire','CI','Savanes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('M’Bengué',10.002435,-5.900366,'Côte D’Ivoire','CI','Savanes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dabakala',8.363209,-4.428628,'Côte D’Ivoire','CI','Vallée du Bandama','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Akoupé',6.38423,-3.887589,'Côte D’Ivoire','CI','Lagunes','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maféré',5.415102,-3.030058,'Côte D’Ivoire','CI','Comoé','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Attiégouakro',6.77402,-5.114105,'Côte D’Ivoire','CI','Yamoussoukro','minor',NULL,NULL);
