CREATE TABLE IF NOT EXISTS next_destinations(
   city              VARCHAR(10) NOT NULL
  ,lat               NUMERIC(9,6) NOT NULL
  ,lng               NUMERIC(9,6) NOT NULL
  ,country           VARCHAR(10) NOT NULL
  ,iso2              VARCHAR(2) NOT NULL
  ,auser             VARCHAR(10) NOT NULL
  ,capital           VARCHAR(7)
  ,population        INTEGER 
  ,population_proper INTEGER 
);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Berlin',52.516667,13.4,'Germany','DE','Berlin','primary',3406000,3094014);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stuttgart',48.782343,9.180819,'Germany','DE','Baden-Württemberg','admin',2944700,606588);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Frankfurt',50.11552,8.684167,'Germany','DE','Hesse','minor',2895000,679664);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mannheim',49.496706,8.479547,'Germany','DE','Baden-Württemberg','minor',2362000,313174);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hamburg',53.575323,10.01534,'Germany','DE','Hamburg','admin',1757000,1739117);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Essen',51.45657,7.012282,'Germany','DE','North Rhine-Westphalia','minor',1742135,573468);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Duisburg',51.432469,6.765161,'Germany','DE','North Rhine-Westphalia','minor',1276757,488005);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Munich',48.15,11.583333,'Germany','DE','Bavaria','admin',1275000,1260391);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Düsseldorf',51.228304,6.793849,'Germany','DE','North Rhine-Westphalia','admin',1220000,592393);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cologne',50.933333,6.95,'Germany','DE','North Rhine-Westphalia',NULL,1004000,963395);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wuppertal',51.270268,7.167553,'Germany','DE','North Rhine-Westphalia','minor',776525,349470);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Saarbrücken',49.235396,6.981646,'Germany','DE','Saarland','admin',770001,175741);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marienberg',49.486021,11.086156,'Germany','DE','Bavaria',NULL,737304,499237);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bremen',53.073789,8.826754,'Germany','DE','Bremen','admin',724909,546501);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hannover',52.38497,9.737141,'Germany','DE','Lower Saxony','admin',722490,515140);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bonn',50.73438,7.095485,'Germany','DE','North Rhine-Westphalia','minor',680543,313125);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dresden',51.048562,13.745794,'Germany','DE','Saxony','admin',617515,486854);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wiesbaden',50.082582,8.249322,'Germany','DE','Hesse','admin',617126,272432);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dortmund',51.514942,7.465997,'Germany','DE','North Rhine-Westphalia','minor',588462,588462);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leipzig',51.34419,12.386504,'Germany','DE','Saxony','minor',542529,504971);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Heidelberg',49.404123,8.683733,'Germany','DE','Baden-Württemberg','minor',426590,143345);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karlsruhe',49.009365,8.40444,'Germany','DE','Baden-Württemberg','minor',377487,283799);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Augsburg',48.371538,10.898514,'Germany','DE','Bavaria','minor',358989,259196);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bielefeld',52.028332,8.542002,'Germany','DE','North Rhine-Westphalia','minor',331906,291573);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Koblenz',50.353573,7.578835,'Germany','DE','Rhineland-Palatinate','minor',312633,107319);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Altchemnitz',50.811536,12.912827,'Germany','DE','Saxony',NULL,302643,247220);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kassel',51.313782,9.484645,'Germany','DE','Hesse','minor',289924,194501);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Münster',51.961114,7.624239,'Germany','DE','North Rhine-Westphalia','minor',270184,237041);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kiel',54.312145,10.135526,'Germany','DE','Schleswig-Holstein','admin',269427,232758);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Freiburg',47.996861,7.84973,'Germany','DE','Baden-Württemberg','minor',254889,215966);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Braunschweig',52.265939,10.526726,'Germany','DE','Lower Saxony','minor',244715,235054);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fürth',49.48121,10.96762,'Germany','DE','Bavaria','minor',237844,112025);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lübeck',53.86687,10.688367,'Germany','DE','Schleswig-Holstein','minor',235390,212207);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Osnabrück',52.272642,8.049799,'Germany','DE','Lower Saxony','minor',231268,166462);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Magdeburg',52.127731,11.629163,'Germany','DE','Saxony-Anhalt','admin',229826,224931);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Potsdam',52.402247,13.057122,'Germany','DE','Brandenburg','admin',218095,145292);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Erfurt',50.978695,11.032831,'Germany','DE','Thuringia','admin',203254,175476);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rostock',54.086813,12.113453,'Germany','DE','Mecklenburg-Western Pomerania',NULL,203080,198293);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mainz',49.984188,8.279096,'Germany','DE','Rhineland-Palatinate','admin',184997,184997);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ulm',48.397053,9.968956,'Germany','DE','Baden-Württemberg','minor',172955,120451);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Würzburg',49.793912,9.951214,'Germany','DE','Bavaria','minor',168561,133731);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oldenburg',53.141178,8.214674,'Germany','DE','Lower Saxony','minor',167458,159218);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Regensburg',49.034512,12.119234,'Germany','DE','Bavaria','minor',164359,129151);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ingolstadt',48.765081,11.423725,'Germany','DE','Bavaria','minor',163325,120658);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Göttingen',51.539334,9.934057,'Germany','DE','Lower Saxony','minor',139419,122149);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bremerhaven',53.550209,8.576735,'Germany','DE','Bremen','minor',137751,117446);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cottbus',51.757691,14.328875,'Germany','DE','Brandenburg','minor',105067,84754);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jena',50.928782,11.589901,'Germany','DE','Thuringia','minor',104712,95171);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gera',50.875507,12.083296,'Germany','DE','Thuringia','minor',104659,103055);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Flensburg',54.78431,9.439611,'Germany','DE','Schleswig-Holstein','minor',97930,85838);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Schwerin',53.628373,11.409462,'Germany','DE','Mecklenburg-Western Pomerania','admin',96641,96641);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rosenheim',47.857316,12.119255,'Germany','DE','Bavaria','minor',92809,60167);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gießen',50.58727,8.675536,'Germany','DE','Hesse','minor',82358,74411);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stralsund',54.315823,13.088588,'Germany','DE','Mecklenburg-Western Pomerania','minor',61368,58976);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Coburg',50.259366,10.963843,'Germany','DE','Bavaria',NULL,61054,41901);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hofeck',50.330895,11.892585,'Germany','DE','Bavaria',NULL,56153,49239);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Emden',53.367454,7.207776,'Germany','DE','Lower Saxony','minor',51526,48046);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Detmold',51.943277,8.872182,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Meißen',51.15,13.483333,'Germany','DE','Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kitzingen',49.739731,10.150719,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dingolfing',48.62958,12.497606,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Heppenheim',49.641447,8.632063,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Torgau',51.56016,12.996166,'Germany','DE','Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hanau',50.134229,8.914176,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Husum',54.482518,9.059913,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Schwandorf',49.32534,12.109795,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bitburg',49.967937,6.527343,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cham',49.225651,12.655013,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Traunstein',47.868247,12.643347,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lüchow',52.968114,11.153968,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gifhorn',52.477743,10.551095,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Biberach',48.099942,9.786893,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Reichenhall',47.729467,12.878193,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Künzelsau',49.281802,9.683525,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Weißenburg',49.030564,10.972771,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Regen',48.971901,13.128243,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nuremberg',49.447778,11.068333,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aurich',53.469193,7.482319,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nordhorn',52.432784,7.068896,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aichach',48.461421,11.134257,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marburg',50.809044,8.770694,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Görlitz',51.166667,15.0,'Germany','DE','Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vechta',52.726324,8.285982,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trier',49.75979,6.636628,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pirmasens',49.204106,7.603486,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pirna',50.958054,13.938197,'Germany','DE','Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neustadt',49.350089,8.138863,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Beeskow',52.17291,14.245973,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Westerstede',53.256822,7.927372,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Verden',52.923425,9.234908,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Worms',49.632784,8.359164,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Düren',50.804337,6.492988,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Landsberg',48.047642,10.869584,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ludwigsburg',48.893886,9.195419,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Meiningen',50.570435,10.417231,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Siegen',50.874815,8.02431,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Deggendorf',48.840855,12.960676,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Peine',52.319277,10.2352,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Frankfurt (Oder)',52.344312,14.53498,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nienburg',52.646102,9.220856,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brake',53.326867,8.480492,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Memmingen',47.985359,10.182507,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kirchheimbolanden',49.662487,8.015131,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tauberbischofsheim',49.624722,9.662778,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Emmendingen',48.118466,7.848932,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Warendorf',51.95109,7.987557,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Segeberg',53.943131,10.302154,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rotenburg',53.111251,9.410819,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kronach',50.238777,11.33049,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Darmstadt',49.871674,8.650271,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mindelheim',48.045781,10.492223,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bergheim',50.954875,6.64094,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Donauwörth',48.694951,10.779154,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Korbach',51.274307,8.87196,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Herzberg',51.691501,13.232048,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hameln',52.109245,9.365097,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Suhl',50.609111,10.694009,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Friedberg',50.337391,8.755907,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hof',50.31622,11.918332,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neuburg',48.732181,11.18709,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Kissingen',50.202278,10.077836,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Viersen',51.254348,6.394414,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Birkenfeld',49.652447,7.166679,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Fallingbostel',52.866414,9.695579,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Halle',51.481473,11.967112,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bamberg',49.893174,10.88883,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fürstenfeldbruck',48.18662,11.27586,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neuss',51.198071,6.685037,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Kreuznach',49.841396,7.867127,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Heilbronn',49.13995,9.220541,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Ems',50.332737,7.717548,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Schwäbisch Hall',49.105833,9.734167,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Offenburg',48.473768,7.944946,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Saalfeld',50.648259,11.365363,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wolfenbüttel',52.164421,10.540946,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Altenkirchen',50.685945,7.64176,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pforzheim',48.884361,8.698923,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Günzburg',48.455989,10.276951,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Euskirchen',50.660569,6.787224,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chemnitz',50.835701,12.929217,'Germany','DE','Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rendsburg',54.306634,9.663126,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tirschenreuth',49.884428,12.337277,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Offenbach',50.100605,8.766466,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Uelzen',52.96572,10.561106,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zwickau',50.72724,12.488394,'Germany','DE','Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Schwabach',49.330468,11.023461,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gelsenkirchen',51.507502,7.122826,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mettmann',51.250404,6.975361,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ravensburg',47.781982,9.61062,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leer',53.233724,7.456431,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wittmund',53.576739,7.77839,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ingelheim',49.970782,8.058826,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Höxter',51.775814,9.378885,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oranienburg',52.755772,13.241967,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Erbach',49.661484,8.994017,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Freising',48.402654,11.747976,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Landau',49.198444,8.116921,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stendal',52.606895,11.858671,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Balingen',48.277142,8.852118,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Reutlingen',48.488779,9.213698,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eisenach',50.980701,10.315221,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tuttlingen',47.984644,8.817702,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neumünster',54.074773,9.981954,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neu-Ulm',48.400724,9.99028,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Köthen',51.751855,11.970928,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Schleiz',50.578663,11.810237,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Garmisch-Partenkirchen',47.498475,11.104356,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Baden-Baden',48.757631,8.242458,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bayreuth',49.947823,11.578935,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wunsiedel',50.043134,12.004459,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Osterode',51.726856,10.250894,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sankt Wendel',49.466326,7.168142,'Germany','DE','Saarland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lüdenscheid',51.219774,7.6273,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Plauen',50.497305,12.137823,'Germany','DE','Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Forst',51.735443,14.63971,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pfaffenhofen',48.53159,11.506415,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bochum',51.481651,7.216482,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Weimar',50.980301,11.32903,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wilhelmshaven',53.529977,8.112526,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Limburg',50.383597,8.050302,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Freyung',48.80952,13.547679,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Merseburg',51.35478,11.989233,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Halberstadt',51.895617,11.056224,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dessau-Roßlau',51.848277,12.229065,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Weiden',49.676824,12.156126,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Altenburg',50.987632,12.436838,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Heide',54.195794,9.098797,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Böblingen',48.684953,9.029552,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kulmbach',50.100684,11.450319,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Homberg',51.029943,9.402612,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Perleberg',53.07583,11.857394,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mülheim',51.431391,6.883666,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Northeim',51.706616,9.999975,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Salzwedel',52.854354,11.152503,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cuxhaven',53.866887,8.70168,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Plön',54.162408,10.423328,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mühlhausen',51.208959,10.452753,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kempten',47.732209,10.315858,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Güstrow',53.798852,12.178073,'Germany','DE','Mecklenburg-Western Pomerania','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lichtenfels',50.148152,11.069607,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Salzungen',50.813418,10.236103,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Weilheim',47.841468,11.15484,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jever',53.573676,7.898061,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arnstadt',50.840478,10.95198,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lüneburg',53.250897,10.414087,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Delmenhorst',53.051103,8.630908,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neubrandenburg',53.564144,13.275319,'Germany','DE','Mecklenburg-Western Pomerania','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Dürkheim',49.461803,8.172358,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Greiz',50.657785,12.199182,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Altötting',48.225329,12.676646,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Erding',48.30662,11.907496,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lübben',51.938144,13.888258,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Holzminden',51.82901,9.45902,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wetzlar',50.561091,8.50495,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Soest',51.571657,8.108861,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mosbach',49.353573,9.151062,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Heilbad Heiligenstadt',51.378187,10.137445,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neustadt',49.732873,12.17773,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Calw',48.716828,8.737612,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kleve',51.788258,6.138646,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Annaberg-Buchholz',50.579985,13.003333,'Germany','DE','Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wismar',53.893145,11.452859,'Germany','DE','Mecklenburg-Western Pomerania','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aachen',50.774122,6.084726,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tübingen',48.533333,9.05,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Freiberg',50.910894,13.338808,'Germany','DE','Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mönchengladbach',51.185386,6.441723,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nordhausen',51.501799,10.795695,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krefeld',51.339208,6.586152,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stadthagen',52.324242,9.205315,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hildesheim',52.154122,9.952068,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Celle',52.61909,10.092232,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eberswalde',52.835127,13.82307,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Recklinghausen',51.61379,7.197381,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eisenberg',50.968602,11.902075,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kaufbeuren',47.882382,10.621923,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sömmerda',51.159143,11.115239,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Remscheid',51.179829,7.192496,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Greifswald',54.093107,13.387857,'Germany','DE','Mecklenburg-Western Pomerania','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rastatt',48.858512,8.209645,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Naumburg',51.149871,11.809792,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lauf',49.51386,11.282474,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Amberg',49.442872,11.862672,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ratzeburg',53.694698,10.790845,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Homburg',50.229964,8.613056,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neustadt',49.579531,10.611257,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Herne',51.538797,7.225716,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sangerhausen',51.472209,11.295333,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Forchheim',49.72376,11.068238,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eutin',54.140541,10.607507,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Oldesloe',53.809544,10.37997,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kelheim',48.921761,11.845459,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Neustadt',50.324586,10.198731,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Helmstedt',52.230039,11.008984,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Heinsberg',51.063583,6.0998,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zweibrücken',49.246864,7.369766,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hagen',51.360811,7.471679,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Montabaur',50.435882,7.823203,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Haßfurt',50.03521,10.515604,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pinneberg',53.667324,9.789362,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Apolda',51.026239,11.51638,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Schwalbach',50.141956,8.069639,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marktoberdorf',47.779637,10.617132,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Winsen',53.357528,10.21282,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wesel',51.666897,6.620367,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Landshut',48.529612,12.161791,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alzey',49.746574,8.115128,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Homburg',49.326366,7.33867,'Germany','DE','Saarland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Passau',48.574308,13.464016,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cloppenburg',52.847538,8.045,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Miesbach',47.791218,11.833358,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gotha',50.950945,10.705764,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Schwelm',51.286348,7.293884,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kusel',49.537724,7.404717,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Meschede',51.350202,8.283325,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Steinfurt',52.135198,7.353441,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aschaffenburg',49.977035,9.15214,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Paderborn',51.718127,8.757493,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karlstadt',49.960341,9.772389,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Waiblingen',48.831538,9.315456,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Villingen-Schwenningen',48.062262,8.49358,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rottweil',48.168228,8.618248,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Göppingen',48.703582,9.656463,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eichstätt',48.888543,11.196753,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Freudenstadt',48.466951,8.41371,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Schleswig',54.521561,9.558598,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Erlangen',49.595606,10.994974,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Olpe',51.02899,7.851393,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lörrach',47.616288,7.664842,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ansbach',49.304808,10.593098,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wittlich',49.985958,6.89308,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neuruppin',52.925588,12.804559,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sonneberg',50.3592,11.174631,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bottrop',51.523918,6.928499,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ludwigshafen',49.481206,8.446414,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Borken',51.843823,6.857743,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Starnberg',48.0,11.35,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gummersbach',51.026079,7.564731,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lauterbach',50.635582,9.397773,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Herford',52.114569,8.67343,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rathenow',52.609013,12.346825,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Solingen',51.173433,7.084502,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Speyer',49.320833,8.431111,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Siegburg',50.800194,7.207693,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Burg',52.271784,11.851402,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leverkusen',51.030299,6.984316,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Unna',51.537945,7.689687,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Coesfeld',51.943489,7.168094,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cochem',50.145108,7.163793,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eschwege',51.183859,10.053294,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Hersfeld',50.87197,9.708908,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Neuenahr-Ahrweiler',50.543224,7.111305,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sondershausen',51.369733,10.87011,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dachau',48.25838,11.449149,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Meppen',52.69085,7.292763,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wolfsburg',52.424516,10.781499,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brandenburg',52.410928,12.551172,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sigmaringen',48.088291,9.230327,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sonthofen',47.518213,10.282619,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Itzehoe',53.92516,9.517306,'Germany','DE','Schleswig-Holstein','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bergisch Gladbach',50.985596,7.132985,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dillingen',48.581529,10.495275,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Saarlouis',49.313663,6.751539,'Germany','DE','Saarland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Groß-Gerau',49.921394,8.48255,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oberhausen',51.473111,6.880739,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Goslar',51.917204,10.434446,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neustadt',49.565583,8.843695,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Germersheim',49.223056,8.363889,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hofheim',50.090194,8.449297,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ebersberg',48.077878,11.964944,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prenzlau',53.316246,13.862611,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bad Tölz',47.760761,11.56301,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Parchim',53.42718,11.849164,'Germany','DE','Mecklenburg-Western Pomerania','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Luckenwalde',52.090293,13.167717,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bernburg',51.794638,11.740096,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Osterholz-Scharmbeck',53.226979,8.79528,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stade',53.593369,9.476292,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neumarkt',49.281558,11.457205,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Salzgitter',52.083333,10.333333,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bautzen',51.18035,14.434941,'Germany','DE','Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hildburghausen',50.426678,10.72889,'Germany','DE','Thuringia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Heidenheim',48.680587,10.152483,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wittenberg',51.86747,12.6377,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kaiserslautern',49.442996,7.771614,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Miltenberg',49.704515,9.267253,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Coburg',50.261359,10.963256,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fulda',50.554729,9.683439,'Germany','DE','Hesse','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Senftenberg',51.525173,14.001635,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mühldorf',48.246695,12.521552,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Merzig',49.443313,6.638738,'Germany','DE','Saarland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Seelow',52.533373,14.380005,'Germany','DE','Brandenburg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Minden',52.289532,8.914552,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Waldshut-Tiengen',47.622491,8.199311,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neunkirchen',49.344493,7.180446,'Germany','DE','Saarland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neuwied',50.433601,7.470566,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Daun',50.197155,6.829418,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Esslingen',48.7374,9.316551,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Simmern',49.98198,7.523507,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gütersloh',51.906931,8.378535,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Diepholz',52.607826,8.370051,'Germany','DE','Lower Saxony','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Frankenthal',49.534143,8.353574,'Germany','DE','Rhineland-Palatinate','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Straubing',48.881259,12.573853,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pfarrkirchen',48.43233,12.938694,'Germany','DE','Bavaria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hamm',51.673991,7.804448,'Germany','DE','North Rhine-Westphalia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Haldensleben',52.286851,11.413255,'Germany','DE','Saxony-Anhalt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aalen',48.834439,10.091336,'Germany','DE','Baden-Württemberg','minor',NULL,NULL);
