INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Athens',37.983333,23.733333,'Greece','GR','Attikí','primary',3242000,729137);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Thessaloníki',40.643615,22.930864,'Greece','GR','Kentrikí Makedonía','admin',828000,354290);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Piraeus',37.961389,23.638889,'Greece','GR','Attikí','minor',466065,175697);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pátra',38.244444,21.734444,'Greece','GR','Dytikí Elláda','admin',163360,155799);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Irákleio',35.338082,25.133029,'Greece','GR','Kríti','admin',137154,131654);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lárisa',39.636889,22.417611,'Greece','GR','Thessalía','admin',128758,111487);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Áno Vólos',39.379361,22.981806,'Greece','GR','Thessalía',NULL,110632,84425);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ioánnina',39.664861,20.851889,'Greece','GR','Ípeiros','admin',86304,64012);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chaniá',35.511236,24.02921,'Greece','GR','Kríti','minor',78728,54565);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agrínio',38.621889,21.409778,'Greece','GR','Dytikí Elláda','minor',75233,43525);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chalkída',38.461451,23.602631,'Greece','GR','Stereá Elláda','minor',71842,54558);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalámi',37.062286,22.070569,'Greece','GR','Peloponnísos',NULL,71823,51108);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kavála',40.939586,24.406868,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',59240,52950);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ródos',36.435564,28.221985,'Greece','GR','Notío Aigaío','minor',56969,56128);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sérres',41.084991,23.54757,'Greece','GR','Kentrikí Makedonía','minor',55886,45935);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kateríni',40.269557,22.506078,'Greece','GR','Kentrikí Makedonía','minor',53293,48408);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alexandroúpoli',40.849949,25.876435,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',52979,44444);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Xánthi',41.134876,24.887998,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',50570,48221);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lamía',38.9,22.433333,'Greece','GR','Stereá Elláda','admin',47246,47246);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Komotiní',41.119174,25.40535,'Greece','GR','Anatolikí Makedonía kai Thráki','admin',45631,45631);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kérkyra',39.620694,19.91975,'Greece','GR','Ionía Nísia','admin',38517,27003);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mytilíni',39.11,26.554722,'Greece','GR','Voreío Aigaío','admin',29328,28322);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trípoli',37.508889,22.379444,'Greece','GR','Peloponnísos','admin',28970,26561);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chíos',38.368621,26.132356,'Greece','GR','Voreío Aigaío','minor',26891,23953);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pýrgos',37.672139,21.439306,'Greece','GR','Dytikí Elláda','minor',22399,22223);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kos',36.892607,27.287574,'Greece','GR','Notío Aigaío','minor',19244,18691);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Spárti',37.074459,22.430091,'Greece','GR','Peloponnísos','minor',16187,15497);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ermoúpoli',37.45,24.933333,'Greece','GR','Notío Aigaío','admin',12260,12260);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Siteía',35.208507,26.103024,'Greece','GR','Kríti','minor',8833,8707);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Polýgyros',40.37704,23.441354,'Greece','GR','Kentrikí Makedonía','minor',5258,5258);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Megalópoli',37.401421,22.13689,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cholargós',38.00095,23.80079,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Náousa',40.630001,22.068374,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ágios Nikólaos',35.191064,25.715244,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agía Kyriakí',39.522639,20.883583,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Póros',37.500076,23.454955,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Palaió Fáliro',37.930198,23.702602,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Palaióchora',35.231328,23.681271,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Melíssia',38.051158,23.836204,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agía Marína',37.154351,26.855903,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Íos',36.723273,25.28246,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Níkiti',40.229439,23.67149,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ílion',38.032332,23.702161,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kastrí',34.83453,24.086424,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kárystos',38.016833,24.421111,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pezá',35.21806,25.192926,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalamáta',37.035586,22.112982,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Itháki',38.362583,20.721833,'Greece','GR','Ionía Nísia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mandráki',36.61038,27.132234,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Asprópyrgos',38.061713,23.589444,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Geráni',35.516772,23.878027,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Paranésti',41.266801,24.501991,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kálymnos',36.95258,26.980644,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kyparissía',37.250733,21.669551,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Výronas',37.959554,23.752897,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pérama',35.369525,24.703879,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pérama',37.966223,23.573917,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zográfos',37.975744,23.769113,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mílos',36.743605,24.422496,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Thérmi',40.547953,23.020184,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Áno Kalentíni',39.251528,21.167944,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alíartos',38.372662,23.101288,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Asklipieío',37.5975,23.074736,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Igoumenítsa',39.503417,20.267278,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sofádes',39.334365,22.097337,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kastélli',35.208387,25.338395,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Íasmos',41.127895,25.184382,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Spáta',37.962471,23.915008,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Árgos Orestikó',40.452491,21.259247,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Argostóli',38.172889,20.490278,'Greece','GR','Ionía Nísia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lefkáda',38.830361,20.704417,'Greece','GR','Ionía Nísia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Néa Smýrni',37.945391,23.714586,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mégara',37.995758,23.344661,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Atalánti',38.653951,22.997011,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alexándreia',40.627594,22.444484,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dáfni',37.950051,23.731164,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Astakós',38.537498,21.084073,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tzermiádo',35.199062,25.48892,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neméa',37.819764,22.662855,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kilkís',40.99302,22.874331,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalávryta',38.031944,22.110833,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ierápetra',35.010563,25.739502,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ierissós',40.397723,23.877716,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Orestiáda',41.506043,26.529641,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kaména Voúrla',38.780599,22.788433,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skýdra',40.767621,22.156474,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Árgos',37.635035,22.728503,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Peristéri',38.009396,23.693942,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aigínio',40.499666,22.542147,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maroúsi',38.053661,23.807692,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Péta',39.167673,21.035102,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sykiés',40.647372,22.956349,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Néa Zíchni',41.031224,23.828941,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Giannitsá',40.792367,22.414839,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mouzáki',39.428778,21.662889,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Velestíno',39.382081,22.745136,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pýlos',36.912844,21.696644,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Káto Achaḯa',38.142028,21.550736,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vrilíssia',38.035407,23.831943,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Galatás',37.496076,23.448066,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kónitsa',40.046135,20.750396,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chalandrítsa',38.106616,21.783201,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Deskáti',39.925272,21.810152,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vrýses',35.454507,23.6004,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Síkinos',36.696522,25.119876,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kifisiá',38.076703,23.820776,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Salamína',37.966546,23.491851,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Spétses',37.263875,23.155469,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Páros',37.084355,25.149176,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skiáthos',39.165333,23.487306,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fillýra',41.121566,25.632418,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Amýntaio',40.69033,21.679623,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alivéri',38.410028,24.03825,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sidirókastro',41.236068,23.39248,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Néa Ionía',38.04142,23.752898,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ágios Kírykos',37.612872,26.291092,'Greece','GR','Voreío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sápes',41.024762,25.696501,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rodolívos',40.921054,23.974641,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Polýkastro',40.997539,22.570945,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Filippiáda',39.204333,20.881583,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Irákleio',38.053994,23.77449,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Irákleia',41.182276,23.282221,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Thebes',38.319927,23.319074,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marathónas',38.156533,23.959951,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gázi',35.32517,25.066222,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sérifos',37.15,24.5,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kórinthos',37.938465,22.927911,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Litóchoro',40.098648,22.505356,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ampelókipoi',40.654038,22.91747,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Loutráki',37.975001,22.979761,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Álimos',37.914335,23.715868,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalamariá',40.578948,22.948475,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Amfilochía',38.862365,21.166047,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mándra',38.0747,23.496944,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zákynthos',37.780221,20.895551,'Greece','GR','Ionía Nísia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sámos',37.757437,26.976157,'Greece','GR','Voreío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Náfplio',37.568632,22.806912,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Folégandros',36.62803,24.919944,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Elassóna',39.892889,22.188778,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Acharnés',38.084728,23.73718,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Spercheiáda',38.908669,22.126835,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Métsovo',39.771247,21.183299,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ágios Efstrátios',39.539104,24.990445,'Greece','GR','Voreío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ándros',37.833333,24.933333,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Palamás',39.464439,22.08249,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Xylókastro',38.07712,22.633146,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Istiaía',38.954437,23.149986,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Megálo Chorió',36.455083,27.346892,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Amaliáda',37.797167,21.349528,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Psychikó',38.013057,23.772304,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tríkala',39.554926,21.768369,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Évlalo',40.981235,24.800107,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Évosmos',40.669775,22.90879,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leonídio',37.167704,22.858153,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Goúrnes',35.324771,25.277567,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dístomo',38.42889,22.666746,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Paianía',37.95432,23.854138,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lidoríki',38.527359,22.205085,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alónnisos',39.149361,23.845361,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Psará',38.541441,25.563014,'Greece','GR','Voreío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dráma',41.152831,24.147302,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prosotsáni',41.179377,23.971968,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skópelos',39.121667,23.727556,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chaïdári',38.007868,23.659713,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Antíparos',37.040429,25.08188,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Péfki',38.055583,23.79032,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kranídi',37.37963,23.159581,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Préveza',38.956167,20.7505,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Káto Nevrokópi',41.342114,23.868228,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zevgolatió',38.081529,22.619325,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Archaía Olympía',37.646917,21.625639,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Psachná',38.577536,23.643107,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Siátista',40.258261,21.552513,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Áno Sýros',37.45,24.933333,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ágioi Déka',35.058216,24.960236,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vólos',39.373027,22.942708,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Korydallós',37.981097,23.651351,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Néa Filadélfeia',38.041867,23.7415,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eleftheroúpoli',40.914913,24.254241,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kýthira',36.149229,22.987954,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Smínthi',41.228866,24.880445,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Áno Liósia',38.084017,23.702293,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rafína',38.023207,24.002594,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalývia Thorikoú',37.839079,23.927634,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chrysó',41.058377,23.651399,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gérakas',38.013336,23.855994,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Édessa',40.802596,22.047514,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Náfpaktos',38.393798,21.828368,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chóra Sfakíon',35.201807,24.139826,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kímolos',36.793743,24.573874,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ilioúpoli',37.930202,23.751406,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kerasochóri',39.0045,21.639028,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Náxos',37.102069,25.378035,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dimitsána',37.595672,22.039477,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nestório',40.413386,21.061162,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Metamórfosi',38.063904,23.761847,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moscháto',37.954043,23.681454,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kréstena',37.591528,21.617833,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prámanta',39.52198,21.098563,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Límni',38.765902,23.31946,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Meligalás',37.223725,21.96988,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Anógeia',35.290667,24.883421,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Paramythiá',39.465417,20.513028,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Peraía',40.499003,22.926167,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kaisarianí',37.968142,23.759457,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leipsoí',37.295857,26.769537,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fársala',39.296306,22.384472,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kéa',37.633333,24.35,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Anthiró',39.34725,21.458556,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aigáleo',37.992527,23.678064,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lagkadás',40.750484,23.065161,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eleoúsa',39.705861,20.79275,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Anáfi',36.350868,25.767118,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Argalastí',39.226139,23.217333,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Livadeiá',38.436158,22.87665,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kanaláki',39.233056,20.603139,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skýros',38.906011,24.56556,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Makrychóri',39.804194,22.492278,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ýdra',37.346946,23.465725,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Didymóteicho',41.350129,26.498022,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kastoriá',40.521648,21.263407,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Thásos',40.778353,24.709417,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karpenísi',38.912178,21.798362,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pýli',39.459606,21.622123,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zagorá',39.444417,23.101167,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Farkadóna',39.59133,22.068624,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kardítsa',39.364848,21.921912,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Frý',35.416178,26.9231,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aígina',37.747641,23.43211,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lechainá',37.937306,21.262139,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Erétria',38.394338,23.794968,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Elefsína',38.045194,23.543821,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kiáto',38.011807,22.749725,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gastoúni',37.850583,21.253389,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Káto Tithoréa',38.608621,22.712961,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ágioi Anárgyroi',38.032449,23.724739,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Spíli',35.216798,24.536112,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Amorgós',36.831809,25.898313,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agiá',39.71875,22.755528,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agía Foteiní',35.254212,24.634203,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Thérmo',38.572861,21.666167,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oropós',38.301722,23.754167,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Koropí',37.900859,23.872306,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oinoússes',38.515768,26.222474,'Greece','GR','Voreío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Morfovoúni',39.352528,21.750435,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Panórama',40.585316,23.028138,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oraiókastro',40.729566,22.916548,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kozáni',40.300685,21.788959,'Greece','GR','Dytikí Makedonía','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Elafónisos',36.509021,22.978682,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grevená',40.084021,21.429096,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skála',36.852386,22.666515,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Árta',39.160139,20.985611,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kassándreia',40.048701,23.413064,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalampáka',39.706184,21.626047,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalampáki',41.051399,24.1871,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sými',36.614478,27.836224,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Orchomenós',38.492114,22.978681,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kárpathos',35.506479,27.21301,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Schimatári',38.346528,23.581229,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chrysoúpoli',40.986661,24.699648,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Voúla',37.845901,23.762577,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Filiátes',39.600056,20.309167,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sérvia',40.184385,22.000485,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tínos',37.537531,25.163434,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Týrnavos',39.740333,22.286889,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Koufália',40.779878,22.57781,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Samothráki',40.474338,25.525137,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Asprángeloi',39.822639,20.727639,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Argyroúpoli',37.906165,23.750712,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agía Paraskeví',38.013637,23.825535,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aígio',38.249322,22.084838,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ágios Dimítrios',37.934177,23.729145,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Galátsi',38.013005,23.753293,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Astypálaia',36.547904,26.351977,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ámfissa',38.52813,22.377131,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gýtheio',36.762071,22.563789,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Megísti',36.148344,29.591655,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Geniséa',41.060476,24.961796,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Markópoulo',37.883333,23.933333,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stavroúpoli',40.669203,22.931033,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zacháro',37.483583,21.6495,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agía Varvára',37.988313,23.660925,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Megálo Chorió',37.457757,26.972355,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Véroia',40.524368,22.202419,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moláoi',36.804176,22.853346,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mýkonos',37.45,25.333333,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Apollonía',36.974373,24.724006,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Réthymno',35.366868,24.474872,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chalándri',38.021559,23.798919,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gáios',39.196083,20.185778,'Greece','GR','Ionía Nísia','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mesolóngi',38.371378,21.431509,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Flórina',40.78071,21.409274,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stylída',38.914429,22.613769,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Laimós',40.835876,21.140355,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moíres',35.051684,24.875012,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kallithéa',37.954953,23.701001,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Souflí',41.194824,26.300171,'Greece','GR','Anatolikí Makedonía kai Thráki','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Messíni',37.051106,22.008423,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Firá',36.420718,25.43219,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pátmos',37.308646,26.547423,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lávrio',37.714389,24.053278,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalpáki',39.887056,20.624944,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Domokós',39.127459,22.303834,'Greece','GR','Stereá Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stavrós',40.663545,23.699785,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agkístri',37.709586,23.347153,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vourgaréli',39.37175,21.183306,'Greece','GR','Ípeiros','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Keratsíni',37.964318,23.619906,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Foúrnoi',37.576824,26.481504,'Greece','GR','Voreío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kýthnos',37.416667,24.433333,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mýrina',39.879478,25.065005,'Greece','GR','Voreío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Níkaia',39.564944,22.466,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ágios Stéfanos',38.140834,23.859089,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Néa Moudaniá',40.241123,23.286565,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kardamýli',36.88769,22.232668,'Greece','GR','Peloponnísos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Petroúpoli',38.039568,23.681172,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aridaía',40.973004,22.060999,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vónitsa',38.916611,20.890417,'Greece','GR','Dytikí Elláda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Síndos',40.669752,22.806046,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kíssamos',35.494289,23.652784,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Almyrós',39.181541,22.758519,'Greece','GR','Thessalía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chálki',36.222649,27.611277,'Greece','GR','Notío Aigaío','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ptolemaḯda',40.512124,21.678029,'Greece','GR','Dytikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Níkaia',37.973675,23.640226,'Greece','GR','Attikí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nigríta',40.907565,23.500116,'Greece','GR','Kentrikí Makedonía','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Áno Viánnos',35.053924,25.409959,'Greece','GR','Kríti','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Glyfáda',37.863716,23.754249,'Greece','GR','Attikí','minor',NULL,NULL);
