INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Guatemala',14.633426,-90.516722,'Guatemala','GT','Guatemala','minor',1024000,994938);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Quetzaltenango',14.834722,-91.518056,'Guatemala','GT','Quetzaltenango','admin',575263,224703);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Luis',16.198889,-89.440278,'Guatemala','GT','Petén','minor',132470,6776);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Escuintla',14.305,-90.785,'Guatemala','GT','Escuintla','admin',107638,103165);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Huehuetenango',15.319722,-91.470833,'Guatemala','GT','Huehuetenango','admin',85992,79426);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chimaltenango',14.661111,-90.819444,'Guatemala','GT','Chimaltenango','admin',82370,82370);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Totonicapán',14.911667,-91.361111,'Guatemala','GT','Totonicapán','admin',69734,69734);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cobán',15.470833,-90.370833,'Guatemala','GT','Alta Verapaz','admin',65194,53375);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mazatenango',14.534167,-91.503333,'Guatemala','GT','Suchitepéquez','admin',64652,44132);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Puerto Barrios',15.727778,-88.594444,'Guatemala','GT','Izabal','admin',56605,53150);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jutiapa',14.291667,-89.895833,'Guatemala','GT','Jutiapa','admin',50681,34332);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jalapa',14.634722,-89.988889,'Guatemala','GT','Jalapa','admin',45834,45834);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sololá',14.772222,-91.183333,'Guatemala','GT','Sololá','admin',45373,45373);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chiquimula',14.8,-89.545833,'Guatemala','GT','Chiquimula','admin',41521,41521);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Salamá',15.102778,-90.318056,'Guatemala','GT','Baja Verapaz','admin',40000,40000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Antigua Guatemala',14.561111,-90.734444,'Guatemala','GT','Sacatepéquez','admin',39368,39368);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Flores',16.921667,-89.895278,'Guatemala','GT','Petén','admin',38035,20464);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Retalhuleu',14.536111,-91.677778,'Guatemala','GT','Retalhuleu','admin',36656,36656);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zacapa',14.972222,-89.530556,'Guatemala','GT','Zacapa','admin',36088,36088);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Marcos',14.963889,-91.794444,'Guatemala','GT','San Marcos','admin',25088,25088);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Cruz del Quiché',15.030556,-91.148889,'Guatemala','GT','Quiché','admin',23618,23618);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José',13.916667,-90.816666,'Guatemala','GT','Escuintla','minor',18655,9841);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cuilapa',14.276389,-90.298889,'Guatemala','GT','Santa Rosa','admin',16484,16484);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lívingston',15.833333,-88.75,'Guatemala','GT','Izabal','minor',14350,10255);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('La Libertad',16.788497,-90.116978,'Guatemala','GT','Petén','minor',8646,8523);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Quezaltepeque',14.633333,-89.45,'Guatemala','GT','Chiquimula','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mixco',14.633333,-90.606389,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Huité',14.933333,-89.716667,'Guatemala','GT','Zacapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Huitán',15.049201,-91.639439,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Magdalena Milpas Altas',14.545278,-90.675278,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tecpán Guatemala',14.766944,-90.994167,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tectitán',15.333333,-92.033333,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Jorge',14.933333,-89.583333,'Guatemala','GT','Zacapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Concepción Las Minas',14.516667,-89.45,'Guatemala','GT','Chiquimula','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Sebastián Huehuetenango',15.387681,-91.615299,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lanquín',15.566667,-89.966667,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Rodeo',14.916667,-91.966667,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José Chacayá',14.766667,-91.216667,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Juan Ostuncalco',14.873285,-91.689703,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zunilito',14.616667,-91.516667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zunil',14.783333,-91.483333,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Andrés Villa Seca',14.566667,-91.583333,'Guatemala','GT','Retalhuleu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Andrés Semetabaj',14.75,-91.133333,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Andrés Sajcabajá',15.216667,-90.916667,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Andrés Itzapa',14.62,-90.844167,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ixtahuacán',15.416667,-91.766667,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Patulul',14.416667,-91.166667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Asintal',14.6,-91.733333,'Guatemala','GT','Retalhuleu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Esquipulas Palo Gordo',14.933333,-91.816667,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Los Amates',15.266667,-89.1,'Guatemala','GT','Izabal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Bernardino',14.533333,-91.45,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Usumatlán',14.95,-89.783333,'Guatemala','GT','Zacapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Chal',16.666667,-89.633333,'Guatemala','GT','Petén','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Poptún',16.331111,-89.416944,'Guatemala','GT','Petén','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sansare',14.747222,-90.1125,'Guatemala','GT','El Progreso','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Casillas',14.422222,-90.244167,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José',16.983333,-89.9,'Guatemala','GT','Petén','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Agustín Acasaguastlán',14.95,-89.966667,'Guatemala','GT','El Progreso','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jocotán',14.816667,-89.383333,'Guatemala','GT','Chiquimula','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chiquimulilla',14.085833,-90.376667,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Ana',16.8,-89.833333,'Guatemala','GT','Petén','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Rafael Pie de La Cuesta',14.933333,-91.916667,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ciudad Vieja',14.526389,-90.759722,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Coatepeque',14.7,-91.866667,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jerez',14.1,-89.75,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Taxisco',14.070833,-90.463056,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José La Máquina',14.301781,-91.567068,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pajapita',14.72152,-92.035211,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ostuncalco',14.866667,-91.616667,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Unión',15.920513,-91.77621,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Almolonga',14.816667,-91.5,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alotenango',14.480278,-90.8075,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Samayac',14.583333,-91.466667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gualán',15.133333,-89.366667,'Guatemala','GT','Zacapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Guanagazapa',14.225278,-90.643333,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Parramos',14.607778,-90.803056,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Chol',14.964167,-90.480556,'Guatemala','GT','Baja Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sibilia',15.0,-91.616667,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sibinal',15.149629,-92.048917,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Francisco La Unión',14.916667,-91.533333,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Francisco El Alto',14.95,-91.45,'Guatemala','GT','Totonicapán','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José Poaquil',14.819722,-90.906389,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José Pinula',14.546111,-90.411389,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Yupiltepeque',14.2,-89.783333,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Miguel Acatán',15.7,-91.616667,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José Ojetenam',15.216667,-91.966667,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Juan Chamelco',15.433333,-90.333333,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ciudad Melchor de Mencos',17.068611,-89.152222,'Guatemala','GT','Petén','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Yepocapa',14.504167,-90.956944,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fray Bartolomé de Las Casas',15.815155,-89.889314,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Esquipulas',14.566667,-89.35,'Guatemala','GT','Chiquimula','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Guazacapán',14.074167,-90.416667,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Génova',14.616667,-91.833333,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Colomba',14.716667,-91.733333,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tamahú',15.333333,-90.166667,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Vicente Pacaya',14.416111,-90.639167,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Miguel Ixtahuacán',15.272465,-91.74785,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Quesada',14.270278,-90.040278,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Catarina',14.851525,-92.076473,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('La Democracia',15.625444,-91.8867,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('La Democracia',14.230833,-90.947222,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Bárbara',15.316167,-91.632792,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malacatán',14.910654,-92.057947,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa María Ixhuatán',14.19,-90.274722,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa María Visitación',14.716667,-91.316667,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Olopa',14.683333,-89.35,'Guatemala','GT','Chiquimula','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Morazán',14.932778,-90.143056,'Guatemala','GT','El Progreso','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pueblo Nuevo',14.65,-91.533333,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Cristóbal Acasaguastlán',14.916667,-89.883333,'Guatemala','GT','El Progreso','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Cristóbal Cucho',14.9,-91.783333,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tucurú',15.3,-90.066667,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aguacatán',15.343056,-91.311667,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Martín Zapotitlán',14.6,-91.6,'Guatemala','GT','Retalhuleu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Mateo',14.866667,-91.583333,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Martín Jilotepeque',14.787778,-90.7925,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Catarina Pinula',14.568889,-90.495278,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Juan Cotzal',15.434167,-91.034167,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Tumbador',14.866667,-91.933333,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Palestina de los Altos',14.933333,-91.7,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Palín',14.405556,-90.698333,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nebaj',15.405833,-91.146111,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Carlos Sija',14.983333,-91.55,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Guastatoya',14.854167,-90.069444,'Guatemala','GT','El Progreso','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Progreso',14.35,-89.85,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santo Domingo Suchitepéquez',14.466667,-91.483333,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Andrés Xecul',14.9,-91.483333,'Guatemala','GT','Totonicapán','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Atescatempa',14.174444,-89.7425,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zapotitlán',14.133333,-89.833333,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Concepción Chiquirichapa',14.85,-91.616667,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sacapulas',15.286667,-91.087222,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Juan La Laguna',14.7,-91.283333,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Juan Ixcoy',15.599722,-91.445278,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tajumulco',15.083333,-91.883333,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fraijanes',14.465278,-90.440833,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('La Gomera',14.083333,-91.05,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Petapa',14.502778,-90.551667,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Lucía La Reforma',15.128333,-91.235556,'Guatemala','GT','Totonicapán','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Lucía Milpas Altas',14.575833,-90.678611,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Lucía Cotzumalguapa',14.333333,-91.016667,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santo Tomás La Unión',14.633333,-91.383333,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sanarate',14.795,-90.192222,'Guatemala','GT','El Progreso','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Cruz Balanyá',14.687222,-90.915,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Canillá',15.166667,-90.85,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Champerico',14.3,-91.916667,'Guatemala','GT','Retalhuleu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Joyabaj',14.995,-90.806111,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Comalapa',14.741111,-90.8875,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Antonio Suchitepéquez',14.533333,-91.416667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Antonio Sacatepéquez',14.966667,-91.733333,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Manuel Chaparrón',14.516667,-89.766667,'Guatemala','GT','Jalapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Senahú',15.4,-89.833333,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Río Bravo',14.4,-91.316667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Comapa',14.116667,-89.916667,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Gaspar Ixchil',15.387963,-91.725644,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Benito',16.916667,-89.9,'Guatemala','GT','Petén','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Rafael La Independencia',15.716667,-91.533333,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Antonio Aguas Calientes',14.539722,-90.769444,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Juan Tecuaco',14.082222,-90.261111,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cuilco',15.4,-91.966667,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chinique',15.044722,-91.025833,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chicamán',15.4,-90.766667,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Río Hondo',15.066667,-89.583333,'Guatemala','GT','Zacapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Quetzal',14.766667,-91.816667,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Antonio Huista',15.650098,-91.771628,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pedro La Laguna',14.683333,-91.266667,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Concepción Tutuapa',15.283333,-91.783333,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Lucas Sacatepéquez',14.609722,-90.656944,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mataquescuintla',14.529167,-90.184167,'Guatemala','GT','Jalapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Masagua',14.203056,-90.848056,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chiantla',15.354722,-91.458333,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tejutla',15.116667,-91.8,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Teculután',14.983333,-89.716667,'Guatemala','GT','Zacapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Jerónimo',15.05,-90.2,'Guatemala','GT','Baja Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cajolá',14.916667,-91.616667,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Panajachel',14.733333,-91.15,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Comitancillo',15.089367,-91.749706,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Barillas',15.803611,-91.315833,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Palmar',14.65,-91.583333,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pueblo Nuevo Tiquisate',14.283333,-91.366667,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chuarrancho',14.821667,-90.508611,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Felipe',14.616667,-91.6,'Guatemala','GT','Retalhuleu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sayaxché',16.516667,-90.166667,'Guatemala','GT','Petén','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Patzún',14.683333,-91.016667,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Rosa de Lima',14.388056,-90.295556,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sumpango',14.646389,-90.733889,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pablo',14.931535,-92.003918,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pablo Jocopilas',14.583333,-91.45,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Todos Santos Cuchumatán',15.516667,-91.616667,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jocotenango',14.581944,-90.743611,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Olintepeque',14.883333,-91.516667,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Soloma',15.716667,-91.45,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Uspantán',15.383333,-90.833333,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cabañas',14.933333,-89.8,'Guatemala','GT','Zacapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Patzicía',14.631667,-90.926944,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cuyotenango',14.533333,-91.566667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Bartolomé Jocotenango',15.192778,-91.077222,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Bartolomé Milpas Altas',14.606111,-90.68,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Bartolo',15.084444,-91.455833,'Guatemala','GT','Totonicapán','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('La Reforma',14.8,-91.816667,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rabinal',15.1,-90.45,'Guatemala','GT','Baja Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Marcos La Laguna',14.716667,-91.266667,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pedro Sacatepéquez',14.684167,-90.644167,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pedro Necta',15.491423,-91.765505,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José Acatempa',14.265278,-90.126944,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Estor',15.533333,-89.35,'Guatemala','GT','Izabal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Andrés',16.966667,-89.916667,'Guatemala','GT','Petén','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Francisco',16.8,-89.933333,'Guatemala','GT','Petén','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nueva Concepción',14.2,-91.3,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cubulco',15.133333,-90.583333,'Guatemala','GT','Baja Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tacaná',15.239325,-92.067365,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Siquinalá',14.306111,-90.965,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Sebastián Coatán',15.733333,-91.566667,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Sebastián',14.566667,-91.65,'Guatemala','GT','Retalhuleu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ocós',14.509981,-92.192984,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Raimundo',14.764722,-90.595556,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ayutla',14.673833,-92.139937,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José La Arada',14.716667,-89.583333,'Guatemala','GT','Chiquimula','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Rafael Las Flores',14.481389,-90.173333,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Rafael Petzal',15.405032,-91.66526,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Salcajá',14.883333,-91.45,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chahal',15.75,-89.566667,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pasaco',13.977222,-90.206389,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Villa Canales',14.481389,-90.531667,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pochuta',14.55,-91.083333,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Playa Grande',15.933333,-90.733333,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Purulhá',15.266667,-90.2,'Guatemala','GT','Baja Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jacaltenango',15.666667,-91.733333,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dolores',16.514167,-89.415833,'Guatemala','GT','Petén','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chichicastenango',14.933333,-91.116667,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Antonio Ilotenango',15.054722,-91.229722,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nentón',15.800702,-91.75464,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Tejar',14.647778,-90.792778,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pedro Jocopilas',15.094444,-91.151389,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cahabón',15.566667,-89.816667,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chinautla',14.708333,-90.499444,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zacualpa',15.083333,-90.833333,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Jícaro',14.916667,-89.9,'Guatemala','GT','El Progreso','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Estanzuela',15.0,-89.566667,'Guatemala','GT','Zacapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Cristóbal Totonicapán',14.916667,-91.433333,'Guatemala','GT','Totonicapán','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Cristóbal Verapaz',15.383333,-90.4,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Diego',14.783333,-89.783333,'Guatemala','GT','Zacapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Concepción',14.783333,-91.15,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nueva Santa Rosa',14.381111,-90.276111,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Martín Sacatepéquez',14.816667,-91.65,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Miguel Dueñas',14.523889,-90.798333,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Miguel Chicaj',15.1,-90.4,'Guatemala','GT','Baja Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Juan Ermita',14.766667,-89.433333,'Guatemala','GT','Chiquimula','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('La Tinta',15.316667,-89.883333,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('El Adelanto',14.166667,-89.833333,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pachalun',14.924722,-90.662778,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Raxruhá',15.866667,-90.033333,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Flores Costa Cuca',14.65,-91.816667,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa María Chiquimula',15.030278,-91.329167,'Guatemala','GT','Totonicapán','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa María de Jesús',14.518333,-90.726667,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sipacapa',15.212457,-91.634163,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Guatemala City',14.621111,-90.526944,'Guatemala','GT','Guatemala','primary',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jalpatagua',14.141667,-90.008611,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Camotán',14.816667,-89.366667,'Guatemala','GT','Chiquimula','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nahualá',14.85,-91.316667,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nuevo Progreso',14.8,-91.916667,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nuevo San Carlos',14.6,-91.7,'Guatemala','GT','Retalhuleu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Miguel Panán',14.533333,-91.366667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Miguel Sigüilá',14.9,-91.616667,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Juan Atitán',15.428861,-91.623981,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Apolonia',14.791389,-90.970833,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Juan Bautista',14.416667,-91.183333,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Bárbara',14.433333,-91.233333,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malacatancito',15.216667,-91.516667,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Panzós',15.4,-89.666667,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Lucía Utatlán',14.766667,-91.266667,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Palencia',14.664722,-90.358611,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Carlos Alzatate',14.497778,-90.060278,'Guatemala','GT','Jalapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Ana Huista',15.680854,-91.820048,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ixchiguán',15.2,-91.883333,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ipala',14.616667,-89.616667,'Guatemala','GT','Chiquimula','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('La Unión',14.966667,-89.283333,'Guatemala','GT','Zacapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Mateo Ixtatán',15.831944,-91.478056,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Catarina Barahona',14.548889,-90.788333,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Catarina Ixtahuacán',14.8,-91.366667,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Catarina Mita',14.45,-89.75,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Catarina Palopó',14.716667,-91.133333,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Iztapa',13.933333,-90.7075,'Guatemala','GT','Escuintla','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santiago Sacatepéquez',14.635278,-90.676389,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tactic',15.333333,-90.3,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Luis Jilotepeque',14.65,-89.733333,'Guatemala','GT','Jalapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zaragoza',14.654444,-90.889444,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moyuta',14.038611,-90.080833,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cunén',15.3375,-91.026944,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Eulalia',15.733056,-91.456944,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santo Domingo Xenacoj',14.677778,-90.697778,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Asunción Mita',14.330833,-89.710833,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('La Esperanza',14.866667,-91.566667,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Juan Sacatepéquez',14.718889,-90.644167,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Clara La Laguna',14.716667,-91.3,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Antonio Palopó',14.7,-91.116667,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pastores',14.596667,-90.754722,'Guatemala','GT','Sacatepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Patzité',14.966667,-91.216667,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José El Ídolo',14.45,-91.416667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Río Blanco',15.038199,-91.684631,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Conguaco',14.044167,-90.031111,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San José del Golfo',14.762778,-90.376389,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Lorenzo',15.030868,-91.735344,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Lorenzo',14.483333,-91.516667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oratorio',14.228056,-90.175833,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Morales',15.483333,-88.816667,'Guatemala','GT','Izabal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chisec',15.816667,-90.283333,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Acatenango',14.551944,-90.942222,'Guatemala','GT','Chimaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Cruz Muluá',14.583333,-91.616667,'Guatemala','GT','Retalhuleu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Cruz La Laguna',14.75,-91.216667,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Cruz Verapaz',15.366667,-90.433333,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Cruz Naranjo',14.388056,-90.369722,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cabricán',15.074846,-91.648003,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Francisco Zapotitlán',14.583333,-91.516667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Gabriel',14.516667,-91.516667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chajul',15.485278,-91.034167,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cantel',14.816667,-91.45,'Guatemala','GT','Quetzaltenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santiago Chimaltenango',15.476582,-91.696555,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santiago Atitlán',14.633333,-91.233333,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Villa Nueva',14.526944,-90.5875,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pedro Sacatepéquez',14.966667,-91.766667,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pedro Pinula',14.666667,-89.85,'Guatemala','GT','Jalapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Lucas Tolimán',14.633333,-91.133333,'Guatemala','GT','Sololá','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Monjas',14.5,-89.866667,'Guatemala','GT','Jalapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Momostenango',15.043611,-91.408611,'Guatemala','GT','Totonicapán','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chiché',15.008611,-91.065,'Guatemala','GT','Quiché','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Amatitlán',14.4875,-90.615278,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Concepción',15.616667,-91.683333,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Barberena',14.309444,-90.361111,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pueblo Nuevo Viñas',14.225833,-90.474167,'Guatemala','GT','Santa Rosa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Antonio La Paz',14.749722,-90.286667,'Guatemala','GT','El Progreso','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Colotenango',15.405063,-91.714352,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pedro Carchá',15.483333,-90.266667,'Guatemala','GT','Alta Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pedro Ayampuc',14.786667,-90.451111,'Guatemala','GT','Guatemala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chicacao',14.533333,-91.316667,'Guatemala','GT','Suchitepéquez','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Agua Blanca',14.5,-89.65,'Guatemala','GT','Jutiapa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('La Libertad',15.514208,-91.869436,'Guatemala','GT','Huehuetenango','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Granados',14.913611,-90.522778,'Guatemala','GT','Baja Verapaz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('La Blanca',14.57889,-92.141367,'Guatemala','GT','San Marcos','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Pablo La Laguna',14.716667,-91.266667,'Guatemala','GT','Sololá','minor',NULL,NULL);
