INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dublin',53.333056,-6.248889,'Ireland','IE','Dublin','primary',1059000,968976);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cork',51.898611,-8.495833,'Ireland','IE','Cork','admin',188907,136797);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Limerick',52.664722,-8.623056,'Ireland','IE','Limerick','admin',90054,78078);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Galway',53.271944,-9.048889,'Ireland','IE','Galway','admin',75594,70686);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Waterford',52.258333,-7.111944,'Ireland','IE','Waterford','admin',49275,49275);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Drogheda',53.718889,-6.347778,'Ireland','IE','Louth',NULL,36533,33441);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tralee',52.266667,-9.716667,'Ireland','IE','Kerry','admin',26384,22941);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kilkenny',52.654167,-7.252222,'Ireland','IE','Kilkenny','admin',21589,21213);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sligo',54.266667,-8.483333,'Ireland','IE','Sligo','admin',20228,14200);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Killarney',52.05,-9.516667,'Ireland','IE','Kerry',NULL,11902,7300);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shannon',52.703889,-8.864167,'Ireland','IE','Clare',NULL,8781,7506);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Monaghan',54.25,-6.966667,'Ireland','IE','Monaghan',NULL,5937,5937);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ros Comáin',53.633333,-8.183333,'Ireland','IE','Roscommon','admin',4860,4860);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Donegal',54.65,-8.116667,'Ireland','IE','Donegal',NULL,2513,1945);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lifford',54.831944,-7.483611,'Ireland','IE','Donegal','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Carlow',52.840833,-6.926111,'Ireland','IE','Carlow','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mullingar',53.533333,-7.35,'Ireland','IE','Westmeath','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('An Cabhán',53.990833,-7.360556,'Ireland','IE','Cavan','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wicklow',52.975,-6.049444,'Ireland','IE','Wicklow','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dún Dealgan',54.0,-6.416667,'Ireland','IE','Louth','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Clonmel',52.355,-7.703889,'Ireland','IE','Tipperary','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Naas',53.215833,-6.666944,'Ireland','IE','Kildare','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ennis',52.843611,-8.986389,'Ireland','IE','Clare','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Port Laoise',53.032222,-7.3,'Ireland','IE','Laois','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Swords',53.459722,-6.218056,'Ireland','IE','Fingal','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tallaght',53.287778,-6.341111,'Ireland','IE','South Dublin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wexford',52.334167,-6.4575,'Ireland','IE','Wexford','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trim',53.555,-6.791667,'Ireland','IE','Meath','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tullamore',53.273889,-7.488889,'Ireland','IE','Offaly','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Castlebar',53.85,-9.3,'Ireland','IE','Mayo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nenagh',52.861944,-8.196667,'Ireland','IE','Tipperary','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dunleary',53.2925,-6.128611,'Ireland','IE','Dún Laoghaire-Rathdown','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Longford',53.733333,-7.8,'Ireland','IE','Longford','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Carrick on Shannon',53.946944,-8.09,'Ireland','IE','Leitrim','admin',NULL,NULL);
