INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tehran',35.705,51.4216,'Iran','IR','Tehrān','primary',7873000,7153309);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mashhad',36.315591,59.567964,'Iran','IR','Khorāsān-e Raẕavī','admin',2469000,2167253);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eşfahān',32.657218,51.677608,'Iran','IR','Eşfahān','admin',1628000,1517766);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karaj',35.832664,50.991545,'Iran','IR','Alborz','admin',1423000,1423000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tabrīz',38.08,46.2919,'Iran','IR','Āz̄arbāyjān-e Sharqī','admin',1413000,1196426);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shīrāz',29.610308,52.531135,'Iran','IR','Fārs','admin',1240000,1240000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ahvāz',31.312381,48.677175,'Iran','IR','Khūzestān','admin',996000,841145);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qom',34.6401,50.8764,'Iran','IR','Qom','admin',973000,893956);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kermānshāh',34.314167,47.065,'Iran','IR','Kermānshāh','admin',828313,828313);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zāhedān',29.4963,60.8629,'Iran','IR','Sīstān va Balūchestān','admin',598887,551980);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rasht',37.276108,49.58862,'Iran','IR','Gīlān','admin',594590,494885);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kermān',30.283209,57.07879,'Iran','IR','Kermān','admin',577514,535522);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Orūmīyeh',37.5553,45.0724,'Iran','IR','Āz̄arbāyjān-e Gharbī','admin',577307,577307);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hamadān',34.799216,48.514556,'Iran','IR','Hamadān','admin',528256,330);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arāk',34.091741,49.689164,'Iran','IR','Markazī','admin',503647,423251);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Yazd',31.897222,54.3675,'Iran','IR','Yazd','admin',477905,425942);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qazvīn',36.2797,50.0049,'Iran','IR','Qazvīn','admin',464551,333635);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar ‘Abbās',27.1865,56.2808,'Iran','IR','Hormozgān','admin',461499,367508);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khomeynī Shahr',32.685604,51.536093,'Iran','IR','Eşfahān','minor',437138,437138);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ārdsālem',38.2669,48.283,'Iran','IR','Ardabīl',NULL,414603,410753);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khorramābād',33.487778,48.355833,'Iran','IR','Lorestān','admin',375198,329825);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ābādān',30.3392,48.3043,'Iran','IR','Khūzestān','minor',370180,260078);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zanjān',36.676421,48.496282,'Iran','IR','Zanjān','admin',357471,352554);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sanandaj',35.314948,46.998831,'Iran','IR','Kordestān','admin',349176,314420);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bīrjand',32.866277,59.221139,'Iran','IR','Khorāsān-e Jonūbī','admin',324703,196982);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dezfūl',32.381577,48.40585,'Iran','IR','Khūzestān','minor',315482,315482);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gorgān',36.8427,54.443907,'Iran','IR','Golestān','admin',281023,244937);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sārī',36.563319,53.060087,'Iran','IR','Māzandarān','admin',271467,255396);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Borūjerd',33.8973,48.7516,'Iran','IR','Lorestān','minor',251958,251958);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kāshān',33.997284,51.441575,'Iran','IR','Eşfahān','minor',250000,248789);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zābol',31.0306,61.4949,'Iran','IR','Sīstān va Balūchestān','minor',233968,121989);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sabzevār',36.21412,57.677047,'Iran','IR','Khorāsān-e Raẕavī','minor',226183,205638);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nīshābūr',36.213288,58.795755,'Iran','IR','Khorāsān-e Raẕavī','minor',221700,220929);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Āmol',36.469612,52.350724,'Iran','IR','Māzandarān','minor',221650,199382);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bojnūrd',37.47473,57.329031,'Iran','IR','Khorāsān-e Shomālī','admin',208582,192041);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khvoy',38.5503,44.9521,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',202728,175370);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Varāmīn',35.3242,51.6457,'Iran','IR','Tehrān','minor',179603,164827);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malāyer',34.301579,48.821656,'Iran','IR','Hamadān','minor',176573,176573);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sāveh',35.0213,50.3566,'Iran','IR','Markazī','minor',175533,115236);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sīrjān',29.437045,55.680229,'Iran','IR','Kermān','minor',175000,167014);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar-e Būshehr',28.9684,50.8385,'Iran','IR','Būshehr','admin',169060,165377);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mahābād',36.7499,45.7229,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',162434,144423);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gonbad-e Kāvūs',37.250042,55.167208,'Iran','IR','Golestān','minor',159982,131416);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kāshmar',35.23831,58.465575,'Iran','IR','Khorāsān-e Raẕavī','minor',157135,96151);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Masjed Soleymān',31.9364,49.3039,'Iran','IR','Khūzestān','minor',153663,111510);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Īlām',33.6374,46.4227,'Iran','IR','Īlām','admin',152894,140940);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marāgheh',37.392063,46.239093,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',151385,151385);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qūchān',37.105997,58.509547,'Iran','IR','Khorāsān-e Raẕavī','minor',145531,111752);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shāhrūd',36.418189,54.976282,'Iran','IR','Semnān','minor',131889,118719);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahr-e Kord',32.325556,50.864444,'Iran','IR','Chahār Maḩāl va Bakhtīārī','admin',129153,129153);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Semnān',35.576915,53.392046,'Iran','IR','Semnān','admin',124826,110950);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fasā',28.9383,53.6482,'Iran','IR','Fārs','minor',124458,98061);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Torbat-e Jām',35.244,60.6225,'Iran','IR','Khorāsān-e Raẕavī','minor',104578,58928);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ahar',38.4774,47.0699,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',103639,94348);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bam',29.106,58.357,'Iran','IR','Kermān','minor',99268,99268);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Yāsūj',30.668237,51.587963,'Iran','IR','Kohgīlūyeh va Bowyer Aḩmad','admin',96786,96786);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Behbahān',30.5959,50.2417,'Iran','IR','Khūzestān','minor',85707,79327);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chābahār',25.2919,60.643,'Iran','IR','Sīstān va Balūchestān','minor',65801,47287);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bījār',35.8727,47.6029,'Iran','IR','Kordestān','minor',53871,43741);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qaşr-e Shīrīn',34.5156,45.5791,'Iran','IR','Kermānshāh','minor',11202,11202);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chādegān',32.768248,50.628733,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dehdasht',30.794901,50.564575,'Iran','IR','Kohgīlūyeh va Bowyer Aḩmad','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zehak',30.894,61.6804,'Iran','IR','Sīstān va Balūchestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dārān',32.988707,50.41267,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar-e Māhshahr',30.556546,49.188519,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar-e Lengeh',26.557918,54.880669,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ārān Bīdgol',34.057513,51.482912,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bastak',27.199076,54.366761,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Takāb',36.4009,47.1133,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gomīshān',37.071805,54.076543,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rābor',29.2912,56.9131,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar-e Ganāveh',29.5791,50.517,'Iran','IR','Būshehr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marīvān',35.518287,46.182978,'Iran','IR','Kordestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dīvāndarreh',35.9139,47.0239,'Iran','IR','Kordestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Āz̄arshahr',37.759,45.9783,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rūdsar',37.137612,50.288001,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tīrān',32.7026,51.1537,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rāmshīr',30.893145,49.407868,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarvābād',35.3126,46.3669,'Iran','IR','Kordestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arakvāz-e Malekshāhī',33.3828,46.5983,'Iran','IR','Īlām','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mohr',27.5552,52.8836,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Esfarāyen',37.076448,57.510086,'Iran','IR','Khorāsān-e Shomālī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chenārān',36.645462,59.121232,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Narmāshīr',28.952159,58.697732,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jūybār',36.641152,52.912443,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khorramshahr',30.44079,48.184283,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ashkez̄ar',32.006609,54.214251,'Iran','IR','Yazd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarāb',37.9408,47.5367,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maḩallāt',33.911083,50.453168,'Iran','IR','Markazī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eshtehārd',35.7255,50.3662,'Iran','IR','Alborz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('‘Alīābād-e Katūl',36.910109,54.867366,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nīr',38.0346,47.9986,'Iran','IR','Ardabīl','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Borāzjān',29.269896,51.218803,'Iran','IR','Būshehr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mīnūdasht',37.230147,55.372111,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kahnūj',27.9519,57.6996,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nekā',36.650786,53.299048,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dehgolān',35.278,47.4184,'Iran','IR','Kordestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oshnavīyeh',37.0397,45.0983,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ābādeh',31.1608,52.6506,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nūr',36.571681,52.015305,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pāveh',35.0434,46.3565,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tafresh',34.693066,50.016007,'Iran','IR','Markazī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Meshgīn Shahr',38.399,47.682,'Iran','IR','Ardabīl','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nā’īn',32.860061,53.087491,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sīāhkal',37.153284,49.871361,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chālūs',36.654996,51.420397,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bonāb',37.3404,46.0561,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bahār',34.9072,48.4414,'Iran','IR','Hamadān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ābyek',36.03993,50.531015,'Iran','IR','Qazvīn','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Komījān',34.7193,49.3268,'Iran','IR','Markazī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nasīm Shahr',35.562102,51.16133,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Semīrom',31.414183,51.569443,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nehbandān',31.541853,60.036485,'Iran','IR','Khorāsān-e Jonūbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ardabīl',38.2498,48.2933,'Iran','IR','Ardabīl','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nowshahr',36.649,51.496,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Asadābād',34.782413,48.120118,'Iran','IR','Hamadān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bāneh',35.9975,45.8853,'Iran','IR','Kordestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jīroft',28.6535,57.7646,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Boshrūyeh',33.868447,57.428851,'Iran','IR','Khorāsān-e Jonūbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kangāvar',34.5043,47.9653,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rāsak',26.236817,61.399009,'Iran','IR','Sīstān va Balūchestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sīsakht',30.863928,51.455901,'Iran','IR','Kohgīlūyeh va Bowyer Aḩmad','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Naqadeh',36.9553,45.388,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kāmyārān',34.7956,46.9355,'Iran','IR','Kordestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shaft',37.1702,49.3998,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Najafābād',32.6344,51.3668,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rūdān',27.441937,57.19198,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fūman',37.224,49.3125,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hashtpar',37.79658,48.905209,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fahraj',28.9502,58.885,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shādegān',30.64924,48.664969,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Damāvand',35.718418,52.069575,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kerend-e Gharb',34.2842,46.2423,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Āq Qalā',37.013904,54.455042,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dehlorān',32.6941,47.2679,'Iran','IR','Īlām','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jājarm',36.950122,56.380045,'Iran','IR','Khorāsān-e Shomālī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pol-e Sefīd',36.117874,53.05531,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sepīdān',30.260612,51.984243,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hoveyzeh',31.4619,48.074,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eyvān',33.8272,46.3097,'Iran','IR','Īlām','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sonqor',34.7837,47.6004,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Āb Bar',36.9225,48.9745,'Iran','IR','Zanjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nahāvand',34.190877,48.374458,'Iran','IR','Hamadān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sīrīk',26.516143,57.101941,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Reẕvānshahr',37.549758,49.137029,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ardestān',33.3761,52.3694,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fāmenīn',35.1141,48.9718,'Iran','IR','Hamadān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Āzādshahr',37.08641,55.172224,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Salmās',38.1973,44.7653,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Feyẕābād',35.018907,58.783433,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khonj',27.8913,53.4344,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Asadīyeh',32.942799,59.719977,'Iran','IR','Khorāsān-e Jonūbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gāvbandī',27.2083,53.0361,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bāsht',30.361005,51.157351,'Iran','IR','Kohgīlūyeh va Bowyer Aḩmad','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Taft',31.76056,54.223034,'Iran','IR','Yazd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Garmsār',35.218242,52.340849,'Iran','IR','Semnān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Farmahīn',34.503834,49.684367,'Iran','IR','Markazī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khalkhāl',37.6189,48.5258,'Iran','IR','Ardabīl','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Behābād',31.870913,56.024332,'Iran','IR','Yazd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mehrīz',31.585255,54.441484,'Iran','IR','Yazd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Farīmān',35.70685,59.85006,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar-e Deylam',30.0542,50.159,'Iran','IR','Būshehr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qīr',28.4825,53.0346,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khorramdarreh',36.20898,49.19152,'Iran','IR','Zanjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marand',38.4329,45.7749,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jāsk',25.645335,57.775524,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khondāb',34.3928,49.1841,'Iran','IR','Markazī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khalīlābād',35.253952,58.285658,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Varazqān',38.675485,46.112051,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Manūjān',27.406976,57.501278,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Farāshband',28.8713,52.0916,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sa‘ādat Shahr',30.079207,53.134639,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hashtrūd',37.4779,47.0508,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fārsān',32.256941,50.560955,'Iran','IR','Chahār Maḩāl va Bakhtīārī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khomeyn',33.642255,50.078898,'Iran','IR','Markazī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arsanjān',29.9124,53.3085,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Şowme‘eh Sarā',37.301339,49.315038,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Solţānābād',36.403524,58.038935,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kūhbanān',31.410293,56.282547,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Haftkel',31.446858,49.529508,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarāb-e Dowreh',33.5639,48.0221,'Iran','IR','Lorestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tūyserkān',34.550998,48.443531,'Iran','IR','Hamadān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eslāmābād-e Gharb',34.1094,46.5275,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qal‘eh-ye Khvājeh',32.2064,49.4437,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sūrān',27.2855,61.9965,'Iran','IR','Sīstān va Balūchestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aleshtar',33.86419,48.262576,'Iran','IR','Lorestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rāmhormoz',31.279972,49.603511,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahrīār',35.658842,51.05775,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pārsābād',39.6482,47.9174,'Iran','IR','Ardabīl','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Meybod',32.250137,54.016585,'Iran','IR','Yazd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fārūj',37.231209,58.219004,'Iran','IR','Khorāsān-e Shomālī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fīrūzābād',28.8438,52.5707,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chelgard',32.46668,50.123084,'Iran','IR','Chahār Maḩāl va Bakhtīārī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bābolsar',36.702506,52.6576,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bāfq',31.603498,55.402492,'Iran','IR','Yazd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahr-e Herāt',30.054072,54.372938,'Iran','IR','Yazd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rāmsar',36.917956,50.648016,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalāt-e Nāderī',36.995322,59.764721,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kavār',29.205,52.6899,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dūst Moḩammad Khān',31.1447,61.7925,'Iran','IR','Sīstān va Balūchestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarbīsheh',32.575658,59.798205,'Iran','IR','Khorāsān-e Jonūbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarvestān',29.2735,53.2203,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lāmerd',27.334,53.179,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Namīn',38.4269,48.4839,'Iran','IR','Ardabīl','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ferdows',34.018498,58.172222,'Iran','IR','Khorāsān-e Jonūbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khāsh',28.221072,61.215819,'Iran','IR','Sīstān va Balūchestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shalamzār',32.045392,50.817135,'Iran','IR','Chahār Maḩāl va Bakhtīārī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bāft',29.2331,56.6022,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Deyr',27.8399,51.9378,'Iran','IR','Būshehr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Roshtkhvār',34.975119,59.624818,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bajestān',34.516388,58.184504,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pākdasht',35.478544,51.683396,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shāzand',33.9276,49.4116,'Iran','IR','Markazī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qeshm',26.9492,56.2691,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pīshvā',35.308,51.7267,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dārāb',28.751944,54.544444,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Anār',30.870659,55.270247,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Garmeh',36.987004,56.289424,'Iran','IR','Khorāsān-e Shomālī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gīlān-e Gharb',34.1421,45.9203,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Behshahr',36.692347,53.552617,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pā’īn-e Bāzār-e Rūdbār',36.8211,49.4264,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bardsīr',29.92266,56.574335,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Golpāyegān',33.453702,50.288361,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fāryāb',28.098699,57.231814,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Īrānshahr',27.202446,60.684758,'Iran','IR','Sīstān va Balūchestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hendījān',30.2363,49.7119,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lāhījān',37.207318,50.003971,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pīrānshahr',36.701,45.1413,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qarah Āghāj',37.2187,47.2167,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dāmghān',36.167905,54.342924,'Iran','IR','Semnān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('‘Ajab Shīr',37.4776,45.8943,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jam',27.828167,52.325358,'Iran','IR','Būshehr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bardaskan',35.26218,57.970745,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nīkshahr',26.2258,60.2143,'Iran','IR','Sīstān va Balūchestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ţorqabeh',36.3104,59.3735,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Āstārā',38.4291,48.872,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mākū',39.295126,44.498216,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marvdasht',29.8742,52.8025,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dowlatābād',32.79978,51.695527,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Abarkūh',31.1289,53.2824,'Iran','IR','Yazd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gonābād',34.352865,58.683647,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ardakān',32.310011,54.017474,'Iran','IR','Yazd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ardal',31.999691,50.662308,'Iran','IR','Chahār Maḩāl va Bakhtīārī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩājjīābād',33.604956,59.993404,'Iran','IR','Khorāsān-e Jonūbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neyrīz',29.1988,54.3278,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mehrān',33.1222,46.1646,'Iran','IR','Īlām','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kangān',27.834,52.0628,'Iran','IR','Būshehr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kāzerūn',29.619491,51.654147,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shūsh',32.1942,48.2436,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khodābandeh',36.1189,48.5894,'Iran','IR','Zanjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rafsanjān',30.4067,55.9939,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Borūjen',31.965232,51.287295,'Iran','IR','Chahār Maḩāl va Bakhtīārī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shāhīn Dezh',36.6793,46.5669,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarābleh',33.767724,46.565777,'Iran','IR','Īlām','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Do Gonbadān',30.3586,50.7981,'Iran','IR','Kohgīlūyeh va Bowyer Aḩmad','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Abhar',36.1468,49.218,'Iran','IR','Zanjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Meyāmī',36.410919,55.650182,'Iran','IR','Semnān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zābolī',27.130999,61.674446,'Iran','IR','Sīstān va Balūchestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahr-e Qadīm-e Lār',27.683362,54.34172,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khvānsār',33.220521,50.314969,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Āshkhāneh',37.561495,56.921249,'Iran','IR','Khorāsān-e Shomālī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahr-e Qods',35.7214,51.109,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Neqāb',36.707917,57.421461,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gerāsh',27.669664,54.135859,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Delījān',33.9905,50.6838,'Iran','IR','Markazī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jahrom',28.5,53.5605,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Galūgāh',36.727341,53.808879,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kord Kūy',36.793068,54.112135,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Charām',30.746,50.746,'Iran','IR','Kohgīlūyeh va Bowyer Aḩmad','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarpol-e Z̄ahāb',34.461092,45.862644,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Seyah Cheshmeh',39.06508,44.384157,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar-e Gaz',36.774086,53.947981,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gālīkesh',37.272593,55.433939,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dowlatābād',35.282187,59.519719,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sūrīān',30.4551,53.651,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qā’en',33.726539,59.184393,'Iran','IR','Khorāsān-e Jonūbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mīāneh',37.421,47.715,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Andīmeshk',32.461496,48.353677,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qā’em Shahr',36.48144,52.891093,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shabestar',38.1804,45.7028,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khomārlū',39.1489,47.0347,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tonekābon',36.816259,50.873763,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Estahbān',29.1266,54.0421,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Robāţ Karīm',35.4846,51.0829,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dehāqān',31.94004,51.647861,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lordegān',31.51338,50.82672,'Iran','IR','Chahār Maḩāl va Bakhtīārī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maḩmūdābād',36.631907,52.262858,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shūshtar',32.049721,48.848429,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ţabas',33.595856,56.924368,'Iran','IR','Yazd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahrak-e Bākharz',34.992045,60.31714,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bīleh Savār',39.379613,48.354626,'Iran','IR','Ardabīl','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩājjīābād',28.3091,55.9017,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Līkak',30.8949,50.0931,'Iran','IR','Kohgīlūyeh va Bowyer Aḩmad','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tākestān',36.0696,49.6959,'Iran','IR','Qazvīn','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bū’īn Zahrā',35.7669,50.0578,'Iran','IR','Qazvīn','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sūrak',36.594884,53.207623,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sorkheh',35.4633,53.214,'Iran','IR','Semnān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarakhs',36.5449,61.1577,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mollās̄ānī',31.5851,48.885,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khowrmūj',28.6543,51.38,'Iran','IR','Būshehr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Āshtīān',34.522984,50.00608,'Iran','IR','Markazī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mīāndoāb',36.966671,46.109612,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Darreh Shahr',33.144468,47.379903,'Iran','IR','Īlām','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Razan',35.3866,49.0338,'Iran','IR','Hamadān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qal‘eh Ganj',27.5236,57.8811,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Herīs',38.248156,47.116777,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Māhneshān',36.7444,47.6725,'Iran','IR','Zanjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zarand',30.812709,56.563993,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahreẕā',32.0089,51.8668,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ārādān',35.249405,52.494216,'Iran','IR','Semnān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tāybād',34.74,60.7756,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dorūd',33.497135,49.057768,'Iran','IR','Lorestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sar‘eyn',38.1513,48.0708,'Iran','IR','Ardabīl','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Naz̧arābād',35.954109,50.606075,'Iran','IR','Alborz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eslāmābād',28.026114,58.0,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zarrīn Shahr',32.3897,51.3766,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dalgān',27.482317,59.446559,'Iran','IR','Sīstān va Balūchestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oskū',37.915037,46.122576,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('‘Anbarābād',28.4759,57.848,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bābol',36.551321,52.678951,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shīrvān',37.396693,57.929517,'Iran','IR','Khorāsān-e Shomālī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alvand',36.1893,50.0643,'Iran','IR','Qazvīn','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Şafāshahr',30.6131,53.1954,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mehdīshahr',35.710714,53.353937,'Iran','IR','Semnān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Falāvarjān',32.555301,51.509735,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moḩammadābād',28.668767,59.073411,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Būkān',36.521,46.2089,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Amlash',37.097427,50.186522,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Javānrūd',34.8067,46.4913,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Omīdīyeh',30.759722,49.705,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Joghtāy',36.636188,57.072836,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('‘Abbāsābād',36.727686,51.105737,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fereydūnkenār',36.686418,52.522548,'Iran','IR','Māzandarān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kūhdasht',33.533349,47.609989,'Iran','IR','Lorestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩājjīābād',28.357352,54.423346,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kherāmeh',29.498959,53.311989,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eqlīd',30.898854,52.697011,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malārd',35.6659,50.9767,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eslāmshahr',35.552224,51.235036,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bāgh-e Malek',31.523135,49.886239,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ravānsar',34.7153,46.6533,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arzū’īyeh',28.4414,56.3728,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maşīrī',30.245844,51.522326,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Abū Mūsā',25.86698,55.023633,'Iran','IR',NULL,'minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khvāf',34.576299,60.14093,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sūsangerd',31.563497,48.189576,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bozghān',36.286395,58.585864,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Īz̄eh',31.834079,49.867246,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qarah Ẕīā’ od Dīn',38.8915,45.0255,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tajrīsh',35.8044,51.4256,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zarrīnābād',36.426221,48.281583,'Iran','IR','Zanjān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mīnāb',27.131043,57.087159,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Langarūd',37.197006,50.153508,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fīrūzkūh',35.756736,52.770624,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar-e Anzalī',37.473182,49.457853,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ţāleqān',36.174486,50.769083,'Iran','IR','Alborz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aznā',33.4557,49.4555,'Iran','IR','Lorestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fareydūnshahr',32.940979,50.121,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Poldasht',39.348,45.071,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar-e Torkaman',36.901237,54.071948,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gīvī',37.685846,48.342035,'Iran','IR','Ardabīl','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Māmūnīyeh',35.305553,50.499199,'Iran','IR','Markazī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jolfā',38.9404,45.6308,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Saqqez',36.2463,46.2665,'Iran','IR','Kordestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lālī',32.329,49.0936,'Iran','IR','Khūzestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rāvar',31.265625,56.80545,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar-e Khamīr',26.9521,55.5851,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bandar-e ‘Asalūyeh',27.4761,52.6074,'Iran','IR','Būshehr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ābdānān',32.9926,47.4198,'Iran','IR','Īlām','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bostānābād',37.846331,46.835416,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Harsīn',34.2721,47.5861,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Konārak',25.3604,60.3995,'Iran','IR','Sīstān va Balūchestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Germī',39.0215,48.0801,'Iran','IR','Ardabīl','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Māsāl',37.3631,49.1329,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shāhīn Shahr',32.857879,51.552904,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rāmīān',37.015976,55.141226,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kabūdarāhang',35.2084,48.724,'Iran','IR','Hamadān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tāzehābād',34.7387,46.1496,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ahram',28.8826,51.2746,'Iran','IR','Būshehr','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mobārakeh',32.346508,51.504494,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahr-e Bābak',30.1165,55.1186,'Iran','IR','Kermān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Şaḩneh',34.4813,47.6908,'Iran','IR','Kermānshāh','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Showţ',39.2192,44.77,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khūr',33.775123,55.083294,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Naţanz',33.51118,51.918082,'Iran','IR','Eşfahān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarāyān',33.86017,58.521659,'Iran','IR','Khorāsān-e Jonūbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dargaz',37.444466,59.108087,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Āstāneh-ye Ashrafīyeh',37.263178,49.943248,'Iran','IR','Gīlān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalāleh',37.37899,55.493002,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hashtgerd',35.962,50.6799,'Iran','IR','Alborz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malekān',37.142585,46.103447,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nūrābād',34.0734,47.9725,'Iran','IR','Lorestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kaleybar',38.865089,47.039091,'Iran','IR','Āz̄arbāyjān-e Sharqī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marāveh Tappeh',37.904096,55.955965,'Iran','IR','Golestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Poldokhtar',33.152492,47.710136,'Iran','IR','Lorestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qorveh',35.1664,47.8045,'Iran','IR','Kordestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alīgūdarz',33.400633,49.694901,'Iran','IR','Lorestān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sardasht',36.1552,45.4788,'Iran','IR','Āz̄arbāyjān-e Gharbī','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sardasht',26.4559,57.9028,'Iran','IR','Hormozgān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rey',35.593545,51.439966,'Iran','IR','Tehrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nūrābād',30.114052,51.521744,'Iran','IR','Fārs','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Torbat-e Ḩeydarīyeh',35.274007,59.219487,'Iran','IR','Khorāsān-e Raẕavī','minor',NULL,NULL);
