INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vilnius',54.683333,25.316667,'Lithuania','LT','Vilniaus Miestas','primary',542366,507029);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kaunas',54.902716,23.909613,'Lithuania','LT','Kauno Miestas','admin',374643,353046);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Klaipėda',55.70888,21.143121,'Lithuania','LT','Klaipėdos Miestas','admin',192307,190361);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vijoliai',55.954889,23.282076,'Lithuania','LT',NULL,NULL,133528,130587);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Paežerys I',55.759514,24.409858,'Lithuania','LT','Panevėžys',NULL,127405,117395);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šalčininkai',54.308638,25.386766,'Lithuania','LT','Šalčininkai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skuodas',56.270572,21.532077,'Lithuania','LT','Skuodas','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Telšiai',55.983069,22.234348,'Lithuania','LT','Telšiai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Panevėžys',55.73186,24.359828,'Lithuania','LT','Panevėžio Miestas','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ignalina',55.340628,26.160488,'Lithuania','LT','Ignalina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Palanga',55.920313,21.071014,'Lithuania','LT','Palangos Miestas','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Širvintos',55.043999,24.954462,'Lithuania','LT','Širvintos','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Visaginas',55.596775,26.439842,'Lithuania','LT','Visaginas','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Varėna',54.215463,24.57538,'Lithuania','LT','Varėna','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rietavas',55.727082,21.923428,'Lithuania','LT','Rietavo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Raseiniai',55.379732,23.123857,'Lithuania','LT','Raseiniai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rokiškis',55.958668,25.594662,'Lithuania','LT','Rokiškis','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šiauliai',55.933333,23.316667,'Lithuania','LT','Šiaulių Miestas','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kazlų Rūda',54.749666,23.495021,'Lithuania','LT','Kazlų Rūdos','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mažeikiai',56.312215,22.326509,'Lithuania','LT','Mažeikiai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kelmė',55.630085,22.934897,'Lithuania','LT','Kelmė','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Joniškis',56.239394,23.615407,'Lithuania','LT','Joniškis','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Biržai',56.198588,24.75208,'Lithuania','LT','Biržai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Birštonas',54.604823,24.031141,'Lithuania','LT','Birštono','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marijampolė',54.559913,23.35412,'Lithuania','LT','Marijampolė','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kupiškis',55.840149,24.980331,'Lithuania','LT','Kupiškis','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radviliškis',55.811144,23.541143,'Lithuania','LT','Radviliškis','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kretinga',55.888804,21.244482,'Lithuania','LT','Kretinga','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jurbarkas',55.075561,22.764165,'Lithuania','LT','Jurbarkas','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tauragė',55.252222,22.289722,'Lithuania','LT','Tauragė','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalvarija',54.417194,23.228296,'Lithuania','LT','Kalvarijos','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pagėgiai',55.137935,21.913782,'Lithuania','LT','Pagégiai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prienai',54.636002,23.945849,'Lithuania','LT','Prienai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Švenčionys',55.132959,26.159531,'Lithuania','LT','Švenčionys','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zarasai',55.732247,26.251151,'Lithuania','LT','Zarasai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pasvalys',56.062507,24.399654,'Lithuania','LT','Pasvalys','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lazdijai',54.233263,23.514661,'Lithuania','LT','Lazdijai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Plungė',55.907743,21.845554,'Lithuania','LT','Plungė','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kėdainiai',55.287821,23.972748,'Lithuania','LT','Kėdainiai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šilutė',55.345331,21.473328,'Lithuania','LT','Šilutė','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Druskininkai',54.015728,23.987028,'Lithuania','LT','Druskininkai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nida',55.3086,20.996513,'Lithuania','LT','Neringa','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jonava',55.080139,24.275436,'Lithuania','LT','Jonava','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Anykščiai',55.524558,25.106609,'Lithuania','LT','Anykščiai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šilalė',55.489801,22.186925,'Lithuania','LT','Šilalė','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kaišiadorys',54.865282,24.468154,'Lithuania','LT','Kaišiadorys','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Elektrėnai',54.786345,24.662601,'Lithuania','LT','Elektrénai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Molėtai',55.224694,25.416883,'Lithuania','LT','Molėtai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pakruojis',55.978891,23.85508,'Lithuania','LT','Pakruojis','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Utena',55.497642,25.599184,'Lithuania','LT','Utena','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alytus',54.396354,24.041416,'Lithuania','LT','Alytaus Miestas','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šakiai',54.953386,23.047789,'Lithuania','LT','Šakiai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Akmenė',56.25,22.75,'Lithuania','LT','Akmenė','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trakai',54.639938,24.935993,'Lithuania','LT','Trakai','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vilkaviškis',54.648019,23.030463,'Lithuania','LT','Vilkaviškis','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ukmergė',55.249396,24.763645,'Lithuania','LT','Ukmergė','admin',NULL,NULL);
