INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chisinau',47.005556,28.8575,'Moldova','MD','Chişinău','primary',688134,635994);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tiraspol',46.842744,29.629086,'Moldova','MD','Stînga Nistrului','admin',157000,117194);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bălţi',47.763138,27.929317,'Moldova','MD','Bălţi','admin',151355,118690);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cahul',45.904246,28.199294,'Moldova','MD','Cahul','admin',63407,34492);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dubăsari',47.265621,29.16667,'Moldova','MD','Stînga Nistrului',NULL,23254,23254);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Taraclia',45.902735,28.668159,'Moldova','MD','Taraclia','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ştefan Vodă',46.512869,29.661934,'Moldova','MD','Ştefan-Vodă','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Donduşeni',48.239416,27.605551,'Moldova','MD','Donduşeni','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bender',46.83156,29.477694,'Moldova','MD','Bender','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Edineţ',48.172149,27.30337,'Moldova','MD','Edineţ','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Straşeni',47.142161,28.607735,'Moldova','MD','Străşeni','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Drochia',48.035546,27.812935,'Moldova','MD','Drochia','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Basarabeasca',46.331701,28.963646,'Moldova','MD','Basarabeasca','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ialoveni',46.943464,28.782328,'Moldova','MD','Ialoveni','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cocieri',47.308721,29.110106,'Moldova','MD','Dubăsari','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rîşcani',47.947925,27.563759,'Moldova','MD','Rîşcani','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Teleneşti',47.5011,28.36536,'Moldova','MD','Teleneşti','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Floreşti',47.891372,28.293123,'Moldova','MD','Floreşti','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rezina',47.749284,28.965826,'Moldova','MD','Rezina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Briceni',48.362892,27.077875,'Moldova','MD','Briceni','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Şoldăneşti',47.816084,28.797182,'Moldova','MD','Şoldăneşti','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Orhei',47.384936,28.824457,'Moldova','MD','Orhei','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Făleşti',47.576668,27.712644,'Moldova','MD','Făleşti','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ocniţa',48.38274,27.438051,'Moldova','MD','Ocniţa','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leova',46.482295,28.253014,'Moldova','MD','Leova','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cantemir',46.277428,28.202703,'Moldova','MD','Cantemir','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sîngerei',47.636321,28.142962,'Moldova','MD','Sîngerei','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Anenii Noi',46.878387,29.234831,'Moldova','MD','Anenii Noi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Căuşeni',46.636744,29.411142,'Moldova','MD','Căuşeni','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Comrat',46.294555,28.656501,'Moldova','MD','Găgăuzia','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Criuleni',47.213069,29.159258,'Moldova','MD','Criuleni','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cimişlia',46.526847,28.764414,'Moldova','MD','Cimişlia','admin',NULL,NULL);
