INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Potkrajnica',42.451667,19.303611,'Montenegro','ME',NULL,NULL,145850,136473);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Petnjica',42.908889,19.964444,'Montenegro','ME','Petnjica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ulcinj',41.928333,19.206389,'Montenegro','ME','Ulcinj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Budva',42.286389,18.84,'Montenegro','ME','Budva','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nikšić',42.775,18.958333,'Montenegro','ME','Nikšić','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Danilovgrad',42.547222,19.105278,'Montenegro','ME','Danilovgrad','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tivat',42.436389,18.696111,'Montenegro','ME','Tivat','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rožaje',42.843889,20.168333,'Montenegro','ME','Rožaje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Golubovci',42.335,19.231111,'Montenegro','ME',NULL,'minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Plav',42.596944,19.945556,'Montenegro','ME','Plav','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Plužine',43.152778,18.839444,'Montenegro','ME','Plužine','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bar',42.093056,19.100278,'Montenegro','ME','Bar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Podgorica',42.441111,19.263611,'Montenegro','ME','Podgorica','primary',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mojkovac',42.963889,19.5825,'Montenegro','ME','Mojkovac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žabljak',43.154722,19.121944,'Montenegro','ME','Žabljak','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Herceg-Novi',42.453056,18.5375,'Montenegro','ME','Herceg Novi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šavnik',42.956389,19.096667,'Montenegro','ME','Šavnik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cetinje',42.392222,18.9225,'Montenegro','ME','Cetinje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tuzi',42.365556,19.331389,'Montenegro','ME',NULL,'minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Andrijevica',42.733889,19.791944,'Montenegro','ME','Andrijevica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kolašin',42.824167,19.5225,'Montenegro','ME','Kolašin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Berane',42.8425,19.873333,'Montenegro','ME','Berane','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kotor',42.425833,18.771944,'Montenegro','ME','Kotor','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bijelo Polje',43.029167,19.745556,'Montenegro','ME','Bijelo Polje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gusinje',42.561944,19.833889,'Montenegro','ME','Gusinje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pljevlja',43.352222,19.354167,'Montenegro','ME','Pljevlja','admin',NULL,NULL);
