INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skopje',41.996457,21.431407,'Macedonia','MK',NULL,'primary',494087,474889);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tetovo',42.009734,20.971548,'Macedonia','MK','Tetovo','admin',119132,72944);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bitola',41.031429,21.334736,'Macedonia','MK','Bitola','admin',86528,64574);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vinica',41.882778,22.509167,'Macedonia','MK','Vinica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Češinovo',41.871484,22.289609,'Macedonia','MK','Češinovo-Obleševo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Demir Kapija',41.406129,22.246315,'Macedonia','MK','Demir Kapija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radoviš',41.638333,22.464722,'Macedonia','MK','Radoviš','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sopište',41.954722,21.4275,'Macedonia','MK','Sopište','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gradsko',41.5775,21.942778,'Macedonia','MK','Gradsko','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vasilevo',41.474081,22.64301,'Macedonia','MK','Vasilevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kruševo',41.369399,21.248284,'Macedonia','MK','Kruševo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Resen',41.089341,21.010924,'Macedonia','MK','Resen','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zelenikovo',41.884134,21.588477,'Macedonia','MK','Zelenikovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gevgelija',41.141658,22.501411,'Macedonia','MK','Gevgelija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Makedonska Kamenica',42.020793,22.587603,'Macedonia','MK','Makedonska Kamenica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Veles',41.715556,21.775556,'Macedonia','MK','Veles','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sveti Nikole',41.866683,21.941127,'Macedonia','MK','Sveti Nikole','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Novo Selo',41.414859,22.881639,'Macedonia','MK','Novo Selo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pehčevo',41.762258,22.889214,'Macedonia','MK','Pehčevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Plasnica',41.467222,21.123056,'Macedonia','MK','Plasnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bogovinje',41.923611,20.913611,'Macedonia','MK','Bogovinje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vevčani',41.240556,20.593333,'Macedonia','MK','Vevčani','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karbinci',41.817581,22.23529,'Macedonia','MK','Karbinci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Konče',41.495112,22.383587,'Macedonia','MK','Konče','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kičevo',41.512671,20.958858,'Macedonia','MK','Kičevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Struga',41.17799,20.677844,'Macedonia','MK','Struga','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kočani',41.916389,22.412778,'Macedonia','MK','Kočani','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rostuša',41.61,20.6,'Macedonia','MK','Mavrovo i Rostuša','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rosoman',41.516713,21.945849,'Macedonia','MK','Rosoman','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tearce',42.076655,21.0531,'Macedonia','MK','Tearce','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kavadarci',41.433056,22.011944,'Macedonia','MK','Kavadarci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Staro Nagoričane',42.198056,21.828611,'Macedonia','MK','Staro Nagoričane','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lozovo',41.783889,21.905556,'Macedonia','MK','Lozovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brvenica',41.967222,20.980833,'Macedonia','MK','Brvenica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Demir Hisar',41.220967,21.203024,'Macedonia','MK','Demir Hisar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prilep',41.34514,21.555037,'Macedonia','MK','Prilep','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bogdanci',41.203056,22.575556,'Macedonia','MK','Bogdanci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Strumica',41.4375,22.643333,'Macedonia','MK','Strumica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kratovo',42.078385,22.180701,'Macedonia','MK','Kratovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Čučer-Sandevo',42.102021,21.384579,'Macedonia','MK','Čučer-Sandevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Star Dojran',41.186473,22.720305,'Macedonia','MK','Dojran','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kriva Palanka',42.200882,22.332444,'Macedonia','MK','Kriva Palanka','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Petrovec',41.938889,21.615,'Macedonia','MK','Petrovec','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aračinovo',42.026389,21.561944,'Macedonia','MK','Aračinovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bosilovo',41.440556,22.727778,'Macedonia','MK','Bosilovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Makedonski Brod',41.513611,21.215278,'Macedonia','MK','Makedonski Brod','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Probištip',42.0019,22.172767,'Macedonia','MK','Probištip','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rankovce',42.168566,22.11664,'Macedonia','MK','Rankovce','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valandovo',41.317444,22.560018,'Macedonia','MK','Valandovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vrapčište',41.834394,20.885626,'Macedonia','MK','Vrapčište','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lipkovo',42.156389,21.585278,'Macedonia','MK','Lipkovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dolneni',41.425788,21.45402,'Macedonia','MK','Dolneni','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Berovo',41.703056,22.857778,'Macedonia','MK','Berovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krivogaštani',41.336938,21.33111,'Macedonia','MK','Krivogaštani','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Negotino',41.484557,22.090563,'Macedonia','MK','Negotino','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ohrid',41.117222,20.801944,'Macedonia','MK','Ohrid','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Čaška',41.648719,21.692241,'Macedonia','MK','Čaška','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Studeničani',41.915833,21.530556,'Macedonia','MK','Studeničani','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Štip',41.74227,22.197932,'Macedonia','MK','Štip','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Belčišta',41.302778,20.830278,'Macedonia','MK','Debarca','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Novaci',41.041974,21.458663,'Macedonia','MK','Novaci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mogila',41.108333,21.378611,'Macedonia','MK','Mogila','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Delčevo',41.96539,22.776266,'Macedonia','MK','Delčevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ilinden',41.994514,21.580023,'Macedonia','MK','Ilinden','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gostivar',41.796014,20.908191,'Macedonia','MK','Gostivar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Želino',41.982474,21.06241,'Macedonia','MK','Želino','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Centar Župa',41.478775,20.558629,'Macedonia','MK','Centar Župa','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kumanovo',42.132222,21.714444,'Macedonia','MK','Kumanovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Debar',41.524441,20.524206,'Macedonia','MK','Debar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zrnovci',41.854167,22.444444,'Macedonia','MK','Zrnovci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jegunovce',42.072379,21.123674,'Macedonia','MK','Jegunovce','admin',NULL,NULL);
