INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valletta',35.899722,14.514722,'Malta','MT','Valletta','primary',368250,6966);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Saint Paul’s Bay',35.948333,14.400556,'Malta','MT','San Pawl il-Baħar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Siġġiewi',35.855556,14.436389,'Malta','MT','Siġġiewi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Xewkija',36.032778,14.258056,'Malta','MT','Xewkija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Imġarr',35.920556,14.366389,'Malta','MT','Imġarr','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pietà',35.894722,14.495,'Malta','MT','Pietà','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kirkop',35.842222,14.485278,'Malta','MT','Kirkop','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kerċem',36.041944,14.226667,'Malta','MT','Kerċem','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sannat',36.024444,14.242778,'Malta','MT','Sannat','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fontana',36.0375,14.236111,'Malta','MT','Fontana','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tarxien',35.865833,14.515,'Malta','MT','Tarxien','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gżira',35.905833,14.488056,'Malta','MT','Gżira','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Għaxaq',35.848889,14.516667,'Malta','MT','Għaxaq','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Għasri',36.057778,14.226389,'Malta','MT','Għasri','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mellieħa',35.956389,14.362222,'Malta','MT','Mellieħa','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sliema',35.9125,14.501944,'Malta','MT','Sliema','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żejtun',35.855833,14.533056,'Malta','MT','Żejtun','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qormi',35.878333,14.471944,'Malta','MT','Qormi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żebbuġ',35.871944,14.441111,'Malta','MT','Żebbuġ','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lija',35.900556,14.446389,'Malta','MT','Lija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gudja',35.849167,14.503056,'Malta','MT','Gudja','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Balzan',35.900278,14.455,'Malta','MT','Balzan','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Swieqi',35.9225,14.48,'Malta','MT','Swieqi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pembroke',35.930556,14.476389,'Malta','MT','Pembroke','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Xgħajra',35.885556,14.5475,'Malta','MT','Xgħajra','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalkara',35.889167,14.532778,'Malta','MT','Kalkara','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Għarb',36.06,14.208889,'Malta','MT','Għarb','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Munxar',36.03,14.233333,'Malta','MT','Munxar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fgura',35.870278,14.513333,'Malta','MT','Fgura','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Attard',35.889722,14.4425,'Malta','MT','Attard','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Lawrenz',36.055556,14.203611,'Malta','MT','San Lawrenz','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nadur',36.037778,14.294167,'Malta','MT','Nadur','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Xagħra',36.05,14.264444,'Malta','MT','Xagħra','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Imtarfa',35.893333,14.398889,'Malta','MT','Imtarfa','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Paola',35.873056,14.498889,'Malta','MT','Paola','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marsaxlokk',35.841944,14.543056,'Malta','MT','Marsaxlokk','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ħamrun',35.884722,14.484444,'Malta','MT','Ħamrun','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Għajnsielem',36.026389,14.285,'Malta','MT','Għajnsielem','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cospicua',35.885556,14.5275,'Malta','MT','Bormla','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mosta',35.909167,14.425556,'Malta','MT','Mosta','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Imsida',35.8925,14.482778,'Malta','MT','Imsida','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dingli',35.861389,14.382222,'Malta','MT','Dingli','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marsaskala',35.866944,14.561944,'Malta','MT','Marsaskala','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Imdina',35.886944,14.4025,'Malta','MT','Imdina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qrendi',35.834722,14.458333,'Malta','MT','Qrendi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Victoria',36.044444,14.239722,'Malta','MT','Rabat (Ghawdex)','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rabat',35.882222,14.398056,'Malta','MT','Rabat','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Ġiljan',35.919722,14.484444,'Malta','MT','San Ġiljan','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Għargħur',35.924167,14.451944,'Malta','MT','Għargħur','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żurrieq',35.831111,14.474167,'Malta','MT','Żurrieq','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Iklin',35.909167,14.452222,'Malta','MT','Iklin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Senglea',35.8875,14.516944,'Malta','MT','Isla','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Safi',35.833056,14.484722,'Malta','MT','Safi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ta’ Xbiex',35.899167,14.494444,'Malta','MT','Ta’ Xbiex','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('San Ġwann',35.905556,14.476111,'Malta','MT','San Ġwann','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vittoriosa',35.892222,14.518333,'Malta','MT','Birgu','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Naxxar',35.913611,14.443611,'Malta','MT','Naxxar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żebbuġ',36.072222,14.235833,'Malta','MT','Żebbuġ (Ghawdex)','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Venera',35.890833,14.474167,'Malta','MT','Santa Venera','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Imqabba',35.846111,14.467222,'Malta','MT','Imqabba','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qala',36.036111,14.309444,'Malta','MT','Qala','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Luqa',35.858889,14.488611,'Malta','MT','Luqa','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żabbar',35.876111,14.535,'Malta','MT','Żabbar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Floriana',35.895833,14.508333,'Malta','MT','Floriana','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Luċija',36.043056,14.217222,'Malta','MT','Santa Luċija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Birżebbuġa',35.825833,14.526944,'Malta','MT','Birżebbuġa','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marsa',35.879167,14.495278,'Malta','MT','Marsa','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Birkirkara',35.897222,14.461111,'Malta','MT','Birkirkara','admin',NULL,NULL);
