INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oslo',59.916667,10.75,'Norway','NO','Oslo','primary',835000,580000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bergen',60.391111,5.324722,'Norway','NO','Hordaland','admin',213585,187194);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stavanger',58.966667,5.75,'Norway','NO','Rogaland','admin',173132,100866);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trondheim',63.416667,10.416667,'Norway','NO','Sør-Trøndelag','admin',147139,141533);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Drammen',59.7425,10.211667,'Norway','NO','Buskerud','admin',90722,80153);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skyer',59.2,9.683333,'Norway','NO','Telemark',NULL,73330,73330);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kristiansand',58.166667,8.0,'Norway','NO','Vest-Agder','admin',63814,52770);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tomasjorda',69.666667,19.016667,'Norway','NO','Troms',NULL,52436,45365);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ålesund',62.47276,6.15346,'Norway','NO','Møre og Romsdal','minor',47772,42982);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sandnes',58.85,5.733333,'Norway','NO','Rogaland','minor',46911,46911);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Haugesund',59.411944,5.2775,'Norway','NO','Rogaland','minor',40321,32118);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tønsberg',59.285833,10.418056,'Norway','NO','Vestfold','admin',38914,38914);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moss',59.436667,10.669167,'Norway','NO','Østfold','minor',36901,34492);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bodø',67.283333,14.383333,'Norway','NO','Nordland','admin',34073,28694);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arendal',58.460278,8.766667,'Norway','NO','Aust-Agder','admin',30916,30916);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hamar',60.8,11.1,'Norway','NO','Hedmark','admin',29479,29479);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gjøvik',60.8,10.7,'Norway','NO','Oppland','minor',22719,17596);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mo i Rana',66.316667,14.166667,'Norway','NO','Nordland','minor',20409,17853);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Narvik',68.435556,17.437222,'Norway','NO','Nordland','minor',20000,18473);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lillehammer',61.133333,10.5,'Norway','NO','Oppland','admin',19542,19096);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Harstad',68.8025,16.545556,'Norway','NO','Troms','minor',19433,18973);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Molde',62.733333,7.183333,'Norway','NO','Møre og Romsdal','admin',18594,13749);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alta',69.966667,23.241667,'Norway','NO','Finnmark','minor',12077,12077);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Steinkjer',64.016667,11.5,'Norway','NO','Nord-Trøndelag','admin',11274,11113);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hammerfest',70.661667,23.688333,'Norway','NO','Finnmark','minor',10000,9934);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Namsos',64.483333,11.5,'Norway','NO','Nord-Trøndelag','minor',9035,9035);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vossevangen',60.633333,6.433333,'Norway','NO','Hordaland',NULL,5571,5571);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vadsø',70.073056,29.769722,'Norway','NO','Finnmark','admin',5139,5139);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Svolvær',68.233333,14.566667,'Norway','NO','Nordland','minor',4197,4197);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Finnsnes',69.233333,17.983333,'Norway','NO','Troms','minor',3907,3315);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kirkenes',69.725,30.051667,'Norway','NO','Finnmark','minor',3282,2174);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rørvik',64.85,11.233333,'Norway','NO','Nord-Trøndelag','minor',2615,2615);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hermansverk',61.183333,6.85,'Norway','NO','Sogn og Fjordane','admin',1965,1965);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skogsvåg',60.25559,5.10167,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Noresund',60.166667,9.616667,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sandnessjøen',66.016667,12.633333,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hansnes',69.966667,19.6,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Råde',59.35,10.85,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tingvoll',62.913056,8.205556,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Årdalstangen',61.233333,7.716667,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rosendal',59.983333,6.016667,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Batnfjordsøra',62.883333,7.7,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Namdalseid',64.22287,11.22102,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jaren',60.383333,10.55,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hov',60.7,10.35,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kragerø',58.866667,9.416667,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stranda',62.316667,6.9,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gratangen',68.65,17.683333,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valldal',62.333333,7.35,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ulefoss',59.283333,9.266667,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Våler',60.666667,11.833333,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Drøbak',59.663333,10.631111,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hokksund',59.77187,9.88385,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lurøy',66.417,12.84472,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vik',65.3,12.15,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tysse',60.370833,5.756111,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kleppe',58.766667,5.666667,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skjåk',61.88105,8.36928,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vågå',61.86877,9.12332,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Åseral',58.616667,7.416667,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Langesund',59.0,9.75,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sørumsand',59.966667,11.25,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Randaberg',59.0,5.6,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Treungen',59.033333,8.55,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ølen',59.603611,5.8075,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sykkylven',62.39723,6.58321,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ål',60.633333,8.566667,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kongsberg',59.65,9.65,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ski',59.716667,10.833333,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dale',60.583333,5.816667,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lyngdal',58.133333,7.083333,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kongsvinger',60.2,12.0,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brøstadbotn',69.079444,17.701389,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sør-Fron',61.566667,9.933333,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oppdal',62.6,9.666667,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bjørkelangen',59.883333,11.566667,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alvdal',62.116667,10.65,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brekstad',63.683333,9.683333,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Iveland',58.44727,7.91631,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Storslett',69.766667,21.016667,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Søgne',58.083333,7.816667,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rena',61.133333,11.366667,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Evje',58.6,7.85,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brønnøysund',65.466667,12.216667,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Selbu',63.21654,11.03954,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nesna',66.2,13.033333,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nannestad',60.212364,11.004408,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Andenes',69.320278,16.142778,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Borkenes',68.783333,16.183333,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bremnes',59.795278,5.175278,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jevnaker',60.25,10.466667,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bruflat',60.883333,9.616667,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stokmarknes',68.561944,14.908611,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kjøllefjord',70.933333,27.35,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Røyrvik',64.883333,13.55,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fiskå',62.09988,5.55656,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rognan',67.1,15.383333,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hommelvik',63.416667,10.8,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Volda',62.15,6.1,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alstad',63.58519,10.73769,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valderhaug',62.49853,6.12775,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Surnadal',62.97544,8.72457,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hauge',58.35,6.283333,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bø',59.416667,9.066667,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gryllefjord',69.366667,17.016667,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kopervik',59.283333,5.3,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gjerstad',58.866667,9.0,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leksvik',63.67267,10.62948,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kvalsund',70.5025,23.988056,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ås',63.05,11.65,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Reine',67.93372,13.08914,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brattvåg',62.6,6.45,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Støren',63.03718,10.28558,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Meldal',63.04613,9.71033,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Larsnes',62.216667,5.6,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lena',60.666667,10.8,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sørland',67.666667,12.7,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Steinshamn',62.783333,6.483333,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skjervøy',70.033333,20.983333,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skarnes',60.25,11.683333,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dokka',60.833333,10.083333,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Masfjordnes',60.8,5.3,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kvinesdal',58.316667,6.95,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bruhagen',63.05332,7.63226,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Isdalstø',60.555556,5.269167,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Falkhytta',62.80578,6.88576,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Flekkefjord',58.283333,6.683333,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kolvereid',64.85,11.6,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Øksfjord',70.239167,22.371389,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oteren',69.255384,19.881581,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Honningsvåg',70.983333,25.983333,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sunndalsøra',62.666667,8.55,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tynset',62.283333,10.783333,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Granvin',60.55,6.716667,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sørreisa',69.138732,18.17983,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Årnes',63.966667,10.233333,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hareid',62.366667,6.033333,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tromsø',69.666667,18.966667,'Norway','NO','Troms','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Terråk',65.083333,12.416667,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lom',61.833333,8.55,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trysil',61.316667,12.266667,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bardu',68.86563,18.34735,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bogen',68.52619,16.9945,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rong',60.513333,4.903333,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Burfjord',69.933333,22.05,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Koppang',61.566667,11.066667,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eidsvåg',62.781944,8.071111,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eidsvoll',60.316667,11.233333,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sagstua',60.38846,11.53763,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Flå',60.416667,9.466667,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rjukan',59.883333,8.6,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sveio',59.544722,5.349167,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karasjok',69.45,25.5,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vikevåg',59.098056,5.698056,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vågaholmen',66.70914,13.2693,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ramberg',68.083333,13.233333,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hamnvik',68.783333,17.183333,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Midsund',62.683333,6.683333,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skien',59.2,9.6,'Norway','NO','Telemark','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Enebakk',59.756127,11.136371,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Birkeland',58.333333,8.233333,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Flisa',60.60781,12.05206,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Raufoss',60.716667,10.616667,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ørnes',66.866667,13.7,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krokstadøra',63.4,9.5,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Olderdalen',69.616667,20.533333,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eivinvik',60.983333,5.066667,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Høyanger',61.216667,6.083333,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Manger',60.641667,5.039167,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Balestrand',61.2,6.533333,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Liabøen',63.116667,8.3,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Inndyr',67.033333,14.033333,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Breivikbotn',70.592644,22.297676,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tana Bru',70.20238,28.17331,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hemsedal',60.866667,8.566667,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rømskog',59.712676,11.841647,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dale',61.366667,5.416667,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Røyken',59.7475,10.393611,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bryne',58.733333,5.65,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Os',62.5,11.2,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hol',60.62003,8.297178,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rygge',59.383333,10.716667,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Verdal',63.8,11.483333,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lyngseidet',69.583333,20.216667,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mandal',58.033333,7.45,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sætre',59.681667,10.524722,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Utsira',59.3,4.9,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fagernes',60.983333,9.25,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sandane',61.766667,6.216667,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Heggenes',61.15,9.083333,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Odda',60.066667,6.55,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fetsund',59.933333,11.166667,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Naustdal',61.516667,5.716667,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rissa',63.58324,9.95911,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Våler',59.487374,10.852732,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hobøl',59.598415,10.942048,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Elnesvågen',62.85382,7.15363,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Frekhaug',60.517222,5.246111,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Straumen',67.35,15.6,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tvedestrand',58.624444,8.928611,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ålen',62.85,11.283333,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fauske',67.25,15.4,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grong',64.45,12.333333,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sjøvegan',68.873333,17.864444,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Høylandet',64.62775,12.29996,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kyrksæterøra',63.283333,9.1,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Judaberg',59.183333,5.85,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Norheimsund',60.366667,6.133333,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ulvik',60.566667,6.9,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Berlevåg',70.85,29.1,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Østre Gausdal',61.25812,10.15394,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ålgård',58.766667,5.85,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Orkanger',63.316667,9.866667,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ørje',59.483333,11.65,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Førde',61.45,5.866667,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Årnes',60.15,11.466667,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vestby',59.6,10.75,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Otta',61.766667,9.533333,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Røyse',60.07685,10.19652,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rødberg',60.27107,8.95367,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lampeland',59.83422,9.57586,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vang',61.12448,8.57399,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lauvsnes',64.5,10.916667,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aurlandsvangen',60.90626,7.18635,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gaupne',61.40481,7.29415,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Korgen',66.083333,13.833333,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Spydeberg',59.6,11.083333,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Asker',59.833333,10.433333,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Namsskogan',64.916667,13.166667,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mosjøen',65.833333,13.2,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fredrikstad',59.216667,10.95,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grimstad',58.340556,8.588611,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Langevåg',62.44342,6.18836,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mjøndalen',59.75,10.016667,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fillan',63.6,8.983333,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Uggdal',60.008889,5.512222,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dovre',61.983333,9.25,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Drangedal',59.1,9.066667,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malm',64.066667,11.216667,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stordal',62.38203,6.98608,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leknes',65.1,11.7,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Varhaug',58.616667,5.65,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Konsmo',58.3,7.4,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mo',60.816667,5.8,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bagn',60.816667,9.566667,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kirkenær',60.466667,12.05,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ringebu',61.516667,10.166667,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Øyer',61.26715,10.42444,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Straume',60.35578,5.1196,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Austrheim',60.76443,4.91349,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kinsarvik',60.37583,6.72593,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Voss',60.63182,6.41669,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stord',59.77384,5.49028,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Os',60.18346,5.46663,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Slidre',61.08825,8.98076,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eikelandsosen',60.239444,5.753889,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lesja',62.12123,8.8457,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ørskog',62.47886,6.81155,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bykle',59.35,7.333333,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bygland',58.85,7.85,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skodje',62.516667,6.716667,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Storsteinnes',69.233333,19.25,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lonevåg',60.533333,5.5,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Evenskjer',68.583333,16.566667,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tennevoll',68.75,17.8,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marnardal',58.21242,7.51168,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sandvika',59.891667,10.524722,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Selje',62.049167,5.348056,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Løten',60.816667,11.316667,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nodeland',58.15,7.85,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lensvik',63.516667,9.816667,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skaland',69.45,17.3,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vennesla',58.283333,7.983333,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nittedal',60.022466,10.923943,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Notodden',59.566667,9.283333,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leland',66.066667,12.95,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sauda',59.65,6.333333,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Halden',59.15,11.383333,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fedje',60.781111,4.713056,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aksdal',59.42588,5.42903,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Snåsa',64.25,12.366667,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lærdalsøyri',61.1,7.483333,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Myre',68.9,15.083333,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fyresdal',59.18849,8.08974,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Klæbu',63.29886,10.48054,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vestnes',62.633333,7.083333,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarpsborg',59.283333,11.116667,'Norway','NO','Østfold','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Seljord',59.483333,8.616667,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Åndalsnes',62.566667,7.7,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sand',59.48234,6.27883,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gjerdrum',60.083333,11.1,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Berkåk',62.833333,10.0,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jondal',60.283333,6.283333,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tonstad',58.666667,6.716667,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trofors',65.566667,13.416667,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Farsund',58.083333,6.8,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sande',61.333333,5.8,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Florø',61.6,5.0,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mysen',59.55,11.333333,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Etne',59.666667,5.933333,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eide',62.916667,7.433333,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kautokeino',68.983333,23.133333,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brumunddal',60.883333,10.933333,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kristiansund',63.116667,7.75,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Botngard',63.766667,9.816667,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fosnavåg',62.35,5.65,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nordli',64.46533,13.59341,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Meråker',63.433333,11.75,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sola',58.883333,5.6,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Svelgen',61.766667,5.3,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jessheim',60.15,11.183333,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kviteseid',59.4,8.5,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Røst',67.516667,12.116667,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Froland',58.533333,8.65,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ås',59.666667,10.8,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eidfjord',60.466667,7.083333,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skjærhalden',59.033333,11.033333,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lakselv',70.05,24.933333,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Siljan',59.3,9.7,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hønefoss',60.166667,10.3,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rakkestad',59.433333,11.35,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Måløy',61.938333,5.113333,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hardbakke',61.083333,4.85,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mehamn',71.033333,27.85,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aure',63.266667,8.533333,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vinstra',61.6,9.75,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ranemsletta',64.5,11.95,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leknes',68.14524,13.59928,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Straumsjøen',68.6944,14.4718,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vangsvik',69.166667,17.733333,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Risør',58.716667,9.233333,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tolga',62.416667,11.0,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dalen',59.45,8.0,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leinesfjord',67.77654,15.0147,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Træna',66.50167,12.09632,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stange',60.716667,11.183333,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Porsgrunn',59.15,9.666667,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nesbyen',60.566667,9.1,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nordfjordeid',61.9,6.0,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fitjar',59.9175,5.322778,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Båtsfjord',70.632222,29.699722,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prestfoss',60.033333,9.633333,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dun',64.666667,11.25,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Melhus',63.283333,10.266667,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hopen',63.466667,8.016667,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sistranda',63.716667,8.833333,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rindal',63.05,9.216667,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kjøpsvik',68.1025,16.350556,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lier',59.79253,10.25246,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bokn',59.22356,5.44522,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kvitsøy',59.06319,5.41613,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Forsand',58.90242,6.09638,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skotterud',59.983333,12.116667,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hyllestad',61.166667,5.3,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moldjord',67.0,14.583333,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Engerdal',61.75836,11.95937,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bergset',61.8897,11.07732,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jørpeland',59.016667,6.05,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stjørdal',63.47025,10.91215,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sogndal',61.23155,7.10268,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Askvoll',61.34651,5.05971,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hornindal',61.96927,6.52245,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skei',61.57156,6.47895,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stryn',61.916667,6.783333,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lørenskog',59.940794,10.960957,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trøgstad',59.64589,11.294485,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skiptvet',59.460016,11.160108,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Folldal',62.133333,10.05,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Straumen',63.866667,11.3,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hurdal',60.396226,11.027743,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Storebø',60.1,5.233333,'Norway','NO','Hordaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Røros',62.583333,11.4,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nesoddtangen',59.866667,10.65,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ørsta',62.2,6.15,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Åmli',58.783333,8.5,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Havøysund',71.000556,24.696111,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vikøyri',61.083333,6.583333,'Norway','NO','Sogn og Fjordane','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Egersund',58.45,6.0,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vardø',70.366667,31.1,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Solfjellsjøen',66.116667,12.483333,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tingvatn',58.4,7.233333,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moi',58.466667,6.533333,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Elverum',60.883333,11.566667,'Norway','NO','Hedmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Roan',64.17286,10.22503,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Steinsdalen',64.24292,10.69261,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fossby',59.216667,11.7,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Roa',60.283333,10.616667,'Norway','NO','Oppland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Børsa',63.32768,10.06833,'Norway','NO','Sør-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vinje',59.62009,7.84126,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sauland',59.62027,8.92781,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Akkerhaugen',59.39399,9.24708,'Norway','NO','Telemark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vigeland',58.083333,7.3,'Norway','NO','Vest-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oppeid',68.085556,15.611667,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kolbotn',59.811389,10.798333,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lødingen',68.407222,15.991944,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ballangen',68.335278,16.821111,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hattfjelldal',65.59768,13.98925,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ulsteinvik',62.333333,5.883333,'Norway','NO','Møre og Romsdal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gol',60.7,8.95,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Varangerbotn',70.166667,28.55,'Norway','NO','Finnmark','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rollag',60.02268,9.26946,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vikeså',58.633333,6.1,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vikersund',59.983333,10.033333,'Norway','NO','Buskerud','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hol',68.533333,16.4,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moen',69.133333,18.616667,'Norway','NO','Troms','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Levanger',63.75,11.3,'Norway','NO','Nord-Trøndelag','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hjelmeland',59.233333,6.183333,'Norway','NO','Rogaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vegårshei',58.766667,8.8,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lillestrøm',59.95,11.083333,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lillesand',58.252222,8.378333,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vevelstad',65.716667,12.466667,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Askim',59.583333,11.166667,'Norway','NO','Østfold','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sortland',68.701944,15.423889,'Norway','NO','Nordland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valle',59.2,7.533333,'Norway','NO','Aust-Agder','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fjerdingby',59.925506,11.086483,'Norway','NO','Akershus','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kleppestø',60.409444,5.228611,'Norway','NO','Hordaland','minor',NULL,NULL);
