INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Katowice',50.258415,19.027545,'Poland','PL','Śląskie','admin',2746000,308724);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Warsaw',52.25,21.0,'Poland','PL','Mazowieckie','primary',1707000,1702139);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Łódź',51.75,19.466667,'Poland','PL','Łódzkie','admin',758000,758000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kraków',50.057531,19.980216,'Poland','PL','Małopolskie','admin',756000,755050);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gdańsk',54.36085,18.658291,'Poland','PL','Pomorskie','admin',740000,455830);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bytom',50.348017,18.932822,'Poland','PL','Śląskie','minor',662247,189186);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wrocław',51.1,17.033333,'Poland','PL','Dolnośląskie','admin',634893,610049);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Poznań',52.416667,16.966667,'Poland','PL','Wielkopolskie','admin',623997,570352);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gliwice',50.297612,18.676583,'Poland','PL','Śląskie','minor',507670,198835);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Szczecin',53.439531,14.593891,'Poland','PL','Zachodniopomorskie','admin',407811,372672);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bydgoszcz',53.127062,18.019987,'Poland','PL','Kujawsko-Pomorskie','admin',366452,365992);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lublin',51.25,22.566667,'Poland','PL','Lubelskie','admin',360044,355958);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gdynia',54.5,18.55,'Poland','PL','Pomorskie','minor',314664,253730);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Białystok',53.133333,23.15,'Poland','PL','Podlaskie','admin',291855,285590);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rzeszów',50.037246,22.004949,'Poland','PL','Podkarpackie','admin',245686,158382);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kielce',50.873686,20.630266,'Poland','PL','Świętokrzyskie','admin',215733,208598);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Olsztyn',53.779949,20.494162,'Poland','PL','Warmińsko-Mazurskie','admin',186670,171803);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Opole',50.672115,17.925325,'Poland','PL','Opolskie','admin',131412,127676);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Elbląg',54.1522,19.408841,'Poland','PL','Warmińsko-Mazurskie','minor',127558,121106);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zielona Góra',51.939345,15.505772,'Poland','PL','Lubuskie','admin',118433,109298);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Koszalin',54.193589,16.184916,'Poland','PL','Zachodniopomorskie','minor',107450,107450);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Twierdza Grudziadz',53.5,18.75,'Poland','PL','Kujawsko-Pomorskie',NULL,102443,99486);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Inowrocław',52.798858,18.263875,'Poland','PL','Kujawsko-Pomorskie','minor',79007,77597);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ełk',53.826478,22.365416,'Poland','PL','Warmińsko-Mazurskie','minor',55769,46856);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nakło nad Notecią',53.141874,17.602976,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ustrzyki Dolne',49.430858,22.584761,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sępólno Krajeńskie',53.452046,17.539826,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gorlice',49.658084,21.159693,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nowy Targ',49.477579,20.029205,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nowy Tomyśl',52.316477,16.133629,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Łask',51.588037,19.125084,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bolesławiec',51.264183,15.569703,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Olecko',54.036431,22.508387,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Biała Podlaska',52.03129,23.121418,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Polkowice',51.50618,16.072623,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nisko',50.518509,22.144659,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brzozów',49.695431,22.020189,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ruda Śląska',50.307941,18.855156,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bełchatów',51.366503,19.374485,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brodnica',53.25,19.4,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tychy',50.137167,18.96641,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oborniki',52.647394,16.814061,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Choszczno',53.169051,15.420537,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lesko',49.47113,22.329802,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Będzin',50.319705,19.145249,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hrubieszów',50.805019,23.892508,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sztum',53.920268,19.031101,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Świętochłowice',50.292455,18.914684,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Strzelin',50.783958,17.066399,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zwoleń',51.355901,21.582678,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Głogów',51.663026,16.075688,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grodzisk Mazowiecki',52.106384,20.623141,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pruszków',52.162608,20.812948,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radomsko',51.066749,19.454424,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Police',53.542062,14.555212,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rypin',53.067489,19.415666,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ożarów Mazowiecki',52.233333,20.85,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wodzisław Śląski',50.010983,18.455074,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zabrze',50.306355,18.783333,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pajęczno',51.144491,18.996116,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sokółka',53.407154,23.502278,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ostrzeszów',51.425661,17.930084,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pszczyna',49.976483,18.947323,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jarocin',51.97076,17.498773,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lubań',51.120143,15.287678,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lubaczów',50.159707,23.122425,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bielsko-Biała',49.822449,19.046863,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kamień Pomorski',53.968946,14.772834,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Szydłowiec',51.224862,20.858566,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żagań',51.615804,15.314769,'Poland','PL','Lubuskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cieszyn',49.74634,18.636093,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jaworzno',50.206025,19.270062,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lidzbark Warmiński',54.128687,20.57807,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Węgrów',52.401958,22.016667,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Czarnków',52.902144,16.564126,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wieruszów',51.298167,18.157387,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kętrzyn',54.079293,21.370583,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stargard Szczeciński',53.341761,15.052135,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wadowice',49.884086,19.491489,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gniezno',52.53944,17.611262,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Słupca',52.290352,17.873101,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Opatów',50.800952,21.423434,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wejherowo',54.605211,18.235514,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Łęczna',51.304588,22.883235,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Białobrzegi',51.646641,20.950269,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Olkusz',50.27916,19.563162,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zamość',50.724679,23.260629,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lipno',52.845174,19.182561,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Łańcut',50.06819,22.228955,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Parczew',51.642884,22.908449,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Limanowa',49.704128,20.42245,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tarnowskie Góry',50.448546,18.851463,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kłobuck',50.90298,18.937036,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pyrzyce',53.145647,14.892897,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tuchola',53.586661,17.86059,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Starachowice',51.051914,21.088273,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kartuzy',54.333333,18.2,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lubartów',51.462888,22.607754,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sanok',49.558958,22.202951,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wysokie Mazowieckie',52.917069,22.511442,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nowy Dwór Gdański',54.21305,19.117714,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nowy Dwór Mazowiecki',52.430356,20.715855,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Piła',53.154997,16.746074,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nowe Miasto Lubawskie',53.422694,19.592512,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żyrardów',52.055392,20.441451,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sucha Beskidzka',49.737591,19.587148,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gostyń',51.882468,17.012255,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chełm',51.135831,23.482511,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sochaczew',52.233333,20.25,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leżajsk',50.260132,22.421242,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mogilno',52.660492,17.956662,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sierpc',52.852857,19.668927,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ryki',51.623966,21.933517,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Racibórz',50.090569,18.207455,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Staszów',50.56342,21.168666,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chełmno',53.35,18.433333,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dąbrowa Górnicza',50.326206,19.224381,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Garwolin',51.897384,21.614392,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krasnystaw',50.985028,23.172715,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kozienice',51.583602,21.549937,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mysłowice',50.236209,19.141123,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zgorzelec',51.153659,15.008839,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Słupsk',54.467761,17.027457,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Turek',52.017722,18.50559,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żnin',52.853617,17.716677,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skierniewice',51.966667,20.15,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sejny',54.107505,23.34792,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pisz',53.627444,21.812528,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wieluń',51.221009,18.566548,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Świecie',53.409527,18.44512,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stalowa Wola',50.551635,22.051089,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tczew',54.092291,18.79467,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radzyń Podlaski',51.783333,22.616667,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Świdnik',51.22057,22.700337,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Białogard',54.00937,15.986562,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Końskie',51.191432,20.408217,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zgierz',51.84469,19.408752,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krapkowice',50.474689,17.965447,'Poland','PL','Opolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Legnica',51.210062,16.161898,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Legionowo',52.401488,20.926636,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bartoszyce',54.250693,20.814911,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chrzanów',50.139468,19.40626,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Słubice',52.355255,14.564826,'Poland','PL','Lubuskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Strzelce Krajeńskie',52.876306,15.5326,'Poland','PL','Lubuskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nidzica',53.360936,20.426476,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Głubczyce',50.202034,17.829379,'Poland','PL','Opolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Włoszczowa',50.852583,19.966843,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skarżysko-Kamienna',51.117238,20.895717,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalisz',51.76109,18.091018,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Opole Lubelskie',51.148001,21.969903,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Międzychód',52.599017,15.890664,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Olesno',50.876976,18.420937,'Poland','PL','Opolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Działdowo',53.239581,20.170041,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mielec',50.286188,21.432657,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ostrów Mazowiecka',52.803342,21.895544,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pułtusk',52.704141,21.083007,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kraśnik',50.922758,22.22648,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Miechów',50.356529,20.030126,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Konin',52.208577,18.254103,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Góra',51.668392,16.538039,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żory',50.044976,18.694315,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ciechanów',52.878352,20.618754,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Myślenice',49.831956,19.9441,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Myślibórz',52.92174,14.863315,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lubin',51.400825,16.203381,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tarnobrzeg',50.572007,21.684761,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Piotrków Trybunalski',51.410445,19.694952,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gryfice',53.91624,15.198219,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gryfino',53.253865,14.490097,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dzierżoniów',50.732045,16.648718,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grudziądz',53.483333,18.774123,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Płock',52.55,19.7,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Przasnysz',53.020284,20.882391,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Goleniów',53.563753,14.830032,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ząbkowice Śląskie',50.591954,16.818407,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Włodawa',51.55,23.55,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Opoczno',51.375821,20.286737,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rybnik',50.092076,18.547479,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jasło',49.743718,21.47095,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trzebnica',51.309886,17.062849,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maków Mazowiecki',52.866667,21.1,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Proszowice',50.192241,20.291,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chojnice',53.695062,17.566093,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Przemyśl',49.782476,22.79228,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sieradz',51.595347,18.725345,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Łobez',53.638794,15.62231,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mrągowo',53.866667,21.3,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lipsko',51.158672,21.648668,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Świnoujście',53.909148,14.240035,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nysa',50.47226,17.33618,'Poland','PL','Opolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Września',52.323234,17.569913,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sopot',54.434676,18.57076,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kwidzyn',53.724949,18.931137,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ostrołęka',53.086206,21.575663,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brzeg',50.857495,17.46976,'Poland','PL','Opolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Środa Wielkopolska',52.227622,17.279907,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Środa Śląska',51.164565,16.593952,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lębork',54.539214,17.750121,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Giżycko',54.03811,21.764411,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sokołów Podlaski',52.407477,22.251923,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zakopane',49.296247,19.956785,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żuromin',53.067232,19.911376,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Łęczyca',52.059352,19.20184,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Myszków',50.575202,19.324607,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kluczbork',50.97429,18.213765,'Poland','PL','Opolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kolbuszowa',50.241504,21.769935,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Starogard Gdański',53.968898,18.535355,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hajnówka',52.743281,23.581223,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bytów',54.176362,17.487638,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Otwock',52.118856,21.308008,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dębica',50.052379,21.414763,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Włocławek',52.651435,19.072755,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malbork',54.03596,19.03452,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Przeworsk',50.059053,22.49486,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wołów',51.339044,16.646788,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kościerzyna',54.124787,17.972062,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jelenia Góra',50.89828,15.729929,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ropczyce',50.05257,21.609053,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wschowa',51.805426,16.317381,'Poland','PL','Lubuskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Międzyrzecz',52.447891,15.581652,'Poland','PL','Lubuskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kazimierza Wielka',50.265426,20.493057,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krotoszyn',51.698677,17.437383,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Częstochowa',50.796455,19.124088,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gostynin',52.429429,19.46628,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rawa Mazowiecka',51.764368,20.254933,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ostrów Wielkopolski',51.649762,17.808934,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grójec',51.862518,20.867569,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Łowicz',52.113739,19.948742,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Świdwin',53.776279,15.775524,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bieruń',50.091064,19.090982,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Siedlce',52.168215,22.277296,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Łomża',53.173552,22.06538,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Busko-Zdrój',50.466667,20.716667,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jastrzębie-Zdrój',49.933639,18.601372,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Golub-Dobrzyń',53.109425,19.054212,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zambrów',52.985607,22.242249,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brzesko',49.970044,20.607661,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wągrowiec',52.811659,17.207376,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tomaszów Lubelski',50.453239,23.414238,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tomaszów Mazowiecki',51.538614,20.017606,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Suwałki',54.099444,22.933056,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rawicz',51.611313,16.861194,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chorzów',50.305817,18.974203,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wolsztyn',52.112706,16.12361,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pruszcz Gdański',54.26121,18.648054,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Szczecinek',53.707908,16.699373,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grajewo',53.648062,22.459669,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zduńska Wola',51.59741,18.931347,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wałbrzych',50.771407,16.28432,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Płońsk',52.622238,20.37532,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bielsk Podlaski',52.770017,23.190889,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zawiercie',50.488242,19.431832,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sulęcin',52.443562,15.118347,'Poland','PL','Lubuskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Augustów',53.844711,22.980133,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wołomin',52.346753,21.239244,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radziejów',52.622649,18.528425,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jawor',51.051317,16.193471,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Biłgoraj',50.53583,22.727577,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Piaseczno',52.070345,21.027177,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gorzów Wielkopolski',52.73679,15.228775,'Poland','PL','Lubuskie','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Puck',54.718542,18.41085,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mikołów',50.17103,18.904098,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sosnowiec',50.272243,19.155039,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tarnów',50.006105,20.95527,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gołdap',54.309055,22.303898,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Węgorzewo',54.215669,21.737202,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kamienna Góra',50.783136,16.030371,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wieliczka',49.984057,20.062219,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mława',53.116667,20.383333,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Namysłów',51.075035,17.714347,'Poland','PL','Opolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Siemianowice Śląskie',50.304126,19.035834,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Siemiatycze',52.42719,22.862311,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nowa Sól',51.803937,15.715998,'Poland','PL','Lubuskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Milicz',51.526373,17.276928,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Piekary Śląskie',50.384664,18.944183,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jędrzejów',50.640023,20.305868,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radom',51.400963,21.15809,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kępno',51.278425,17.985831,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kędzierzyn-Koźle',50.35,18.2,'Poland','PL','Opolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pińczów',50.520961,20.526694,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bochnia',49.97215,20.426816,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oława',50.942078,17.299643,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ostrowiec Świętokrzyski',50.939932,21.387944,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kościan',52.088293,16.648657,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kołobrzeg',54.175112,15.591352,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leszno',51.848268,16.57022,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brzeziny',51.800545,19.749864,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prudnik',50.323175,17.576214,'Poland','PL','Opolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chodzież',52.993089,16.91405,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oświęcim',50.036838,19.230829,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żywiec',49.686713,19.194226,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aleksandrów Kujawski',52.877639,18.703163,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dąbrowa Tarnowska',50.174915,20.990776,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mińsk Mazowiecki',52.181875,21.565981,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Puławy',51.416667,21.966667,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oleśnica',51.207733,17.386545,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ostróda',53.699585,19.962986,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Poddębice',51.893139,18.956442,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sławno',54.361546,16.67801,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wąbrzeźno',53.280183,18.948288,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jarosław',50.016381,22.677813,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lubliniec',50.672289,18.68672,'Poland','PL','Śląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Łuków',51.928998,22.379556,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nowy Sącz',49.621766,20.697053,'Poland','PL','Małopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krosno Odrzańskie',52.052902,15.100955,'Poland','PL','Lubuskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pleszew',51.895386,17.782928,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Toruń',53.035831,18.604844,'Poland','PL','Kujawsko-Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Strzyżów',49.872663,21.797049,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wyszków',52.596407,21.457539,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Szamotuły',52.61267,16.581905,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wałcz',53.277869,16.471218,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Świdnica',50.841705,16.479066,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grodzisk Wielkopolski',52.227622,16.365335,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Strzelce Opolskie',50.513404,18.305401,'Poland','PL','Opolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kolno',53.409314,21.932665,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Koło',52.207244,18.631954,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Iława',53.586851,19.560983,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Szczytno',53.562589,20.987474,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mońki',53.404957,22.79791,'Poland','PL','Podlaskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Człuchów',53.672639,17.361185,'Poland','PL','Pomorskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Świedbodzin',52.247626,15.532817,'Poland','PL','Lubuskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Śrem',52.088712,17.0173,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Złotoryja',51.123612,15.915771,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sandomierz',50.685808,21.738864,'Poland','PL','Świętokrzyskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Złotów',53.361739,17.045241,'Poland','PL','Wielkopolskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lwówek Śląski',51.108956,15.582667,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kutno',52.228954,19.361672,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Braniewo',54.379722,19.82,'Poland','PL','Warmińsko-Mazurskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Łosice',52.211567,22.714071,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krosno',49.688663,21.770579,'Poland','PL','Podkarpackie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pabianice',51.655351,19.345602,'Poland','PL','Łódzkie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kłodzko',50.436362,16.653612,'Poland','PL','Dolnośląskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Przysucha',51.359529,20.626215,'Poland','PL','Mazowieckie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Janów Lubelski',50.706673,22.412479,'Poland','PL','Lubelskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Żary',51.638165,15.141717,'Poland','PL','Lubuskie','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Drawsko Pomorskie',53.529754,15.80987,'Poland','PL','Zachodniopomorskie','minor',NULL,NULL);
