INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lisbon',38.716667,-9.133333,'Portugal','PT','Lisboa','primary',2812000,517802);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Picotos',41.192402,-8.619816,'Portugal','PT','Porto',NULL,1337000,249633);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Braga',41.550323,-8.420052,'Portugal','PT','Braga','admin',826833,181819);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Funchal',32.633333,-16.9,'Portugal','PT','Madeira','admin',204767,100847);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Setúbal',38.533333,-8.9,'Portugal','PT','Setúbal','admin',117974,117110);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Copeira',40.176915,-8.424018,'Portugal','PT','Coimbra',NULL,106582,89131);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ponta Delgada',37.733333,-25.666667,'Portugal','PT','Azores','admin',61526,20056);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Portimão',37.136636,-8.539796,'Portugal','PT','Faro','minor',61226,38487);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Évora',38.566667,-7.9,'Portugal','PT','Évora','admin',55620,55620);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aveiro',40.644269,-8.645535,'Portugal','PT','Aveiro','admin',54162,54162);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leiria',39.747724,-8.804995,'Portugal','PT','Leiria','admin',45112,45112);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Faro',37.019367,-7.932229,'Portugal','PT','Faro','admin',41355,21163);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Beja',38.015064,-7.863227,'Portugal','PT','Beja','admin',35854,21658);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bragança',41.805817,-6.757189,'Portugal','PT','Bragança','admin',34375,34375);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Castelo Branco',39.822191,-7.490869,'Portugal','PT','Castelo Branco','admin',33479,33479);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Guarda',40.537328,-7.265749,'Portugal','PT','Guarda','admin',32111,32111);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santarém',39.233333,-8.683333,'Portugal','PT','Santarém','admin',29385,29385);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Viseu',40.661014,-7.909714,'Portugal','PT','Viseu','admin',26364,26364);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Covilhã',40.286011,-7.503961,'Portugal','PT','Castelo Branco','minor',24828,17610);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Marim',41.304961,-7.779743,'Portugal','PT','Vila Real',NULL,17001,17001);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Portalegre',39.297178,-7.430151,'Portugal','PT','Portalegre','admin',15581,15581);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Viana do Castelo',41.693234,-8.832869,'Portugal','PT','Viana do Castelo','admin',15555,15555);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Angra do Heroísmo',38.65,-27.216667,'Portugal','PT','Azores',NULL,12045,10228);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Portela',38.533333,-28.666667,'Portugal','PT','Azores',NULL,6611,6572);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lagos',37.101782,-8.674242,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Paredes de Coura',41.910125,-8.560938,'Portugal','PT','Viana do Castelo','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('São João da Pesqueira',41.148051,-7.404888,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('São João da Madeira',40.900956,-8.499744,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fornos de Algodres',40.628072,-7.540638,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Castelo de Paiva',41.063007,-8.264696,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Portel',38.30697,-7.702435,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Porto',41.149606,-8.610993,'Portugal','PT','Porto','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sertã',39.808461,-8.098829,'Portugal','PT','Castelo Branco','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila do Bispo',37.083172,-8.911438,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fronteira',39.056291,-7.648679,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alfândega da Fé',41.343149,-6.961124,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Celorico da Beira',40.637232,-7.39037,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alcoutim',37.474317,-7.472282,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arronches',39.122417,-7.286192,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Amarante',41.272711,-8.082455,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tabuaço',41.116147,-7.567934,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gouveia',40.494455,-7.592145,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aguiar da Beira',40.817264,-7.544307,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Idanha-a-Nova',39.923157,-7.240819,'Portugal','PT','Castelo Branco','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ribeira de Pena',41.52147,-7.802372,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Seia',40.415099,-7.708586,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rio Maior',39.337325,-8.939063,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Condeixa-a-Nova',40.115733,-8.498336,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mação',39.555734,-7.994215,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lousada',41.278223,-8.279926,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trancoso',40.783291,-7.350157,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Estarreja',40.756482,-8.572074,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moita',38.650779,-8.990383,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ponte de Lima',41.767188,-8.583926,'Portugal','PT','Viana do Castelo','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Guimarães',41.444435,-8.296189,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sobral de Monte Agraço',39.019579,-9.150809,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Seixal',38.64008,-9.101412,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Almeirim',39.209028,-8.616426,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cantanhede',40.346708,-8.594195,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Elvas',38.881502,-7.162817,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ponte da Barca',41.804509,-8.415541,'Portugal','PT','Viana do Castelo','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Golegã',39.40474,-8.48625,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Anadia',40.438409,-8.43352,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moura',38.140095,-7.44856,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Avis',39.05391,-7.891556,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Águeda',40.577205,-8.444418,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valongo',41.195007,-8.51027,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Caminha',41.874874,-8.837321,'Portugal','PT','Viana do Castelo','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ourique',37.653897,-8.225687,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sardoal',39.535994,-8.161413,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila do Conde',41.354811,-8.743397,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alijó',41.276781,-7.474883,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Monchique',37.317748,-8.555294,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cabeceiras de Basto',41.514312,-7.989415,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aljezur',37.319152,-8.803305,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Castanheira de Pêra',40.007169,-8.210484,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Melgaço',42.113371,-8.260161,'Portugal','PT','Viana do Castelo','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gavião',39.464431,-7.934494,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Monforte',39.053297,-7.437582,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Viçosa',38.777696,-7.417927,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Almodôvar',37.512792,-8.060077,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Redondo',38.648716,-7.547082,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Nova de Cerveira',41.941184,-8.742304,'Portugal','PT','Viana do Castelo','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mafra',38.937933,-9.327565,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lousã',40.111911,-8.24703,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Amadora',38.759711,-9.239708,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pinhel',40.774029,-7.06675,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Estremoz',38.844316,-7.585854,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Penamacor',40.168946,-7.169867,'Portugal','PT','Castelo Branco','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Penalva do Castelo',40.676273,-7.698391,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Crato',39.287571,-7.645494,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nelas',40.532157,-7.851525,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aljustrel',37.877594,-8.165159,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Esposende',41.536098,-8.782011,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alcochete',38.755335,-8.960861,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sever do Vouga',40.734588,-8.367219,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sesimbra',38.444513,-9.101236,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('São Pedro do Sul',40.75537,-8.072646,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lourinhã',39.233333,-9.316667,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Comba Dão',40.398559,-8.131601,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Entroncamento',39.466667,-8.466667,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Armamar',41.107646,-7.691386,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arcos de Valdevez',41.848912,-8.410905,'Portugal','PT','Viana do Castelo','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Paços de Ferreira',41.276571,-8.376174,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fafe',41.454227,-8.167998,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ponte de Sôr',39.249642,-8.010086,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moimenta da Beira',40.983828,-7.617653,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santa Marta de Penaguião',41.211161,-7.800111,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Murça',41.405997,-7.454846,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sernancelhe',40.898706,-7.493419,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Real',41.30062,-7.744129,'Portugal','PT','Vila Real','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vinhais',41.835094,-7.005007,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alcácer do Sal',38.373258,-8.514436,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ourém',39.641675,-8.591899,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Nova de Gaia',41.133633,-8.617421,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Castelo de Vide',39.414713,-7.454021,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Nova da Barquinha',39.45,-8.433333,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Loulé',37.137722,-8.019684,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lamego',41.097407,-7.809907,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alvaiázere',39.822559,-8.379994,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sátão',40.741775,-7.732855,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Albergaria-a-Velha',40.693185,-8.479936,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Matosinhos',41.18207,-8.689076,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alandroal',38.702005,-7.403094,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Proença-a-Nova',39.752204,-7.923903,'Portugal','PT','Castelo Branco','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lagoa',37.135349,-8.453188,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Montijo',38.706747,-8.973885,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Felgueiras',41.368058,-8.193961,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nazaré',39.602891,-9.068355,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Miranda do Corvo',40.09318,-8.332608,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Penedono',40.988749,-7.393859,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vale de Cambra',40.849701,-8.393892,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Flor',41.309043,-7.153784,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Figueiró dos Vinhos',39.904132,-8.275107,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santiago do Cacém',38.016935,-8.69475,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trofa',41.322784,-8.572016,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Penafiel',41.208348,-8.282847,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Penacova',40.268837,-8.282374,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pedrógão Grande',39.918345,-8.1459,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oleiros',39.918934,-7.913698,'Portugal','PT','Castelo Branco','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sousel',38.952894,-7.675286,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arraiolos',38.723626,-7.984777,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Poiares',40.210256,-8.257464,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Famalicão',41.407967,-8.51978,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Verde',41.647294,-8.43715,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Terras de Bouro',41.717691,-8.30888,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Manteigas',40.402799,-7.539769,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sintra',38.800971,-9.378257,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vizela',41.390962,-8.263888,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Velha de Ródão',39.666667,-7.7,'Portugal','PT','Castelo Branco','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Benavente',38.979192,-8.807591,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maia',41.235739,-8.619897,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Santo Tirso',41.342567,-8.477456,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oeiras',38.691049,-9.310847,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Celorico de Basto',41.387141,-8.00101,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bombarral',39.267231,-9.157952,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Barreiro',38.663137,-9.072395,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Belmonte',40.359303,-7.34869,'Portugal','PT','Castelo Branco','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Montemor-o-Velho',40.172873,-8.686162,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Espinho',41.007628,-8.641251,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oliveira do Hospital',40.361796,-7.86014,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oliveira de Frades',40.733567,-8.174807,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oliveira de Azemeis',40.84101,-8.475554,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oliveira do Bairro',40.514596,-8.493858,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Viana do Alentejo',38.33458,-8.004399,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Carrazeda de Anciães',41.242466,-7.307206,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ovar',40.861753,-8.626014,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Torres Novas',39.481143,-8.539493,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Torres Vedras',39.091089,-9.258602,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cartaxo',39.160221,-8.787408,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mangualde',40.604248,-7.76115,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Nova de Paiva',40.852907,-7.727911,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Paredes',41.204853,-8.33147,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vidigueira',38.209949,-7.800504,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chamusca',39.35722,-8.48151,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trofa',41.487817,-7.961286,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Macedo de Cavaleiros',41.538161,-6.9611,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Resende',41.105822,-7.966497,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Póvoa de Lanhoso',41.577713,-8.268468,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Feira',40.925348,-8.542769,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Azambuja',39.07029,-8.86822,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vieira do Minho',41.632923,-8.142521,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Batalha',39.660252,-8.824751,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alcanena',39.459005,-8.668924,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Palmela',38.569021,-8.901255,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ferreira do Zêzere',39.694064,-8.292131,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arouca',40.930568,-8.24488,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila de Rei',39.67604,-8.145768,'Portugal','PT','Castelo Branco','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tomar',39.601987,-8.409242,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tondela',40.516815,-8.080866,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Constância',39.466667,-8.333333,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Pouca de Aguiar',41.500176,-7.64383,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Almada',38.679018,-9.156904,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Almeida',40.725672,-6.906137,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alvito',38.256109,-7.991584,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Soure',40.05989,-8.626053,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alenquer',39.053151,-9.009282,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mértola',37.643041,-7.661104,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mesão Frio',41.163167,-7.873534,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mourão',38.383562,-7.341888,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valpaços',41.607461,-7.310876,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pombal',39.916738,-8.628474,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mogadouro',41.340203,-6.711347,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Póvoa de Varzim',41.38344,-8.763637,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Baião',41.162735,-8.034704,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mortágua',40.396746,-8.232341,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tábua',40.362074,-8.02936,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cascais',38.69745,-9.423141,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Barcelos',41.538763,-8.615053,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Boticas',41.689874,-7.665938,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sabrosa',41.267017,-7.576007,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Montalegre',41.823569,-7.789714,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gondomar',41.144536,-8.532229,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Freixo de Espada à Cinta',41.090327,-6.806478,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mora',38.943515,-8.164337,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vendas Novas',38.677056,-8.457924,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Nova de Foz Côa',41.083333,-7.2,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Caldas da Rainha',39.403255,-9.138387,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marvão',39.393912,-7.376861,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vimioso',41.584726,-6.52767,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Odivelas',38.795234,-9.187387,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Odemira',37.598106,-8.638886,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Peniche',39.357486,-9.380439,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vagos',40.555998,-8.68175,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marco de Canavezes',41.183887,-8.148641,'Portugal','PT','Porto','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Coruche',38.959546,-8.525235,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Coimbra',40.205642,-8.419551,'Portugal','PT','Coimbra','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Barrancos',38.134462,-6.976042,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Montemor-o-Novo',38.648117,-8.214549,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mêda',40.966352,-7.261634,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Óbidos',39.360551,-9.156696,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Góis',40.157353,-8.110067,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Reguengos de Monsaraz',38.425293,-7.534945,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Torre de Moncorvo',41.174537,-7.05364,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Murtosa',40.736948,-8.637697,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alcobaça',39.552233,-8.977495,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Figueira da Foz',40.150852,-8.861786,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Figueira de Castelo Rodrigo',40.892619,-6.963502,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Abrantes',39.466667,-8.2,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arruda dos Vinhos',38.984106,-9.077463,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fundão',40.140247,-7.501348,'Portugal','PT','Castelo Branco','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tarouca',41.014444,-7.781432,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ílhavo',40.599896,-8.667325,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alpiarça',39.257116,-8.581866,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Albufeira',37.090205,-8.25079,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Penela',40.033333,-8.383333,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valença',42.03104,-8.645953,'Portugal','PT','Viana do Castelo','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Amares',41.630907,-8.351166,'Portugal','PT','Braga','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('São Brás de Alportel',37.1531,-7.887515,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pampilhosa da Serra',40.046198,-7.951824,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tavira',37.127338,-7.648609,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nisa',39.514989,-7.649077,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alter do Chão',39.198712,-7.658298,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Castro Verde',37.698282,-8.085812,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mealhada',40.378063,-8.449912,'Portugal','PT','Aveiro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cuba',38.165436,-7.892402,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vouzela',40.723613,-8.112833,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Franca de Xira',38.955249,-8.98966,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marinha Grande',39.747691,-8.932284,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cinfães',41.071969,-8.089991,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Borba',38.80553,-7.45465,'Portugal','PT','Évora','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mira',40.428924,-8.737462,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Silves',37.189213,-8.438217,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grândola',38.177181,-8.566746,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Campo Maior',39.017742,-7.064967,'Portugal','PT','Portalegre','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ferreira do Alentejo',38.05,-8.033333,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Miranda do Douro',41.496921,-6.273077,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mirandela',41.487385,-7.186949,'Portugal','PT','Bragança','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Chaves',41.740186,-7.468789,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sines',37.956215,-8.869788,'Portugal','PT','Setúbal','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mondim de Basto',41.411566,-7.954414,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Monção',42.078471,-8.481452,'Portugal','PT','Viana do Castelo','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Castro Marim',37.220683,-7.4435,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Castro Daire',40.898399,-7.933805,'Portugal','PT','Viseu','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arganil',40.218261,-8.054029,'Portugal','PT','Coimbra','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Olhão',37.0286,-7.841101,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cadaval',39.242977,-9.103271,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Loures',38.829082,-9.168106,'Portugal','PT','Lisboa','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Salvaterra de Magos',39.027881,-8.793502,'Portugal','PT','Santarém','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Peso da Régua',41.164912,-7.787034,'Portugal','PT','Vila Real','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Serpa',37.945811,-7.597537,'Portugal','PT','Beja','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sabugal',40.351267,-7.091036,'Portugal','PT','Guarda','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ansião',39.911774,-8.435683,'Portugal','PT','Leiria','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vila Real de Santo António',37.194999,-7.417658,'Portugal','PT','Faro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Porto de Mós',39.601911,-8.818389,'Portugal','PT','Leiria','minor',NULL,NULL);
