INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Belgrade',44.818611,20.468056,'Serbia','RS',NULL,'primary',1099000,1099000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Niš',43.323356,21.901779,'Serbia','RS','Niš','admin',250000,210888);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Novi Sad',45.259272,19.829056,'Serbia','RS','Novi Sad','admin',225457,215400);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kragujevac',44.010876,20.909029,'Serbia','RS','Kragujevac','admin',171197,147473);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Subotica',46.100972,19.668233,'Serbia','RS','Subotica','admin',100000,93408);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zrenjanin',45.38182,20.395396,'Serbia','RS','Zrenjanin','admin',64053,64053);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ćuprija',43.928388,21.374491,'Serbia','RS','Ćuprija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krupanj',44.367619,19.36327,'Serbia','RS','Krupanj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arilje',43.754987,20.097004,'Serbia','RS','Arilje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pančevo',44.87131,20.644304,'Serbia','RS','Pančevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Čoka',45.941516,20.146023,'Serbia','RS','Čoka','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bogatić',44.8376,19.480699,'Serbia','RS','Bogatić','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sombor',45.774239,19.115068,'Serbia','RS','Sombor','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šabac',44.753841,19.687569,'Serbia','RS','Šabac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Koceljeva',44.468716,19.82139,'Serbia','RS','Koceljeva','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Požega',43.845852,20.036774,'Serbia','RS','Požega','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kovačica',45.110931,20.623601,'Serbia','RS','Kovačica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lebane',42.917129,21.729449,'Serbia','RS','Lebane','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ljig',44.226611,20.239352,'Serbia','RS','Ljig','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Surčin',44.794368,20.278136,'Serbia','RS','Beograd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Babušnica',43.067962,22.411508,'Serbia','RS','Babušnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aleksinac',43.541667,21.707778,'Serbia','RS','Aleksinac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bojnik',43.014188,21.717967,'Serbia','RS','Bojnik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aranđelovac',44.307663,20.561163,'Serbia','RS','Aranđelovac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bela Crkva',44.901485,21.423394,'Serbia','RS','Bela Crkva','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Doljevac',43.196833,21.833398,'Serbia','RS','Doljevac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stara Pazova',44.986131,20.159731,'Serbia','RS','Stara Pazova','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Užice',43.858185,19.844087,'Serbia','RS','Užice','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lazarevac',44.379722,20.263889,'Serbia','RS','Beograd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Petrovac na Mlavi',44.377283,21.41976,'Serbia','RS','Petrovac na Mlavi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Srbobran',45.548098,19.795377,'Serbia','RS','Srbobran','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Despotovac',44.093202,21.443975,'Serbia','RS','Despotovac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Topola',44.25442,20.682437,'Serbia','RS','Topola','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nova Crnja',45.668517,20.604206,'Serbia','RS','Nova Crnja','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brus',43.384599,21.028883,'Serbia','RS','Brus','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gadžin Han',43.222289,22.033287,'Serbia','RS','Gadžin Han','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prokuplje',43.238315,21.593192,'Serbia','RS','Prokuplje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dimitrovgrad',43.015455,22.77759,'Serbia','RS','Dimitrovgrad','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Boljevac',43.832131,21.960899,'Serbia','RS','Boljevac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Temerin',45.409464,19.89112,'Serbia','RS','Temerin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malo Crniće',44.560257,21.290565,'Serbia','RS','Malo Crniće','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tutin',42.989993,20.333372,'Serbia','RS','Tutin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Plandište',45.229228,21.123827,'Serbia','RS','Plandište','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Blace',43.296964,21.272727,'Serbia','RS','Blace','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zemun',44.840696,20.397853,'Serbia','RS','Beograd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aleksandrovac',43.460895,21.053911,'Serbia','RS','Aleksandrovac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ljubovija',44.189574,19.378486,'Serbia','RS','Ljubovija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kraljevo',43.725908,20.689577,'Serbia','RS','Kraljevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zaječar',43.901871,22.275511,'Serbia','RS','Zaječar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Čačak',43.888017,20.344023,'Serbia','RS','Čačak','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sečanj',45.367638,20.773205,'Serbia','RS','Sečanj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Priboj',43.583611,19.525833,'Serbia','RS','Priboj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Beočin',45.191649,19.724962,'Serbia','RS','Beočin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Irig',45.100148,19.860301,'Serbia','RS','Irig','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Veliko Gradište',44.763811,21.516251,'Serbia','RS','Veliko Gradište','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jagodina',43.97913,21.258311,'Serbia','RS','Jagodina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Novi Kneževac',46.041039,20.09584,'Serbia','RS','Novi Kneževac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Medveđa',42.842007,21.585811,'Serbia','RS','Medveđa','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Smederevo',44.651575,20.925777,'Serbia','RS','Smederevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žagubica',44.197863,21.790196,'Serbia','RS','Žagubica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ražanj',43.674425,21.549205,'Serbia','RS','Ražanj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Loznica',44.531179,19.242668,'Serbia','RS','Loznica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lučani',43.860816,20.138434,'Serbia','RS','Lučani','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gornji Milanovac',44.024504,20.458646,'Serbia','RS','Gornji Milanovac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bačka Palanka',45.251876,19.391649,'Serbia','RS','Bačka Palanka','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Smederevska Palanka',44.365381,20.962273,'Serbia','RS','Smederevska Palanka','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vranje',42.555997,21.900236,'Serbia','RS','Vranje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žabari',44.356169,21.214256,'Serbia','RS','Žabari','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kosjerić',43.998702,19.907859,'Serbia','RS','Kosjerić','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sopot',44.519348,20.575785,'Serbia','RS','Beograd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kučevo',44.476729,21.671183,'Serbia','RS','Kučevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Senta',45.927334,20.078859,'Serbia','RS','Senta','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bajina Bašta',43.970917,19.565524,'Serbia','RS','Bajina Bašta','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vrnjačka Banja',43.622328,20.89561,'Serbia','RS','Vrnjačka Banja','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pirot',43.16165,22.58713,'Serbia','RS','Pirot','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Knić',43.92696,20.719695,'Serbia','RS','Knić','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rekovac',43.860913,21.095774,'Serbia','RS','Rekovac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leskovac',42.997558,21.944496,'Serbia','RS','Leskovac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Golubac',44.652912,21.630772,'Serbia','RS','Golubac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ub',44.457197,20.076242,'Serbia','RS','Ub','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bačka Topola',45.815206,19.636943,'Serbia','RS','Bačka Topola','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bački Petrovac',45.36157,19.591981,'Serbia','RS','Bački Petrovac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Titel',45.206014,20.294882,'Serbia','RS','Titel','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Odžaci',45.50763,19.260601,'Serbia','RS','Odžaci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bač',45.392276,19.236684,'Serbia','RS','Bač','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Čajetina',43.749736,19.714951,'Serbia','RS','Čajetina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Barajevo',44.579011,20.417895,'Serbia','RS','Beograd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Požarevac',44.622213,21.182589,'Serbia','RS','Požarevac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Raška',43.28595,20.613515,'Serbia','RS','Raška','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lapovo',44.187731,21.09687,'Serbia','RS','Lapovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trstenik',43.616944,21.0025,'Serbia','RS','Trstenik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Preševo',42.307058,21.650034,'Serbia','RS','Preševo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vrbas',45.570426,19.647857,'Serbia','RS','Vrbas','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kladovo',44.607292,22.615474,'Serbia','RS','Kladovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ćićevac',43.719967,21.443617,'Serbia','RS','Ćićevac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valjevo',44.271955,19.887437,'Serbia','RS','Valjevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Varvarin',43.719517,21.371223,'Serbia','RS','Varvarin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Apatin',45.67092,18.984344,'Serbia','RS','Apatin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Novi Bečej',45.601466,20.136361,'Serbia','RS','Novi Bečej','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Inđija',45.048162,20.081647,'Serbia','RS','Inđija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vladičin Han',42.708202,22.066365,'Serbia','RS','Vladičin Han','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sokobanja',43.645293,21.869178,'Serbia','RS','Sokobanja','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kruševac',43.58105,21.335174,'Serbia','RS','Kruševac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bosilegrad',42.500482,22.472784,'Serbia','RS','Bosilegrad','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mali Iđoš',45.709191,19.666261,'Serbia','RS','Mali Iđoš','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Petrovaradin',45.245449,19.879344,'Serbia','RS','Novi Sad','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vlasotince',42.965907,22.127178,'Serbia','RS','Vlasotince','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grocka',44.67204,20.715286,'Serbia','RS','Beograd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mali Zvornik',44.399176,19.121431,'Serbia','RS','Mali Zvornik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Majdanpek',44.422847,21.935837,'Serbia','RS','Majdanpek','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Paraćin',43.859155,21.41191,'Serbia','RS','Paraćin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bela Palanka',43.219622,22.314048,'Serbia','RS','Bela Palanka','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kikinda',45.832292,20.468191,'Serbia','RS','Kikinda','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pećinci',44.908889,19.966389,'Serbia','RS','Pećinci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Surdulica',42.690358,22.170416,'Serbia','RS','Surdulica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Opovo',45.052172,20.431343,'Serbia','RS','Opovo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Knjaževac',43.566696,22.25393,'Serbia','RS','Knjaževac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Niška Banja',43.294312,22.009906,'Serbia','RS','Niš','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lajkovac',44.370041,20.164425,'Serbia','RS','Lajkovac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žitište',45.485384,20.550725,'Serbia','RS','Žitište','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Merošina',43.281278,21.721834,'Serbia','RS','Merošina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Svrljig',43.412867,22.125209,'Serbia','RS','Svrljig','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vršac',45.117501,21.298315,'Serbia','RS','Vršac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ivanjica',43.582043,20.228379,'Serbia','RS','Ivanjica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Osečina',44.372836,19.600976,'Serbia','RS','Osečina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vladimirci',44.615776,19.784303,'Serbia','RS','Vladimirci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rača',44.22685,20.978954,'Serbia','RS','Rača','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Svilajnac',44.238271,21.196994,'Serbia','RS','Svilajnac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ada',45.802655,20.128509,'Serbia','RS','Ada','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kula',45.610866,19.527391,'Serbia','RS','Kula','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trgovište',42.3514,22.092091,'Serbia','RS','Trgovište','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žitorađa',43.190209,21.713413,'Serbia','RS','Žitorađa','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bujanovac',42.460618,21.766552,'Serbia','RS','Bujanovac','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alibunar',45.078874,20.968205,'Serbia','RS','Alibunar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kanjiža',46.063472,20.050403,'Serbia','RS','Kanjiža','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Obrenovac',44.653889,20.2,'Serbia','RS','Beograd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Novi Pazar',43.137514,20.514905,'Serbia','RS','Novi Pazar','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kuršumlija',43.139047,21.273508,'Serbia','RS','Kuršumlija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kostolac',44.713559,21.169287,'Serbia','RS','Požarevac','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žabalj',45.374078,20.0707,'Serbia','RS','Žabalj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bečej',45.619602,20.039983,'Serbia','RS','Bečej','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sremski Karlovci',45.202095,19.932455,'Serbia','RS','Sremski Karlovci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sremska Mitrovica',44.976389,19.612222,'Serbia','RS','Sremska Mitrovica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Negotin',44.226389,22.530833,'Serbia','RS','Negotin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prijepolje',43.390327,19.65061,'Serbia','RS','Prijepolje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Batočina',44.154749,21.07991,'Serbia','RS','Batočina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Velika Plana',44.332338,21.075132,'Serbia','RS','Velika Plana','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mladenovac',44.44184,20.697007,'Serbia','RS','Beograd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Crna Trava',42.807114,22.324661,'Serbia','RS','Crna Trava','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mionica',44.252423,20.081707,'Serbia','RS','Mionica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sjenica',43.273545,20.000368,'Serbia','RS','Sjenica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kovin',44.748222,20.976599,'Serbia','RS','Kovin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ruma',45.007858,19.817096,'Serbia','RS','Ruma','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šid',45.127597,19.226675,'Serbia','RS','Šid','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nova Varoš',43.460026,19.811677,'Serbia','RS','Nova Varoš','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bor',44.081885,22.096673,'Serbia','RS','Bor','admin',NULL,NULL);
