INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stockholm',59.333333,18.05,'Sweden','SE','Stockholm','primary',1264000,1253309);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Glöstorp',57.75,11.933333,'Sweden','SE','Västra Götaland',NULL,537797,504084);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malmö',55.6,13.0,'Sweden','SE','Skåne','admin',269349,261548);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Uppsala',59.85,17.633333,'Sweden','SE','Uppsala','admin',133117,127734);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Västerås',59.616667,16.55,'Sweden','SE','Västmanland','admin',107194,93179);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Örebro',59.283333,15.216667,'Sweden','SE','Örebro','admin',98573,93291);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Linköping',58.416667,15.616667,'Sweden','SE','Östergötland','admin',96732,91491);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Helsingborg',56.05,12.7,'Sweden','SE','Skåne','minor',91304,91025);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jönköping',57.783333,14.183333,'Sweden','SE','Jönköping','admin',89780,83202);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Norrköping',58.6,16.183333,'Sweden','SE','Östergötland','minor',88639,82903);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Umeå',63.833333,20.25,'Sweden','SE','Västerbotten','admin',78197,74005);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bärstad',59.333333,13.55,'Sweden','SE','Värmland',NULL,74141,59266);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tunadal',62.414167,17.379444,'Sweden','SE','Västernorrland',NULL,73389,48463);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gävle',60.666667,17.166667,'Sweden','SE','Gävleborg','admin',68635,67836);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Borås',57.716667,12.916667,'Sweden','SE','Västra Götaland','minor',65008,63223);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Växjö',56.883333,14.816667,'Sweden','SE','Kronoberg','admin',59600,46535);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Halmstad',56.671389,12.855556,'Sweden','SE','Halland','admin',55657,55209);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Luleå',65.583333,22.15,'Sweden','SE','Norrbotten','admin',48638,45551);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Östersund',63.183333,14.65,'Sweden','SE','Jämtland','admin',46178,42940);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trollhättan',58.266667,12.3,'Sweden','SE','Västra Götaland','minor',44543,44522);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Borlänge',60.483333,15.416667,'Sweden','SE','Dalarna','minor',39422,38527);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Falun',60.6,15.633333,'Sweden','SE','Dalarna','admin',36477,36477);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalmar',56.666667,16.366667,'Sweden','SE','Kalmar','admin',35024,34744);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kristianstad',56.033333,14.133333,'Sweden','SE','Skåne','minor',32188,21339);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skellefteå',64.766667,20.95,'Sweden','SE','Västerbotten','minor',31311,30839);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Örnsköldsvik',63.3,18.716667,'Sweden','SE','Västernorrland','minor',27749,25063);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nyköping',58.75,17.0,'Sweden','SE','Södermanland','admin',27582,27582);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Visby',57.639617,18.298582,'Sweden','SE','Gotland','admin',22593,21970);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vänersborg',58.366667,12.316667,'Sweden','SE','Västra Götaland','minor',21835,21835);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kirunavaara',67.816667,20.2,'Sweden','SE','Norrbotten',NULL,18154,8450);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fröland',62.616667,17.883333,'Sweden','SE','Västernorrland',NULL,17016,17016);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mariestad',58.7,13.816667,'Sweden','SE','Västra Götaland','minor',14891,14891);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bollnäs',61.35,16.366667,'Sweden','SE','Gävleborg','minor',13398,12145);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Älvsbyn',65.666667,21.0,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Forshaga',59.533333,13.466667,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lomma',55.683333,13.083333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Henån',58.233333,11.683333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kopparberg',59.866667,14.983333,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tibro',58.416667,14.166667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tidaholm',58.183333,13.95,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Broby',56.25,14.083333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Södertälje',59.2,17.616667,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tierp',60.333333,17.5,'Sweden','SE','Uppsala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hammarstrand',63.1,16.35,'Sweden','SE','Jämtland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Motala',58.55,15.05,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hagfors',60.033333,13.65,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Filipstad',59.716667,14.166667,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hallsberg',59.066667,15.116667,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arjeplog',66.048563,17.884984,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arvika',59.666667,12.566667,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tanumshede',58.733333,11.316667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kalix',65.85,23.133333,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hedemora',60.283333,15.983333,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nossebro',58.183333,12.716667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hallstahammar',59.616667,16.216667,'Sweden','SE','Västmanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skurup',55.466667,13.5,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vetlanda',57.433333,15.066667,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ronneby',56.2,15.3,'Sweden','SE','Blekinge','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kungsör',59.416667,16.083333,'Sweden','SE','Västmanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hova',58.866667,14.183333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eksjö',57.666667,14.95,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eslöv',55.833333,13.333333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Höganäs',56.2,12.55,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sölvesborg',56.05,14.55,'Sweden','SE','Blekinge','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Norsjö',64.916667,19.483333,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vaxholm',59.4,18.333333,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Perstorp',56.133333,13.383333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leksand',60.733333,15.016667,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ludvika',60.15,15.183333,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vilhelmina',64.616667,16.65,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alvesta',56.9,14.55,'Sweden','SE','Kronoberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Valdemarsvik',58.2,16.6,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skillingaryd',57.433333,14.083333,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alafors',57.933333,12.083333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tranås',58.05,14.983333,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nykvarn',59.183333,17.433333,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Upplands Väsby',59.516667,17.9,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bjurholm',63.933333,19.216667,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Degerfors',59.233333,14.433333,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sundsvall',62.383333,17.3,'Sweden','SE','Västernorrland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ystad',55.416667,13.816667,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jakobsberg',59.416667,17.833333,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Knivsta',59.716667,17.8,'Sweden','SE','Uppsala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vallentuna',59.533333,18.083333,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Strängnäs',59.383333,17.033333,'Sweden','SE','Södermanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Östhammar',60.266667,18.366667,'Sweden','SE','Uppsala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hofors',60.55,16.283333,'Sweden','SE','Gävleborg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mölndal',57.65,12.016667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Simrishamn',55.55,14.333333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bräcke',62.75,15.416667,'Sweden','SE','Jämtland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vansbro',60.516667,14.216667,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lerum',57.766667,12.266667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Götene',58.533333,13.483333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sollefteå',63.166667,17.266667,'Sweden','SE','Västernorrland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Boden',65.833333,21.7,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ed',58.916667,11.916667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kungsbacka',57.483333,12.066667,'Sweden','SE','Halland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Åstorp',56.133333,12.95,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skärhamn',57.996667,11.556111,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karlskrona',56.166667,15.583333,'Sweden','SE','Blekinge','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mörbylånga',56.516667,16.383333,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tomelilla',55.55,13.95,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vingåker',59.033333,15.866667,'Sweden','SE','Södermanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lysekil',58.283333,11.433333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Säffle',59.133333,12.9,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Norberg',60.066667,15.933333,'Sweden','SE','Västmanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skinnskatteberg',59.833333,15.683333,'Sweden','SE','Västmanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Falkenberg',56.898056,12.501944,'Sweden','SE','Halland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Söderköping',58.483333,16.3,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Surahammar',59.716667,16.216667,'Sweden','SE','Västmanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Munkfors',59.833333,13.533333,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bollebygd',57.666667,12.55,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gagnef',60.583333,15.066667,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hyltebruk',57.0,13.233333,'Sweden','SE','Halland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ödeshög',58.233333,14.65,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Torsås',56.4,16.0,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nynäshamn',58.904444,17.946389,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Djursholm',59.4,18.083333,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Boxholm',58.2,15.05,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bengtsfors',59.033333,12.216667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Båstad',56.432222,12.833333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Österbymo',57.833333,15.266667,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kungsängen',59.483333,17.75,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kungälv',57.866667,11.966667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Älmhult',56.55,14.133333,'Sweden','SE','Kronoberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sorsele',65.53239,17.543098,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Smedjebacken',60.133333,15.416667,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Uddevalla',58.366667,11.933333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oxelösund',58.666667,17.1,'Sweden','SE','Södermanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Överkalix',66.316667,22.833333,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Laholm',56.516667,13.033333,'Sweden','SE','Halland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Svalöv',55.916667,13.1,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sandviken',60.616667,16.766667,'Sweden','SE','Gävleborg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nacka',59.3,18.166667,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Enköping',59.633333,17.066667,'Sweden','SE','Uppsala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Älvdalen',61.233333,14.033333,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Katrineholm',59.0,16.2,'Sweden','SE','Södermanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rättvik',60.883333,15.1,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skoghall',59.333333,13.433333,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sunne',59.833333,13.15,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gislaved',57.3,13.533333,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tumba',59.2,17.816667,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ulricehamn',57.783333,13.416667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Osby',56.366667,13.983333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Högsby',57.166667,16.033333,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Munkedal',58.483333,11.683333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Järpen',63.35,13.483333,'Sweden','SE','Jämtland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lycksele',64.6,18.666667,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ljungby',56.833333,13.933333,'Sweden','SE','Kronoberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vara',58.266667,12.95,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Värnamo',57.183333,14.033333,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Emmaboda',56.633333,15.533333,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nässjö',57.65,14.683333,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Haparanda',65.829729,24.147,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Västerhaninge',59.116667,18.1,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Herrljunga',58.083333,13.033333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tranemo',57.483333,13.35,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Laxå',58.983333,14.616667,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mölnlycke',57.65,12.133333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Storuman',65.1,17.1,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skara',58.366667,13.416667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hudiksvall',61.733333,17.1125,'Sweden','SE','Gävleborg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ljusdal',61.833333,16.1,'Sweden','SE','Gävleborg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Huddinge',59.233333,17.983333,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Töreboda',58.716667,14.133333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Svenljunga',57.5,13.116667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lidingö',59.366667,18.133333,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Solna',59.366667,18.016667,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tyresö',59.233333,18.3,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vännäs',63.916667,19.75,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Örkelljunga',56.283333,13.283333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kil',59.516667,13.316667,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fagersta',60.0,15.783333,'Sweden','SE','Västmanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Åsele',64.166667,17.333333,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Åseda',57.166667,15.333333,'Sweden','SE','Kronoberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Staffanstorp',55.633333,13.216667,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ekerö',59.266667,17.733333,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Norrtälje',59.766667,18.7,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Märsta',59.616667,17.85,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Markaryd',56.433333,13.6,'Sweden','SE','Kronoberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hällefors',59.783333,14.5,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vimmerby',57.666667,15.85,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mönsterås',57.033333,16.433333,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fjugesta',59.166667,14.866667,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Åtvidaberg',58.2,16.0,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kristinehamn',59.333333,14.116667,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arboga',59.4,15.833333,'Sweden','SE','Västmanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Alingsås',57.933333,12.516667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hässleholm',56.15,13.766667,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Edsbyn',61.383333,15.816667,'Sweden','SE','Gävleborg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Strömstad',58.933333,11.183333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Strömsund',63.85,15.583333,'Sweden','SE','Jämtland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Storfors',59.533333,14.266667,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Årjäng',59.383333,12.133333,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karlsborg',58.533333,14.516667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rönninge',59.2,17.733333,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Göteborg',57.716667,11.966667,'Sweden','SE','Västra Götaland','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vadstena',58.45,14.9,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bergsjö',61.983333,17.066667,'Sweden','SE','Gävleborg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karlskoga',59.333333,14.516667,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sollentuna',59.466667,17.9,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Säter',60.35,15.75,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gnosjö',57.366667,13.733333,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gnesta',59.05,17.3,'Sweden','SE','Södermanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bromölla',56.066667,14.466667,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nora',59.516667,15.033333,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gällivare',67.133333,20.7,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Varberg',57.108586,12.266099,'Sweden','SE','Halland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ockelbo',60.883333,16.716667,'Sweden','SE','Gävleborg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Öckerö',57.708097,11.641298,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ängelholm',56.25,12.866667,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vindeln',64.2,19.733333,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Timrå',62.477778,17.306944,'Sweden','SE','Västernorrland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hörby',55.85,13.65,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Höör',55.933333,13.533333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sundbyberg',59.366667,17.966667,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vårgårda',58.033333,12.8,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bjuv',56.083333,12.9,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Svedala',55.5,13.233333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Orsa',61.116667,14.616667,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Piteå',65.333333,21.5,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arvidsjaur',65.583333,19.166667,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aneby',57.833333,14.8,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Falköping',58.166667,13.55,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lund',55.7,13.183333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Olofström',56.266667,14.5,'Sweden','SE','Blekinge','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Habo',57.916667,14.066667,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pajala',67.2,23.366667,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skutskär',60.633333,17.416667,'Sweden','SE','Uppsala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Täby',59.5,18.05,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kävlinge',55.8,13.1,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hultsfred',57.483333,15.833333,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Avesta',60.15,16.2,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ånge',62.516667,15.616667,'Sweden','SE','Västernorrland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malå',65.183333,18.75,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Finspång',58.716667,15.783333,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Borgholm',56.883333,16.65,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gustavsberg',59.316667,18.383333,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mullsjö',57.916667,13.883333,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grästorp',58.333333,12.683333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Åmål',59.05,12.7,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lindesberg',59.583333,15.25,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kinna',57.5,12.683333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sveg',62.033333,14.35,'Sweden','SE','Jämtland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Eskilstuna',59.366667,16.5,'Sweden','SE','Södermanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kumla',59.133333,15.133333,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Köping',59.516667,16.0,'Sweden','SE','Västmanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trelleborg',55.366667,13.166667,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grums',59.316667,13.1,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mellerud',58.7,12.466667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sala',59.916667,16.6,'Sweden','SE','Västmanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Partille',57.733333,12.116667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kramfors',62.933333,17.7925,'Sweden','SE','Västernorrland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sävsjö',57.4,14.666667,'Sweden','SE','Jönköping','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Härnösand',62.636111,17.941111,'Sweden','SE','Västernorrland','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skövde',58.4,13.85,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jokkmokk',66.604995,19.832866,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Askersund',58.883333,14.9,'Sweden','SE','Örebro','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Robertsfors',64.183333,20.85,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kiruna',67.85,20.216667,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stenungsund',58.083333,11.816667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bålsta',59.583333,17.5,'Sweden','SE','Uppsala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tingsryd',56.533333,14.983333,'Sweden','SE','Kronoberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Charlottenberg',59.883333,12.283333,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lidköping',58.5,13.166667,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kungshamn',58.35,11.25,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Heby',59.933333,16.883333,'Sweden','SE','Uppsala','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Färgelanda',58.566667,12.0,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mjölby',58.316667,15.133333,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Åkersberga',59.483333,18.3,'Sweden','SE','Stockholm','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lilla Edet',58.133333,12.133333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Karlstad',59.366667,13.5,'Sweden','SE','Värmland','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lessebo',56.75,15.266667,'Sweden','SE','Kronoberg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Flen',59.066667,16.583333,'Sweden','SE','Södermanland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dorotea',64.266667,16.4,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mora',61.0,14.55,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Arlöv',55.633333,13.066667,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krokom',63.333333,14.45,'Sweden','SE','Jämtland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Svenstavik',62.766667,14.45,'Sweden','SE','Jämtland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malung',60.666667,13.7,'Sweden','SE','Dalarna','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sjöbo',55.633333,13.7,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Landskrona',55.866667,12.833333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nordmaling',63.566667,19.5,'Sweden','SE','Västerbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Västervik',57.75,16.633333,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Övertorneå',66.38658,23.661818,'Sweden','SE','Norrbotten','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nybro',56.75,15.9,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Söderhamn',61.3,17.05,'Sweden','SE','Gävleborg','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kisa',57.983333,15.616667,'Sweden','SE','Östergötland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hjo',58.3,14.283333,'Sweden','SE','Västra Götaland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oskarshamn',57.266667,16.433333,'Sweden','SE','Kalmar','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Torsby',60.133333,13.0,'Sweden','SE','Värmland','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vellinge',55.466667,13.016667,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Klippan',56.133333,13.133333,'Sweden','SE','Skåne','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trosa',58.9,17.55,'Sweden','SE','Södermanland','minor',NULL,NULL);
