INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ljubljana',46.055278,14.514444,'Slovenia','SI','Ljubljana','primary',314807,255115);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maribor',46.554722,15.646667,'Slovenia','SI','Maribor','admin',114228,89056);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šentjernej',45.84,15.336111,'Slovenia','SI','Šentjernej','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šentjur',46.217222,15.3975,'Slovenia','SI','Šentjur','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Poljčane',46.311944,15.579167,'Slovenia','SI','Poljčane','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Podvelka',46.586944,15.330556,'Slovenia','SI','Podvelka','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šentrupert',45.977778,15.095556,'Slovenia','SI','Šentrupert','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Medvode',46.133333,14.433333,'Slovenia','SI','Medvode','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radovljica',46.344444,14.174444,'Slovenia','SI','Radovljica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sveta Trojica v Slovenskih Goricah',46.576667,15.876944,'Slovenia','SI','Sveta Trojica v Slovenskih Goricah','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zgornje Gorje',46.383333,14.083333,'Slovenia','SI','Gorje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zgornje Jezersko',46.383333,14.466667,'Slovenia','SI','Jezersko','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sveta Ana v Slovenskih Goricah',46.649167,15.844167,'Slovenia','SI','Sveta Ana','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Miklavž na Dravskem Polju',46.505833,15.697222,'Slovenia','SI','Miklavž na Dravskem Polju','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Križevci pri Ljutomeru',46.568333,16.138611,'Slovenia','SI','Križevci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gornji Petrovci',46.805278,16.2225,'Slovenia','SI','Gornji Petrovci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Podčetrtek',46.156944,15.598611,'Slovenia','SI','Podčetrtek','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radeče',46.068056,15.183889,'Slovenia','SI','Radeče','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ankaran',45.578611,13.736111,'Slovenia','SI','Ankaran','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Laško',46.151944,15.236389,'Slovenia','SI','Laško','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dobrna',46.3375,15.226389,'Slovenia','SI','Dobrna','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kostanjevica na Krki',45.846111,15.422222,'Slovenia','SI','Kostanjevica na Krki','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trbovlje',46.155,15.053333,'Slovenia','SI','Trbovlje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gorenja Vas',46.107222,14.148056,'Slovenia','SI','Gorenja Vas-Poljane','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Polzela',46.283333,15.066667,'Slovenia','SI','Polzela','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zavrč',46.391667,16.049722,'Slovenia','SI','Zavrč','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brezovica',46.033333,14.4,'Slovenia','SI','Brezovica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šoštanj',46.38,15.048611,'Slovenia','SI','Šoštanj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cankova',46.720833,16.0225,'Slovenia','SI','Cankova','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ajdovščina',45.8875,13.911111,'Slovenia','SI','Ajdovščina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Volčja Draga',45.906944,13.6775,'Slovenia','SI','Renče-Vogrsko','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Borovnica',45.915833,14.363056,'Slovenia','SI','Borovnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Velenje',46.359167,15.110278,'Slovenia','SI','Velenje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Spodnja Hajdina',46.408889,15.846944,'Slovenia','SI','Hajdina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mirna',45.955278,15.061944,'Slovenia','SI','Mirna','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mirna Peč',45.860278,15.083333,'Slovenia','SI','Mirna Peč','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vitanje',46.381667,15.295833,'Slovenia','SI','Vitanje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Markovci',46.383333,15.95,'Slovenia','SI','Markovci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Straža',45.78,15.072778,'Slovenia','SI','Straža','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Metlika',45.647222,15.314167,'Slovenia','SI','Metlika','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Domžale',46.138056,14.597778,'Slovenia','SI','Domžale','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Naklo',46.272778,14.317222,'Slovenia','SI','Naklo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sodražica',45.761111,14.635556,'Slovenia','SI','Sodražica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pivka',45.679444,14.196667,'Slovenia','SI','Pivka','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Solčava',46.419444,14.693611,'Slovenia','SI','Solčava','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Selnica ob Dravi',46.55,15.495,'Slovenia','SI','Selnica ob Dravi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Braslovče',46.289722,15.038889,'Slovenia','SI','Braslovče','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dobrova',46.055,14.417222,'Slovenia','SI','Dobrova-Polhov Gradec','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lukovica pri Domžalah',46.166667,14.7,'Slovenia','SI','Lukovica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vipava',45.846667,13.963056,'Slovenia','SI','Vipava','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Benedikt v Slovenskih Goricah',46.608611,15.888333,'Slovenia','SI','Benedikt','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Celje',46.236111,15.2675,'Slovenia','SI','Celje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radenci',46.647222,16.044167,'Slovenia','SI','Radenci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mokronog',45.934167,15.140833,'Slovenia','SI','Mokronog-Trebelno','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Železniki',46.233333,14.166667,'Slovenia','SI','Železniki','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mežica',46.521389,14.854444,'Slovenia','SI','Mežica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ormož',46.411389,16.154444,'Slovenia','SI','Ormož','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šalovci',46.825,16.298056,'Slovenia','SI','Šalovci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brežice',45.903333,15.591111,'Slovenia','SI','Brežice','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zgornja Kungota',46.639167,15.615556,'Slovenia','SI','Kungota','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gornji Grad',46.295278,14.808333,'Slovenia','SI','Gornji Grad','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Videm',45.85,14.694167,'Slovenia','SI','Dobrepolje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bovec',46.3375,13.552778,'Slovenia','SI','Bovec','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vodice',46.2,14.5,'Slovenia','SI','Vodice','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Odranci',46.586667,16.280278,'Slovenia','SI','Odranci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dol pri Ljubljani',46.088611,14.600833,'Slovenia','SI','Dol pri Ljubljani','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lovrenc na Pohorju',46.540556,15.393056,'Slovenia','SI','Lovrenc na Pohorju','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kobilje',46.684722,16.397778,'Slovenia','SI','Kobilje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Makole',46.317222,15.667222,'Slovenia','SI','Makole','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tolmin',46.186389,13.736111,'Slovenia','SI','Tolmin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Miren',45.895556,13.6075,'Slovenia','SI','Miren-Kostanjevica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nova Vas',45.771667,14.505833,'Slovenia','SI','Bloke','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Postojna',45.776944,14.216667,'Slovenia','SI','Postojna','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Starše',46.465833,15.767222,'Slovenia','SI','Starše','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zreče',46.383333,15.366667,'Slovenia','SI','Zreče','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Slovenj Gradec',46.510278,15.080556,'Slovenia','SI','Slovenj Gradec','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kozje',46.075,15.560278,'Slovenia','SI','Kozje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jesenice',46.430556,14.066944,'Slovenia','SI','Jesenice','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vojnik',46.293333,15.303333,'Slovenia','SI','Vojnik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vitomarci',46.5275,15.939444,'Slovenia','SI','Sveti Andraž v Slovenskih Goricah','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Spodnji Duplek',46.503056,15.745278,'Slovenia','SI','Duplek','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Puconci',46.706667,16.156389,'Slovenia','SI','Puconci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zagorje ob Savi',46.134167,15.001389,'Slovenia','SI','Zagorje ob Savi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tržič',46.366667,14.316667,'Slovenia','SI','Tržič','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Log pri Brezovici',46.016667,14.366667,'Slovenia','SI','Log-Dragomer','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Litija',46.058611,14.8225,'Slovenia','SI','Litija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cerknica',45.793056,14.3625,'Slovenia','SI','Cerknica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Apače',46.697222,15.910556,'Slovenia','SI','Apače','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Komenda',46.203795,14.540652,'Slovenia','SI','Komenda','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Semič',45.646111,15.182222,'Slovenia','SI','Semič','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šmarješke Toplice',45.861961,15.223079,'Slovenia','SI','Šmarješke Toplice','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tišina',46.658056,16.091667,'Slovenia','SI','Tišina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tomaž pri Ormožu',46.484167,16.083611,'Slovenia','SI','Sveti Tomaž','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mengeš',46.166944,14.575,'Slovenia','SI','Mengeš','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Izola',45.536944,13.661944,'Slovenia','SI','Izola','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Beltinci',46.605278,16.240556,'Slovenia','SI','Beltinci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Murska Sobota',46.6625,16.166389,'Slovenia','SI','Murska Sobota','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hrastnik',46.146111,15.081389,'Slovenia','SI','Hrastnik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stari Trg pri Ložu',45.712778,14.469444,'Slovenia','SI','Loška Dolina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žužemberk',45.833889,14.929167,'Slovenia','SI','Žužemberk','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cerkno',46.125556,13.981667,'Slovenia','SI','Cerkno','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trzin',46.133333,14.566667,'Slovenia','SI','Trzin','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lendava',46.561389,16.450556,'Slovenia','SI','Lendava','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lenart v Slovenskih Goricah',46.576111,15.831389,'Slovenia','SI','Lenart','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dornava',46.436667,15.953611,'Slovenia','SI','Dornava','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šempeter pri Gorici',45.9275,13.641111,'Slovenia','SI','Šempeter-Vrtojba','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kobarid',46.248056,13.577222,'Slovenia','SI','Kobarid','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kozina',45.61,13.935556,'Slovenia','SI','Hrpelje-Kozina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trebnje',45.904167,15.021667,'Slovenia','SI','Trebnje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ruše',46.539444,15.515833,'Slovenia','SI','Ruše','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dobrovnik',46.651389,16.3525,'Slovenia','SI','Dobrovnik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Slovenska Bistrica',46.392778,15.574444,'Slovenia','SI','Slovenska Bistrica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tabor',46.236111,15.018333,'Slovenia','SI','Tabor','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Komen',45.815278,13.748333,'Slovenia','SI','Komen','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Škofljica',45.983333,14.576667,'Slovenia','SI','Škofljica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Štore',46.220833,15.313889,'Slovenia','SI','Štore','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cirkulane',46.345291,15.99517,'Slovenia','SI','Cirkulane','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grosuplje',45.955556,14.658889,'Slovenia','SI','Grosuplje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krško',45.953056,15.489444,'Slovenia','SI','Krško','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ilirska Bistrica',45.569722,14.240833,'Slovenia','SI','Ilirska Bistrica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vrhnika',45.966111,14.295556,'Slovenia','SI','Vrhnika','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kanal',46.088611,13.639722,'Slovenia','SI','Kanal','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kidričevo',46.403611,15.791111,'Slovenia','SI','Kidričevo','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šmartno pri Litiji',46.044444,14.844167,'Slovenia','SI','Šmartno pri Litiji','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ljutomer',46.520833,16.1975,'Slovenia','SI','Ljutomer','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Slovenske Konjice',46.336667,15.425833,'Slovenia','SI','Slovenske Konjice','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dolenjske Toplice',45.766667,15.066667,'Slovenia','SI','Dolenjske Toplice','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sežana',45.706944,13.872222,'Slovenia','SI','Sežana','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Luče',46.356111,14.746667,'Slovenia','SI','Luče','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Destrnik',46.500556,15.875,'Slovenia','SI','Destrnik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Škocjan',45.906667,15.291389,'Slovenia','SI','Škocjan','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prevalje',46.546944,14.920833,'Slovenia','SI','Prevalje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Majšperk',46.351667,15.733611,'Slovenia','SI','Majšperk','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moravče',46.136944,14.745,'Slovenia','SI','Moravče','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moravske-Toplice',46.6875,16.225556,'Slovenia','SI','Moravske Toplice','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hodoš',46.823333,16.334167,'Slovenia','SI','Hodoš','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ljubno',46.345556,14.835,'Slovenia','SI','Ljubno','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dobje pri Planini',46.136667,15.408889,'Slovenia','SI','Dobje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šmartno ob Paki',46.333333,15.033333,'Slovenia','SI','Šmartno ob Paki','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Črnomelj',45.571111,15.188889,'Slovenia','SI','Črnomelj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vuzenica',46.596389,15.167222,'Slovenia','SI','Vuzenica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Škofja Loka',46.167222,14.308889,'Slovenia','SI','Škofja Loka','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Idrija',46.002778,14.030556,'Slovenia','SI','Idrija','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ribnica na Pohorju',46.535,15.272778,'Slovenia','SI','Ribnica na Pohorju','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Logatec',45.914444,14.225833,'Slovenia','SI','Logatec','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mozirje',46.339444,14.963333,'Slovenia','SI','Mozirje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gornja Radgona',46.673333,15.992222,'Slovenia','SI','Gornja Radgona','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cerkvenjak',46.570556,15.943611,'Slovenia','SI','Cerkvenjak','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jurovski Dol',46.606389,15.784722,'Slovenia','SI','Sveti Jurij v Slovenskih Goricah','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hrib-Loški Potok',45.701111,14.591111,'Slovenia','SI','Loški Potok','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kostel',45.508421,14.910051,'Slovenia','SI','Kostel','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gorišnica',46.414722,16.013889,'Slovenia','SI','Gorišnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šmarje pri Jelšah',46.227222,15.519167,'Slovenia','SI','Šmarje pri Jelšah','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bistrica ob Sotli',46.058889,15.664167,'Slovenia','SI','Bistrica ob Sotli','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ig',45.960278,14.528889,'Slovenia','SI','Ig','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ribnica',45.738611,14.7275,'Slovenia','SI','Ribnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Novo Mesto',45.7925,15.164722,'Slovenia','SI','Novo Mesto','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nova Gorica',45.961389,13.643611,'Slovenia','SI','Nova Gorica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Črna na Koroškem',46.466667,14.85,'Slovenia','SI','Črna na Koroškem','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Cerklje na Gorenjskem',46.254167,14.488611,'Slovenia','SI','Cerklje na Gorenjskem','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Koper',45.546944,13.729444,'Slovenia','SI','Koper','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sevnica',46.007778,15.315556,'Slovenia','SI','Sevnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Razkrižje',46.521667,16.281111,'Slovenia','SI','Razkrižje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radlje ob Dravi',46.614167,15.226389,'Slovenia','SI','Radlje ob Dravi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Horjul',46.023611,14.299167,'Slovenia','SI','Horjul','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žalec',46.253611,15.1675,'Slovenia','SI','Žalec','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rogatec',46.229444,15.700278,'Slovenia','SI','Rogatec','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kranj',46.241111,14.361667,'Slovenia','SI','Kranj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kranjska Gora',46.483889,13.789444,'Slovenia','SI','Kranjska Gora','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Velika Polana',46.571944,16.346944,'Slovenia','SI','Velika Polana','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pesnica pri Mariboru',46.606944,15.676667,'Slovenia','SI','Pesnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šentilj',46.681667,15.648056,'Slovenia','SI','Šentilj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ptuj',46.421389,15.869722,'Slovenia','SI','Ptuj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Črenšovci',46.574444,16.290556,'Slovenia','SI','Črenšovci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dravograd',46.588056,15.019167,'Slovenia','SI','Dravograd','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rečica ob Savinji',46.316667,14.916667,'Slovenia','SI','Rečica ob Savinji','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sveti Jurij ob Ščavnici',46.569497,16.023473,'Slovenia','SI','Sveti Jurij ob Ščavnici','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Oplotnica',46.387778,15.446667,'Slovenia','SI','Oplotnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Grad',46.8,16.1,'Slovenia','SI','Grad','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vransko',46.243889,14.951389,'Slovenia','SI','Vransko','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žirovnica',46.404722,14.14,'Slovenia','SI','Žirovnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bled',46.369167,14.113611,'Slovenia','SI','Bled','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šenčur',46.245556,14.419722,'Slovenia','SI','Šenčur','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Divača',45.684722,13.970278,'Slovenia','SI','Divača','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Velike Lašče',45.832222,14.636389,'Slovenia','SI','Velike Lašče','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Preddvor',46.3025,14.423056,'Slovenia','SI','Preddvor','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rogašovci',46.8,16.033333,'Slovenia','SI','Rogašovci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rogaška Slatina',46.2375,15.639722,'Slovenia','SI','Rogaška Slatina','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nazarje',46.317573,14.946738,'Slovenia','SI','Nazarje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kamnik',46.219722,14.609444,'Slovenia','SI','Kamnik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mislinja',46.441111,15.195556,'Slovenia','SI','Mislinja','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Videm pri Ptuju',46.368611,15.906389,'Slovenia','SI','Videm','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rače',46.451944,15.681389,'Slovenia','SI','Rače-Fram','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žiri',46.042222,14.107222,'Slovenia','SI','Žiri','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kočevje',45.643333,14.863333,'Slovenia','SI','Kočevje','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Veržej',46.583611,16.165278,'Slovenia','SI','Veržej','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Osilnica',45.529178,14.697899,'Slovenia','SI','Osilnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prebold',46.236944,15.0925,'Slovenia','SI','Prebold','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Središče ob Dravi',46.394167,16.268056,'Slovenia','SI','Središče ob Dravi','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Podlehnik',46.335278,15.88,'Slovenia','SI','Podlehnik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Spodnje Hoče',46.5,15.65,'Slovenia','SI','Hoče-Slivnica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Juršinci',46.484722,15.971389,'Slovenia','SI','Juršinci','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trnovska Vas',46.516667,15.9,'Slovenia','SI','Trnovska Vas','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kuzma',46.836944,16.083333,'Slovenia','SI','Kuzma','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dobrovo',45.996389,13.526389,'Slovenia','SI','Brda','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žetale',46.275,15.793889,'Slovenia','SI','Žetale','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bohinjska Bistrica',46.276944,13.955,'Slovenia','SI','Bohinj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ivančna Gorica',45.938333,14.804444,'Slovenia','SI','Ivančna Gorica','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Piran',45.527778,13.570556,'Slovenia','SI','Piran','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Turnišče',46.627778,16.320278,'Slovenia','SI','Turnišče','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Muta',46.611389,15.166111,'Slovenia','SI','Muta','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ravne na Koroškem',46.543056,14.969167,'Slovenia','SI','Ravne na Koroškem','admin',NULL,NULL);
