INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bratislava',48.15,17.116667,'Slovakia','SK','Bratislavský','primary',423737,373687);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Košice',48.713946,21.258084,'Slovakia','SK','Košický','admin',236563,184070);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prešov',48.998394,21.233934,'Slovakia','SK','Prešovský','admin',94718,76019);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žilina',49.216667,18.733333,'Slovakia','SK','Žilinský','admin',87625,85985);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Banská Bystrica',48.739464,19.153489,'Slovakia','SK','Banskobystrický','admin',82336,79232);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trnava',48.377405,17.587226,'Slovakia','SK','Trnavský','admin',69785,52053);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zvolen',48.57442,19.153236,'Slovakia','SK','Banskobystrický','minor',44502,32051);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vranov nad Topľou',48.888356,21.684794,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bánovce nad Bebravou',48.7213,18.257539,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bytča',49.224045,18.558779,'Slovakia','SK','Žilinský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trebišov',48.628579,21.719535,'Slovakia','SK','Košický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Komárno',48.116667,18.316667,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Trenčín',48.886715,18.047991,'Slovakia','SK','Trenčiansky','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ružomberok',49.074797,19.307509,'Slovakia','SK','Žilinský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zlaté Moravce',48.385528,18.40063,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gelnica',48.855843,20.937125,'Slovakia','SK','Košický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Čadca',49.435031,18.788947,'Slovakia','SK','Žilinský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Michalovce',48.754336,21.919495,'Slovakia','SK','Košický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Snina',48.988566,22.150987,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tvrdošín',49.337004,19.555999,'Slovakia','SK','Žilinský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Banská Štiavnica',48.44858,18.910028,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Brezno',48.804308,19.636313,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sobrance',48.74455,22.181364,'Slovakia','SK','Košický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kežmarok',49.135705,20.433525,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rožňava',48.660085,20.537577,'Slovakia','SK','Košický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Topoľčany',48.563615,18.167119,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Veľký Krtíš',48.210585,19.35043,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Senec',48.219513,17.40043,'Slovakia','SK','Bratislavský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stará Ľubovňa',49.298593,20.686201,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Senica',48.679219,17.366974,'Slovakia','SK','Trnavský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Spišská Nová Ves',48.94464,20.561535,'Slovakia','SK','Košický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nitra',48.309029,18.087314,'Slovakia','SK','Nitriansky','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Medzilaborce',49.272517,21.903322,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Považská Bystrica',49.121534,18.421693,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Svidník',49.308186,21.570295,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pezinok',48.289857,17.266639,'Slovakia','SK','Bratislavský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kysucké Nové Mesto',49.3,18.783333,'Slovakia','SK','Žilinský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Humenné',48.937069,21.91625,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malacky',48.436037,17.02188,'Slovakia','SK','Bratislavský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ilava',48.997687,18.235299,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lučenec',48.332486,19.667077,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Myjava',48.758762,17.56866,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nové Mesto nad Váhom',48.7552,17.830766,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nové Zámky',47.989872,18.166567,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Martin',49.066508,18.92399,'Slovakia','SK','Žilinský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Poprad',49.061442,20.297984,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skalica',48.844901,17.226353,'Slovakia','SK','Trnavský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sabinov',49.103085,21.098796,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Krupina',48.355404,19.064739,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bardejov',49.291754,21.272714,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Revúca',48.683459,20.117341,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Poltár',48.430939,19.794083,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Galanta',48.1913,17.728848,'Slovakia','SK','Trnavský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Šaľa',48.151269,17.880623,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Púchov',49.124942,18.325965,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rimavská Sobota',48.382838,20.022395,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dunajská Streda',47.996525,17.612295,'Slovakia','SK','Trnavský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Detva',48.560688,19.420135,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hlohovec',48.431744,17.803097,'Slovakia','SK','Trnavský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Levice',48.215628,18.607046,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prievidza',48.77446,18.627498,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Stropkov',49.202109,21.652158,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Námestovo',49.407898,19.480324,'Slovakia','SK','Žilinský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Turčianske Teplice',48.862255,18.860479,'Slovakia','SK','Žilinský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žiar nad Hronom',48.591835,18.849577,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Levoča',49.021728,20.592122,'Slovakia','SK','Prešovský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dolný Kubín',49.209827,19.303408,'Slovakia','SK','Žilinský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Liptovský Mikuláš',49.084418,19.612004,'Slovakia','SK','Žilinský','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Žarnovica',48.481235,18.715649,'Slovakia','SK','Banskobystrický','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Partizánske',48.628607,18.384555,'Slovakia','SK','Nitriansky','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Piešťany',48.594791,17.825908,'Slovakia','SK','Trnavský','minor',NULL,NULL);
