INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dushanbe',38.56,68.773889,'Tajikistan','TJ','Dushanbe','primary',1086244,679400);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khŭjand',40.28256,69.622155,'Tajikistan','TJ','Sughd','admin',437684,144865);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qŭrghonteppa',37.833994,68.781858,'Tajikistan','TJ','Khatlon','admin',311574,65000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Konibodom',40.294144,70.431224,'Tajikistan','TJ','Sughd','minor',259876,50359);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kŭlob',37.914585,69.784544,'Tajikistan','TJ','Khatlon','minor',115164,78786);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khorugh',37.489744,71.553045,'Tajikistan','TJ','Kŭhistoni Badakhshon','admin',30000,12035);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ishqoshim',36.724836,71.613311,'Tajikistan','TJ','Kŭhistoni Badakhshon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ismoili Somoní',37.766267,68.801259,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vahdat',38.556319,69.013545,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahrinav',38.570848,68.334978,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahriston',39.774467,68.809289,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Proletar',40.167126,69.501631,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Istaravshan',39.914204,69.003275,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Roghun',38.69331,69.736918,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ghonchí',39.962382,69.129664,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khovaling',38.341943,69.975306,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Panj',37.236341,69.09911,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tajikobod',39.124051,70.84009,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mehron',39.416911,69.286768,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dŭstí',37.348122,68.663983,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shŭrobod',37.841372,70.04865,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qubodiyon',37.409731,68.186439,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fayzobod',38.547314,69.319798,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zafarobod',40.176032,68.846789,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Baljuvon',38.308382,69.676718,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jirghatol',39.219662,71.191553,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Obikiik',38.160331,68.666049,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Farkhor',37.492188,69.403557,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Moskva',37.661014,69.628492,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vakhsh',37.714852,68.834563,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sovet',38.046702,69.588216,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sarband',37.871363,68.922328,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ayní',39.394064,68.537658,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Isfara',40.126485,70.625257,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Darband',38.867761,69.96642,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nov',40.152199,69.370764,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shaydon',40.669915,70.3502,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tursunzoda',38.512707,68.231632,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Panjakent',39.495245,67.609313,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Varzob',38.772772,68.8178,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Abdurahmoni Jomí',37.946359,68.80878,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vanj',38.370776,71.454744,'Tajikistan','TJ','Kŭhistoni Badakhshon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bŭston',40.522859,69.333075,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Danghara',38.095778,69.339978,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bahorí',37.401954,67.994458,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jilikŭl',37.491667,68.531056,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Somoniyon',38.441728,68.774582,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Murghob',38.170228,73.966736,'Tajikistan','TJ','Kŭhistoni Badakhshon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Norak',38.389166,69.322716,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hisor',38.525045,68.551236,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qalaikhumb',38.453729,70.789015,'Tajikistan','TJ','Kŭhistoni Badakhshon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rŭshon',37.944873,71.557445,'Tajikistan','TJ','Kŭhistoni Badakhshon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Roshtqal’a',37.258272,71.825912,'Tajikistan','TJ','Kŭhistoni Badakhshon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vose’',37.803955,69.644165,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tavildara',38.695289,70.484221,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rasht',39.028715,70.374459,'Tajikistan','TJ','Nohiyahoi Tobei Jumhurí','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kolkhozobod',37.588232,68.658864,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahritus',37.262065,68.138492,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mŭ’minobod',38.107144,70.03213,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Yovon',38.314083,69.037841,'Tajikistan','TJ','Khatlon','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ghafurov',40.215706,69.728668,'Tajikistan','TJ','Sughd','minor',NULL,NULL);
