INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gjakovë',42.380278,20.430833,'Kosovo','XK','Gjakovë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Graçanicë',42.601111,21.195833,'Kosovo','XK','Graçanicë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kllokot',42.371389,21.374444,'Kosovo','XK','Kllokot','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ferizaj',42.370556,21.155278,'Kosovo','XK','Ferizaj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Podujevë',42.911098,21.189942,'Kosovo','XK','Podujevë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Suharekë',42.358611,20.825,'Kosovo','XK','Suharekë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Viti',42.321389,21.358333,'Kosovo','XK','Viti','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Hani i Elezit',42.15,21.296667,'Kosovo','XK','Hani i Elezit','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Novobërdë',42.617778,21.419722,'Kosovo','XK','Novobërdë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mamushë',42.330833,20.726944,'Kosovo','XK','Mamushë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rahovec',42.399444,20.654722,'Kosovo','XK','Rahovec','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kaçanik',42.231944,21.259444,'Kosovo','XK','Kaçanik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Istog',42.780833,20.4875,'Kosovo','XK','Istog','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Fushë Kosovë',42.663944,21.096111,'Kosovo','XK','Fushë Kosovë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zveçan',42.9075,20.840278,'Kosovo','XK','Zveçan','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Prizren',42.213889,20.739722,'Kosovo','XK','Prizren','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Malishevë',42.482222,20.745833,'Kosovo','XK','Malishevë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zubin Potok',42.914444,20.689722,'Kosovo','XK','Zubin Potok','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pristina',42.666569,21.172401,'Kosovo','XK','Prishtinë','primary',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ranillug',42.492222,21.598889,'Kosovo','XK','Ranillug','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gjilan',42.468889,21.463333,'Kosovo','XK','Gjilan','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lipjan',42.521667,21.125833,'Kosovo','XK','Lipjan','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Partesh',42.401944,21.433611,'Kosovo','XK','Partesh','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Gllogovc',42.628333,20.893889,'Kosovo','XK','Gllogovc','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Klinë',42.621667,20.577778,'Kosovo','XK','Klinë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Skenderaj',42.746667,20.788611,'Kosovo','XK','Skenderaj','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Pejë',42.66,20.292222,'Kosovo','XK','Pejë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mitrovicë',42.883333,20.866667,'Kosovo','XK',NULL,'admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kamenicë',42.578056,21.580278,'Kosovo','XK','Kamenicë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Junik',42.475833,20.277222,'Kosovo','XK','Junik','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shtërpcë',42.239444,21.027222,'Kosovo','XK','Shtërpcë','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Deçan',42.537778,20.291111,'Kosovo','XK','Deçan','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shtime',42.433056,21.039722,'Kosovo','XK','Shtime','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dragash',42.0265,20.653333,'Kosovo','XK','Dragash','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Leposaviq',43.103889,20.802778,'Kosovo','XK','Leposaviq','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Obiliq',42.686944,21.070278,'Kosovo','XK','Obiliq','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Vushtrri',42.823056,20.9675,'Kosovo','XK','Vushtrri','admin',NULL,NULL);
