INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sanaa',15.354722,44.206667,'Yemen','YE','Amānat al ‘Āşimah','primary',2008000,1835853);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aden',12.779444,45.036667,'Yemen','YE','‘Adan','admin',1000000,550602);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩudaydah',14.797812,42.954516,'Yemen','YE','Al Ḩudaydah','admin',780000,475221);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ta‘izz',13.579522,44.020908,'Yemen','YE','Ta‘izz','admin',751000,615222);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Mukallā',14.542481,49.124244,'Yemen','YE','Ḩaḑramawt','admin',258132,130029);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ibb',13.940771,44.177343,'Yemen','YE','Ibb','admin',234837,234837);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩajjah',15.694247,43.605821,'Yemen','YE','Ḩajjah','admin',208287,43549);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dhamār',14.542742,44.405145,'Yemen','YE','Dhamār','admin',191259,191259);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zabīd',14.1951,43.315181,'Yemen','YE','Al Ḩudaydah','minor',152504,52590);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Say’ūn',15.943333,48.793333,'Yemen','YE','Ḩaḑramawt','minor',68747,68747);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Laḩij',13.056667,44.881944,'Yemen','YE','Laḩij','admin',66288,23375);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ash Shiḩr',14.760258,49.60537,'Yemen','YE','Ḩaḑramawt','minor',54274,54274);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Radā‘',14.415097,44.837089,'Yemen','YE','Al Bayḑā’','minor',45233,45233);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Bayḑā’',13.985226,45.572719,'Yemen','YE','Al Bayḑā’','admin',37821,37821);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('‘Ataq',14.537665,46.831868,'Yemen','YE','Shabwah','admin',37315,37315);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ghayz̧ah',16.207869,52.17605,'Yemen','YE','Al Mahrah','admin',27404,20000);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ma’rib',15.460977,45.325301,'Yemen','YE','Ma’rib','admin',16794,16794);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩadībū',12.65008,54.022336,'Yemen','YE','Arkhabīl Suquţrá','admin',11396,8545);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sayḩūt',15.210556,51.245556,'Yemen','YE','Al Mahrah','minor',189,189);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bājil',15.058984,43.287311,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Burūm',14.363611,48.979722,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩaydān',16.77899,43.433716,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kirsh',13.364734,44.490462,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḑawrān ad Daydah',14.739266,44.206644,'Yemen','YE','Dhamār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bayḩān',14.800669,45.718891,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩarīb',14.931563,45.503556,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ghayl',16.107736,44.680047,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bayt al Faqīh',14.516353,43.324459,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jiblah',13.921618,44.146684,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Tuḩaytā’',14.18356,43.226369,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bayt as Sayyid',15.504503,44.415007,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩarjah',15.488692,44.66573,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Nişāb',14.507426,46.493493,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Manşūrah',12.860191,44.981665,'Yemen','YE','‘Adan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Manşūrīyah',14.685597,43.29922,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩūth',16.231137,43.968536,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩuşūn',15.4739,45.366911,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('As Suwaydā',13.786936,45.230404,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Misrākh',13.460594,44.020432,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩabābah',15.544184,43.875632,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Madīnat Lab‘ūs',13.866667,45.25,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Ayn',13.330048,44.092085,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩabūr',16.050972,43.706991,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Qaflah',16.318973,43.767922,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩabīl ar Raydah',13.644401,44.85097,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩadādah',13.175353,44.274613,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aş Şalw',13.328872,44.217075,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bi’r Ḩāt',17.321967,52.095659,'Yemen','YE','Al Mahrah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩadīyah',14.526377,43.570449,'Yemen','YE','Raymah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mocha',13.318954,43.253171,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sharas',15.712331,43.649252,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩajab',14.851925,45.529041,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rajūzah',16.700561,44.414536,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Qanāwiş',15.492852,43.1343,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Jawl',14.456249,48.280663,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mashra‘ah',13.532353,43.995875,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ash Shuqayrah',13.134524,43.786364,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bayt Marrān',15.693119,44.205302,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kamarān',15.335097,42.609598,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('As Sukhnah',14.794076,43.436196,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('‘Ubāl',14.988081,43.544437,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dhī Nā‘im',14.105737,45.448067,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Wuday‘',13.772103,46.017855,'Yemen','YE','Abyan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Madīd',15.644527,44.47337,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bidbadah',15.425,44.7,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Māwiyah',13.582945,44.347678,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Miftāḩ',15.974314,43.46381,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ad Dīs ash Sharqīyah',14.908404,49.948473,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Banī Ḩujjāj',15.416834,43.319296,'Yemen','YE','Al Maḩwīt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mabyan',15.737726,43.557007,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Yarīm',14.298037,44.377947,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Munīrah',15.322513,42.930049,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ar Raḑmah',14.219726,44.586569,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zarājah',14.866917,44.378678,'Yemen','YE','Dhamār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Bilād',16.138056,49.291667,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aş Şawma‘ah',14.085054,45.801015,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Raydah',15.814206,44.040852,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kuḩlān ‘Affār',15.733087,43.719024,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ma‘bar',14.793954,44.29354,'Yemen','YE','Dhamār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Washḩah',16.307744,43.410662,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Malāḩīţ',16.768476,43.275818,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Riḩāb',14.227615,44.188145,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Z̧almah al ‘Ulyā',14.102296,44.09404,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Şīf',15.313889,48.33,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aslam',16.059609,43.327453,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kushar',16.155233,43.421023,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ad Dann',14.351798,43.85275,'Yemen','YE','Dhamār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aḑ Ḑāli‘',13.695723,44.73137,'Yemen','YE','Aḑ Ḑāli‘','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Az̧ Z̧alī‘ah',15.016667,48.016667,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('As Saddah',14.1221,44.42139,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ar Raḑā‘ī',14.017078,44.392986,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Madghil',15.598585,45.040132,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Musaymīr',13.443889,44.615278,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Az Zāhir',16.317325,44.495051,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qaryat ad Da‘īs',13.987701,44.274895,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Jum‘ah',14.737786,43.964886,'Yemen','YE','Dhamār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Tarīm',16.056944,48.998889,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Aqabah',14.271788,44.786994,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Markaz al Marīr',13.981777,43.595469,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Marāwi‘ah',14.830687,43.153909,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Jurbah',13.791502,45.15894,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dār an Naşr',13.558214,44.016345,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩays',13.931702,43.483099,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩazm',16.164056,44.776919,'Yemen','YE','Al Jawf','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('‘Usaylān',15.032012,45.828321,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Awābil',13.837545,44.864307,'Yemen','YE','Aḑ Ḑāli‘','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩabbān',14.354108,47.076486,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Āl Ma‘ūdah',14.210554,45.387324,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Şuwayr',16.181796,43.609855,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩişn Banī Sa‘d',16.272932,44.477278,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Matwaḩ',15.067596,43.642128,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('As Sarīr',13.738301,44.683864,'Yemen','YE','Aḑ Ḑāli‘','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩazm',14.689193,45.609617,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aţ Ţalḩ',15.155998,47.399026,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sirār',13.637785,45.313712,'Yemen','YE','Abyan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jawl al Majma‘',14.932779,47.027631,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sūq Sibāḩ',13.814355,45.392295,'Yemen','YE','Abyan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Raşad',13.712155,45.303182,'Yemen','YE','Abyan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Jarrāḩī',14.132537,43.388453,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩammām ‘Alī',14.663713,44.147628,'Yemen','YE','Dhamār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shahārat al Ghīs',16.184106,43.702278,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Thamūd',17.3,49.916667,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Maḩfid',14.058469,46.913285,'Yemen','YE','Abyan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sayyān',15.171766,44.324419,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sāqayn',16.876998,43.524987,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mūdīyah',13.928405,46.082542,'Yemen','YE','Abyan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Markaz Mudhaykirah',13.889532,43.968804,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dhaybīn',15.977123,44.129167,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩammām Damt',14.090307,44.67006,'Yemen','YE','Aḑ Ḑāli‘','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dhī Jalāl',13.623784,44.70754,'Yemen','YE','Aḑ Ḑāli‘','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Qurayshīyah',14.512205,44.853581,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Suḩayl Shibām',15.914479,48.63864,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mīdī',16.321009,42.812992,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḑawrān',13.774361,44.441959,'Yemen','YE','Aḑ Ḑāli‘','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Majz',17.069392,43.575069,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jayshān',14.252043,46.179055,'Yemen','YE','Abyan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ash Shawātī',16.78314,43.812646,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩawf',16.633825,53.033682,'Yemen','YE','Al Mahrah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ghayl Bā Wazīr',14.776111,49.366111,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ghaymān',15.272549,44.354,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aḩwar',13.52019,46.713669,'Yemen','YE','Abyan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ghaylah',14.595833,45.583333,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Aḩad',14.258333,43.641667,'Yemen','YE','Dhamār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩabīlayn',13.520016,44.850763,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('‘Amd',15.3,47.983333,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aţ Ţawīlah',15.493889,43.747778,'Yemen','YE','Al Maḩwīt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Ulayb',15.147471,49.073249,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Shirūj',14.685258,47.769255,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ar Rawnah',13.756382,43.80286,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khayrān',16.021905,43.378592,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Māfūd',15.342645,47.252172,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Mayfa’ah',14.463922,44.548658,'Yemen','YE','Dhamār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Yufrus',13.455293,43.947039,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Mirwāḩ',15.472233,43.42939,'Yemen','YE','Al Maḩwīt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sūq Shamar',15.885,43.368056,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Az Zāhir',13.966667,45.483333,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ash Shaykh ‘Uthmān',12.876777,44.993094,'Yemen','YE','‘Adan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Bāţinah',15.483333,48.433333,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ar Rawḑ',16.061449,44.810124,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩabīl al Jabr',13.604221,44.985777,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qishn',15.424089,51.678362,'Yemen','YE','Al Mahrah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ruḑūm',14.085099,47.743138,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Qurḩ',16.733333,51.483333,'Yemen','YE','Al Mahrah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Khamīs',15.185327,43.511216,'Yemen','YE','Al Maḩwīt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shibām',15.50943,43.904451,'Yemen','YE','Al Maḩwīt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Najd al Jumā‘ī',13.91581,44.324144,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Khawkhah',13.807097,43.249303,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sūq ar Rubū‘',14.511546,44.015106,'Yemen','YE','Dhamār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Az Zaydīyah',15.330491,43.006326,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Madān',16.224134,43.64383,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ar Rujum',15.457763,43.632256,'Yemen','YE','Al Maḩwīt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dhubāb',12.943051,43.410245,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩurayḑah',15.598611,48.182778,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ku‘aydinah',15.821042,43.337196,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Luḩayyah',15.703088,42.690933,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Minwakh',16.800351,48.108536,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Asdās',15.766014,45.081511,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('As Sūdah',15.958611,43.780833,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩusayn',13.791988,44.768859,'Yemen','YE','Aḑ Ḑāli‘','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Şanā’',15.4,47.766667,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Hijrah',17.297881,43.38718,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Lawdar',13.882824,45.868586,'Yemen','YE','Abyan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Maşlūb',16.182712,44.626134,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mustabā’',16.228161,43.24895,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('An Naz̧īr',16.909159,43.262261,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maqbanah',13.663939,43.687301,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ash Shaghādirah',15.62,43.520556,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ash Shāhil',15.866558,43.404949,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Abr',16.133333,47.233333,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mawza‘',13.26831,43.509933,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ar Raydah',15.035,50.479167,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ţawr al Bāḩah',13.181789,44.299655,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Makhādir',14.122239,44.197965,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Matūn',16.230632,44.584758,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('An Najd',14.421521,45.295962,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aş Şarārah',15.794486,43.869971,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('An Nāşirah',15.772769,43.809021,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Maghrabah',15.877222,43.666667,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kitāf',17.031654,44.109049,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mayfa‘ah',14.27533,47.584144,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩayfah',15.734936,44.237879,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Juban',14.011636,44.8746,'Yemen','YE','Aḑ Ḑāli‘','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ad Durayhimī',14.637019,43.055048,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aş Şafaqayn',15.379221,43.420456,'Yemen','YE','Al Maḩwīt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Waḑarah',15.710726,43.48321,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Mashāf',16.858358,43.197811,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maswarah',14.343993,45.726229,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Raḩabah al Kawlah',14.895735,44.989185,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Qaţan',15.840556,48.455556,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Banī an Nahārī',15.639809,43.556326,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Maḩjal',16.711686,44.847693,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Amūd',14.721028,45.206763,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Jiḩānah',15.226282,44.482444,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('At Tawāhī',12.784706,44.980203,'Yemen','YE','‘Adan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('‘Amrān',15.659398,43.943852,'Yemen','YE','‘Amrān','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Shiḩan as Suflá',17.769994,52.489253,'Yemen','YE','Al Mahrah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zinjibār',13.128712,45.380728,'Yemen','YE','Abyan','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Aqţa‘',14.662166,45.35123,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Urr',15.246476,43.888362,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Maḩwīt',15.470072,43.544812,'Yemen','YE','Al Maḩwīt','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bayt ‘Adhāqah',15.615764,43.702278,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('As Sūq al Jadīd',15.82496,44.062044,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Kharāb',16.991294,43.338877,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Az Zuhrah',15.72377,42.995821,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Ashshah',16.256525,43.854763,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('As Salāsil',16.47959,48.83153,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Dhī as Sufāl',13.834457,44.114686,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩarf',16.363946,44.094213,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sūq al Khamīs',17.181257,43.28811,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('‘Abs',16.002948,43.197245,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Wa‘lān',15.070206,44.276411,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ad Dimnah',13.453977,44.181678,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Jamīmah',16.017868,43.596474,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aş Şalīf',15.307554,42.671066,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Riqāb',14.885965,43.464912,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Marbāţ',14.205672,46.38811,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Anān',16.721885,44.312521,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qaryat al Qābil',15.45033,44.127685,'Yemen','YE','Amānat al ‘Āşimah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩaşwayn',15.590488,52.100765,'Yemen','YE','Al Mahrah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Kusmah',14.581748,43.636763,'Yemen','YE','Raymah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Milāḩ',13.426111,44.825556,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Milāḩ',14.416172,44.786219,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Manākhah',15.074217,43.741564,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Matnah',15.253333,44.024722,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩajar al Mushā’ikh',16.133333,47.833333,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ash Sharyah',14.356586,45.022441,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Bāqim as Sūq',17.397132,43.477426,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sāh',15.577222,48.850556,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Judaydah',15.07512,45.299622,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Āqir',14.56816,45.911562,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('An Nādirah',14.096276,44.475586,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Majzar',15.85,44.775,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ja‘ār',13.223003,45.305585,'Yemen','YE','Abyan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mafḩaq',15.101619,43.903043,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Zakhim',14.294963,44.685041,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ar Rubū‘',13.780236,43.869006,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩawrah',13.357509,44.145801,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('As Sayyānī',13.842658,44.173948,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Mighlāf',15.287724,43.189099,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qa‘ţabah',13.854933,44.705805,'Yemen','YE','Aḑ Ḑāli‘','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khamir',15.987919,43.953619,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Khirāb',16.554405,44.290476,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Mukayrās',13.944275,45.670739,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Rimāh',17.45532,50.577887,'Yemen','YE','Ḩaḑramawt','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Daḩasuways',15.723889,50.729444,'Yemen','YE','Al Mahrah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ma‘allā’',12.789867,45.002437,'Yemen','YE','‘Adan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al ‘Udayn',13.969184,43.996728,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Banī Bakr',13.933333,45.266667,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Z̧abah',14.490517,44.131085,'Yemen','YE','Dhamār','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩumaydāt',16.484396,44.429345,'Yemen','YE','Al Jawf','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ar Ramādī',13.956407,43.784574,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Saḩḩab',15.602231,44.024203,'Yemen','YE','‘Amrān','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩayfān',13.317781,44.280114,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('As Sawādīyah',14.301129,45.22148,'Yemen','YE','Al Bayḑā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Khāniq',15.502534,44.181576,'Yemen','YE','Şan‘ā’','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Crater',12.7775,45.032778,'Yemen','YE','‘Adan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Ḩashwah',16.906408,44.276222,'Yemen','YE','Şa‘dah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('At Turbah',13.212704,44.124148,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Nashmah',13.390278,43.968333,'Yemen','YE','Ta‘izz','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aḑ Ḑil‘',14.671989,43.818275,'Yemen','YE','Raymah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Jabīn',14.704007,43.599043,'Yemen','YE','Raymah','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Sūq Şirwāḩ',15.449328,45.018915,'Yemen','YE','Ma’rib','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ar Rawḑah',14.46725,47.276379,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ar Rawḑah',15.432512,44.223991,'Yemen','YE','Amānat al ‘Āşimah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Banī al ‘Awwām',15.581187,43.587271,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩazm al ‘Udayn',14.027433,44.005258,'Yemen','YE','Ibb','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aş Şa‘īd',14.330111,46.87292,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ḩaraḑ',16.409654,43.058834,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Aḑ Ḑaḩī',15.215175,43.070203,'Yemen','YE','Al Ḩudaydah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Ash Shaţţ',12.893569,44.035706,'Yemen','YE','Laḩij','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Şa‘dah',16.940208,43.763935,'Yemen','YE','Şa‘dah','admin',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Burayqah',12.739444,44.884167,'Yemen','YE','‘Adan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Al Maḩābishah',15.947582,43.435868,'Yemen','YE','Ḩajjah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khawr Maksar',12.812273,45.033371,'Yemen','YE','‘Adan','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Khawrah',14.432012,46.154353,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Maţarah',15.525911,47.633388,'Yemen','YE','Shabwah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Markaz Bilād aţ Ţa‘ām',14.833611,43.536389,'Yemen','YE','Raymah','minor',NULL,NULL);
INSERT INTO next_destinations(city,lat,lng,country,iso2,auser,capital,population,population_proper) VALUES ('Qalansīyah',12.689578,53.487085,'Yemen','YE','Arkhabīl Suquţrá','minor',NULL,NULL);
